use crate::{
    ObjectId, ProfileAuthority, SchemaContractError, SchemaContractErrorKind, SchemaObjectKind,
    SemanticValue, encode_generated_identifier, encode_generated_path,
};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

const GENERATED_PROFILE_IMPORTS: &[(&str, &[&str])] = &[
    ("sifr.datetime", &["date", "datetime", "time"]),
    ("sifr.json", &["JsonValue"]),
    (
        "sifr.sql",
        &[
            "CalendarInterval",
            "IPAddress",
            "IPNetwork",
            "Instant",
            "MacAddress",
            "MultiRange",
            "Numeric",
            "OffsetTime",
            "Range",
            "SqlArray",
            "SqlEnum",
            "SqlSchema",
        ],
    ),
    ("sifr.uuid", &["UUID"]),
];

const GENERATED_PROFILE_BUILTINS: &[&str] = &[
    "None",
    "bigdecimal",
    "bool",
    "bytes",
    "decimal",
    "float",
    "int",
    "int8",
    "int16",
    "int32",
    "int64",
    "list",
    "str",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
];

pub const COMPILER_KNOWN_PROFILE_EXPORTS: &[&str] = &[
    "Schema",
    "all",
    "any",
    "composites",
    "connect",
    "domains",
    "enums",
    "not_",
    "open_pool",
    "query",
    "schema",
    "sql",
    "symbol",
];

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum GeneratedSchemaType {
    Enum {
        identity: ObjectId,
        path: Vec<String>,
        variants: Vec<String>,
    },
    Domain {
        identity: ObjectId,
        path: Vec<String>,
        storage_type: String,
    },
    Composite {
        identity: ObjectId,
        path: Vec<String>,
        fields: BTreeMap<String, String>,
    },
}

impl GeneratedSchemaType {
    fn path(&self) -> &[String] {
        match self {
            Self::Enum { path, .. } | Self::Domain { path, .. } | Self::Composite { path, .. } => {
                path
            }
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileModuleMetadata {
    pub profile_name: String,
    pub nominal_identity: String,
    pub profile_fingerprint: String,
    pub schema_fingerprint: String,
    pub compiler_known_exports: BTreeSet<String>,
    pub generated_types: Vec<GeneratedSchemaType>,
    pub schema_symbols: BTreeSet<ObjectId>,
    pub schema_witness: SchemaWitnessMetadata,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SchemaWitnessMetadata {
    pub export_name: String,
    pub profile_identity: String,
    pub type_name: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedProfileModule {
    pub module_path: String,
    pub source: String,
    pub metadata: ProfileModuleMetadata,
}

impl GeneratedProfileModule {
    pub fn lookup_static_symbol(
        &self,
        authority: &ProfileAuthority,
        name: &str,
    ) -> Result<ObjectId, SchemaContractError> {
        let object = authority.profile.schema.resolve_symbol(name)?;
        if !self.metadata.schema_symbols.contains(&object.identity) {
            return Err(SchemaContractError::new(
                SchemaContractErrorKind::UnknownSymbol,
                format!("schema symbol '{name}' is absent from generated module metadata"),
            ));
        }
        Ok(object.identity.clone())
    }
}

pub fn generate_profile_module(
    authority: &ProfileAuthority,
) -> Result<GeneratedProfileModule, SchemaContractError> {
    let generated_types = generated_types(authority)?;
    let compiler_known_exports = COMPILER_KNOWN_PROFILE_EXPORTS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();
    let mut source = format!(
        "# Generated by Sifr. Do not edit.\n# profile-identity: {}\n\n",
        authority.nominal_identity
    );
    render_generated_imports(&mut source)?;
    source.push_str("\nclass Schema:\n    pass\n\nschema: SqlSchema[Schema]\n");
    for generated in &generated_types {
        render_generated_type(&mut source, generated)?;
    }
    let metadata = ProfileModuleMetadata {
        profile_name: authority.profile.name.clone(),
        nominal_identity: authority.nominal_identity.clone(),
        profile_fingerprint: authority.profile_fingerprint.as_str().to_string(),
        schema_fingerprint: authority.schema_fingerprint.as_str().to_string(),
        compiler_known_exports,
        generated_types,
        schema_symbols: authority.profile.schema.objects.keys().cloned().collect(),
        schema_witness: SchemaWitnessMetadata {
            export_name: "schema".to_string(),
            profile_identity: authority.nominal_identity.clone(),
            type_name: format!("SqlSchema[{}]", authority.nominal_identity),
        },
    };
    Ok(GeneratedProfileModule {
        module_path: format!("sifr.sql.schemas.{}", authority.profile.name),
        source,
        metadata,
    })
}

fn render_generated_imports(source: &mut String) -> Result<(), SchemaContractError> {
    for (module, names) in GENERATED_PROFILE_IMPORTS {
        writeln!(source, "from {module} import {}", names.join(", ")).map_err(format_error)?;
    }
    Ok(())
}

fn render_generated_type(
    source: &mut String,
    generated: &GeneratedSchemaType,
) -> Result<(), SchemaContractError> {
    match generated {
        GeneratedSchemaType::Enum { path, variants, .. } => {
            let name = encode_generated_path(path)?;
            writeln!(source, "\nclass {name}(SqlEnum):").map_err(format_error)?;
            for (index, variant) in variants.iter().enumerate() {
                writeln!(
                    source,
                    "    {} = {index}",
                    encode_generated_identifier(variant)?
                )
                .map_err(format_error)?;
            }
            if variants.is_empty() {
                source.push_str("    pass\n");
            }
        }
        GeneratedSchemaType::Domain {
            path, storage_type, ..
        } => {
            let name = encode_generated_path(path)?;
            writeln!(source, "\nclass {name}:\n    value: {storage_type}").map_err(format_error)?;
        }
        GeneratedSchemaType::Composite { path, fields, .. } => {
            let name = encode_generated_path(path)?;
            writeln!(source, "\nclass {name}:").map_err(format_error)?;
            for (field, field_type) in fields {
                writeln!(
                    source,
                    "    {}: {field_type}",
                    encode_generated_identifier(field)?
                )
                .map_err(format_error)?;
            }
            if fields.is_empty() {
                source.push_str("    pass\n");
            }
        }
    }
    Ok(())
}

fn generated_types(
    authority: &ProfileAuthority,
) -> Result<Vec<GeneratedSchemaType>, SchemaContractError> {
    let mut generated = Vec::new();
    for object in authority.profile.schema.objects.values() {
        let qualified = qualified_generated_path(object.identity.as_str())?;
        let candidate = match object.kind {
            SchemaObjectKind::Enum => Some(GeneratedSchemaType::Enum {
                identity: object.identity.clone(),
                path: generated_path("enums", &qualified),
                variants: identifier_list_property(object, "variants")?,
            }),
            SchemaObjectKind::Domain => Some(GeneratedSchemaType::Domain {
                identity: object.identity.clone(),
                path: generated_path("domains", &qualified),
                storage_type: type_property(object, "sifr_type")?.to_string(),
            }),
            SchemaObjectKind::Composite => Some(GeneratedSchemaType::Composite {
                identity: object.identity.clone(),
                path: generated_path("composites", &qualified),
                fields: type_map_property(object, "fields")?,
            }),
            _ => None,
        };
        if let Some(candidate) = candidate {
            if generated
                .iter()
                .any(|existing: &GeneratedSchemaType| existing.path() == candidate.path())
            {
                return Err(SchemaContractError::new(
                    SchemaContractErrorKind::InvalidSchema,
                    format!(
                        "generated schema type path '{}' is ambiguous",
                        candidate.path().join(".")
                    ),
                ));
            }
            generated.push(candidate);
        }
    }
    generated.sort_by(|left, right| left.path().cmp(right.path()));
    validate_generated_type_bindings(&generated, GENERATED_PROFILE_IMPORTS)?;
    Ok(generated)
}

fn validate_generated_type_bindings(
    generated: &[GeneratedSchemaType],
    imports: &[(&str, &[&str])],
) -> Result<(), SchemaContractError> {
    let mut bound = GENERATED_PROFILE_BUILTINS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();
    for (_, names) in imports {
        bound.extend(names.iter().map(|name| (*name).to_string()));
    }
    bound.extend(
        generated
            .iter()
            .map(GeneratedSchemaType::path)
            .map(encode_generated_path)
            .collect::<Result<Vec<_>, _>>()?,
    );
    for generated_type in generated {
        let expressions = match generated_type {
            GeneratedSchemaType::Domain { storage_type, .. } => std::slice::from_ref(storage_type),
            GeneratedSchemaType::Composite { fields, .. } => {
                for expression in fields.values() {
                    validate_bound_type_expression(expression, &bound)?;
                }
                continue;
            }
            GeneratedSchemaType::Enum { .. } => continue,
        };
        for expression in expressions {
            validate_bound_type_expression(expression, &bound)?;
        }
    }
    Ok(())
}

fn validate_bound_type_expression(
    expression: &str,
    bound: &BTreeSet<String>,
) -> Result<(), SchemaContractError> {
    for primary in top_level_type_members(expression) {
        let (name, inner) = type_primary_parts(primary);
        if !bound.contains(name) {
            return Err(SchemaContractError::new(
                SchemaContractErrorKind::InvalidSchema,
                format!("generated Sifr type annotation '{name}' has no declaration or import"),
            ));
        }
        if let Some(inner) = inner {
            validate_bound_type_expression(inner, bound)?;
        }
    }
    Ok(())
}

fn top_level_type_members(value: &str) -> Vec<&str> {
    let mut depth = 0usize;
    let mut start = 0usize;
    let mut members = Vec::new();
    for (index, byte) in value.bytes().enumerate() {
        match byte {
            b'[' => depth += 1,
            b']' => depth = depth.saturating_sub(1),
            b'|' if depth == 0 => {
                members.push(value[start..index].trim());
                start = index + 1;
            }
            _ => {}
        }
    }
    members.push(value[start..].trim());
    members
}

fn type_primary_parts(value: &str) -> (&str, Option<&str>) {
    value.find('[').map_or((value, None), |open| {
        (&value[..open], Some(&value[open + 1..value.len() - 1]))
    })
}

/// Render the canonical source annotation for a provider-neutral SQL type.
///
/// Generated profile modules validate the returned name against the import
/// table above. This keeps provider output and generated imports closed over
/// one vocabulary.
pub fn generated_sifr_type_name(ty: &crate::SifrType) -> Result<String, SchemaContractError> {
    use crate::{IntegerSign, IntegerWidth, SifrType};

    match ty {
        SifrType::Bool => Ok("bool".to_string()),
        SifrType::FixedInteger { sign, width } => Ok(match (sign, width) {
            (IntegerSign::Signed, IntegerWidth::Bits8) => "int8",
            (IntegerSign::Signed, IntegerWidth::Bits16) => "int16",
            (IntegerSign::Signed, IntegerWidth::Bits32) => "int32",
            (IntegerSign::Signed, IntegerWidth::Bits64) => "int64",
            (IntegerSign::Unsigned, IntegerWidth::Bits8) => "uint8",
            (IntegerSign::Unsigned, IntegerWidth::Bits16) => "uint16",
            (IntegerSign::Unsigned, IntegerWidth::Bits32) => "uint32",
            (IntegerSign::Unsigned, IntegerWidth::Bits64) => "uint64",
        }
        .to_string()),
        SifrType::ExactInteger => Ok("int".to_string()),
        SifrType::Decimal => Ok("decimal".to_string()),
        SifrType::BigDecimal => Ok("bigdecimal".to_string()),
        SifrType::Numeric => Ok("Numeric".to_string()),
        SifrType::Float => Ok("float".to_string()),
        SifrType::Str => Ok("str".to_string()),
        SifrType::Bytes => Ok("bytes".to_string()),
        SifrType::Date => Ok("date".to_string()),
        SifrType::LocalTime => Ok("time".to_string()),
        SifrType::OffsetTime => Ok("OffsetTime".to_string()),
        SifrType::LocalDateTime => Ok("datetime".to_string()),
        SifrType::Instant => Ok("Instant".to_string()),
        SifrType::CalendarInterval => Ok("CalendarInterval".to_string()),
        SifrType::Uuid => Ok("UUID".to_string()),
        SifrType::JsonValue => Ok("JsonValue".to_string()),
        SifrType::None => Ok("None".to_string()),
        SifrType::IpAddress => Ok("IPAddress".to_string()),
        SifrType::IpNetwork => Ok("IPNetwork".to_string()),
        SifrType::MacAddress => Ok("MacAddress".to_string()),
        SifrType::Nominal { identity } => Ok(identity.as_str().to_string()),
        SifrType::Custom { identity } => Ok(identity.clone()),
        SifrType::List { element } => Ok(format!("list[{}]", generated_sifr_type_name(element)?)),
        SifrType::SqlArray { element } => {
            Ok(format!("SqlArray[{}]", generated_sifr_type_name(element)?))
        }
        SifrType::Range {
            element,
            multirange,
        } => Ok(format!(
            "{}[{}]",
            if *multirange { "MultiRange" } else { "Range" },
            generated_sifr_type_name(element)?
        )),
        SifrType::Union { members } => members
            .iter()
            .map(generated_sifr_type_name)
            .collect::<Result<Vec<_>, _>>()
            .map(|members| members.join(" | ")),
    }
}

fn type_property<'a>(
    object: &'a crate::SchemaObject,
    name: &str,
) -> Result<&'a str, SchemaContractError> {
    match object.semantic.get(name) {
        Some(SemanticValue::Text(value)) if valid_type_expression(value) => Ok(value),
        _ => Err(invalid_generated_property(object, name)),
    }
}

fn identifier_list_property(
    object: &crate::SchemaObject,
    name: &str,
) -> Result<Vec<String>, SchemaContractError> {
    let Some(SemanticValue::List(values)) = object.semantic.get(name) else {
        return Err(invalid_generated_property(object, name));
    };
    let variants = values
        .iter()
        .map(|value| match value {
            SemanticValue::Text(value) if valid_identifier(value) => Ok(value.clone()),
            _ => Err(invalid_generated_property(object, name)),
        })
        .collect::<Result<Vec<_>, _>>()?;
    if variants.iter().collect::<BTreeSet<_>>().len() != variants.len() {
        return Err(invalid_generated_property(object, name));
    }
    Ok(variants)
}

fn type_map_property(
    object: &crate::SchemaObject,
    name: &str,
) -> Result<BTreeMap<String, String>, SchemaContractError> {
    let Some(SemanticValue::Map(values)) = object.semantic.get(name) else {
        return Err(invalid_generated_property(object, name));
    };
    values
        .iter()
        .map(|(key, value)| match value {
            SemanticValue::Text(value) if valid_identifier(key) && valid_type_expression(value) => {
                Ok((key.clone(), value.clone()))
            }
            _ => Err(invalid_generated_property(object, name)),
        })
        .collect()
}

fn invalid_generated_property(object: &crate::SchemaObject, name: &str) -> SchemaContractError {
    SchemaContractError::new(
        SchemaContractErrorKind::InvalidSchema,
        format!(
            "schema object '{}' needs canonical '{name}' metadata for Sifr generation",
            object.identity
        ),
    )
}

fn qualified_generated_path(identity: &str) -> Result<Vec<String>, SchemaContractError> {
    identity
        .split('.')
        .map(|name| {
            if valid_identifier(name) {
                Ok(name.to_string())
            } else {
                Err(SchemaContractError::new(
                    SchemaContractErrorKind::InvalidSchema,
                    format!("schema type identity '{identity}' cannot be emitted as Sifr"),
                ))
            }
        })
        .collect()
}

fn generated_path(category: &str, qualified: &[String]) -> Vec<String> {
    std::iter::once(category.to_string())
        .chain(qualified.iter().cloned())
        .collect()
}

use crate::identifier::{is_sifr_keyword, valid_identifier};

fn valid_type_expression(value: &str) -> bool {
    let mut depth = 0usize;
    let mut start = 0usize;
    let bytes = value.as_bytes();
    let mut index = 0usize;
    while index < bytes.len() {
        match bytes[index] {
            b'[' => depth += 1,
            b']' => {
                let Some(next) = depth.checked_sub(1) else {
                    return false;
                };
                depth = next;
            }
            b'|' if depth == 0 => {
                if index == 0
                    || bytes.get(index.wrapping_sub(1)) != Some(&b' ')
                    || bytes.get(index + 1) != Some(&b' ')
                    || !valid_type_primary(&value[start..index - 1])
                {
                    return false;
                }
                start = index + 2;
                index += 1;
            }
            _ => {}
        }
        index += 1;
    }
    depth == 0 && start < value.len() && valid_type_primary(&value[start..])
}

fn valid_type_primary(value: &str) -> bool {
    let Some(open) = value.find('[') else {
        return valid_type_name(value);
    };
    if !value.ends_with(']') || !valid_type_name(&value[..open]) {
        return false;
    }
    let inner = &value[open + 1..value.len() - 1];
    !inner.is_empty() && valid_type_expression(inner)
}

fn valid_type_name(value: &str) -> bool {
    GENERATED_PROFILE_BUILTINS.contains(&value)
        || (!value.is_empty()
            && value
                .split('.')
                .all(|part| valid_identifier(part) && !is_sifr_keyword(part)))
}

fn format_error(_: std::fmt::Error) -> SchemaContractError {
    SchemaContractError::new(
        SchemaContractErrorKind::Serialization,
        "cannot render generated profile module",
    )
}

#[cfg(test)]
mod tests {
    use super::{
        GENERATED_PROFILE_IMPORTS, GeneratedSchemaType, valid_type_expression,
        validate_generated_type_bindings,
    };
    use crate::ObjectId;

    #[test]
    fn generated_type_expression_validation_accepts_closed_nested_types() {
        for value in [
            "i64",
            "None",
            "Numeric",
            "list[domains__public__positive_id]",
            "Range[decimal]",
            "list[Range[decimal | None]]",
            "str | None",
        ] {
            assert!(valid_type_expression(value), "{value}");
        }
    }

    #[test]
    fn generated_type_expression_validation_rejects_source_injection() {
        for value in [
            "",
            "class",
            "list[]",
            "list[i64",
            "list[i64]]",
            "i64|str",
            "i64 | ",
            "i64; print('unsafe')",
        ] {
            assert!(!valid_type_expression(value), "{value}");
        }
    }

    #[test]
    fn generated_type_binding_validation_rejects_a_missing_import() {
        let generated = vec![GeneratedSchemaType::Domain {
            identity: ObjectId::new("public.identifier"),
            path: vec![
                "domains".to_string(),
                "public".to_string(),
                "identifier".to_string(),
            ],
            storage_type: "UUID".to_string(),
        }];
        let imports = GENERATED_PROFILE_IMPORTS
            .iter()
            .copied()
            .filter(|(module, _)| *module != "sifr.uuid")
            .collect::<Vec<_>>();
        let error = validate_generated_type_bindings(&generated, &imports)
            .expect_err("UUID must have an import");
        assert!(error.message.contains("UUID"));
    }
}
