use crate::{
    ObjectId, ProfileAuthority, SchemaContractError, SchemaContractErrorKind, SchemaObjectKind,
    SemanticValue, encode_generated_identifier, encode_generated_path,
};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

pub const COMPILER_KNOWN_PROFILE_EXPORTS: &[&str] = &[
    "Schema",
    "all",
    "any",
    "composites",
    "connect",
    "domains",
    "enums",
    "not_",
    "open_pool",
    "query",
    "schema",
    "sql",
    "symbol",
];

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum GeneratedSchemaType {
    Enum {
        identity: ObjectId,
        path: Vec<String>,
        variants: Vec<String>,
    },
    Domain {
        identity: ObjectId,
        path: Vec<String>,
        storage_type: String,
    },
    Composite {
        identity: ObjectId,
        path: Vec<String>,
        fields: BTreeMap<String, String>,
    },
}

impl GeneratedSchemaType {
    fn path(&self) -> &[String] {
        match self {
            Self::Enum { path, .. } | Self::Domain { path, .. } | Self::Composite { path, .. } => {
                path
            }
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileModuleMetadata {
    pub profile_name: String,
    pub nominal_identity: String,
    pub profile_fingerprint: String,
    pub schema_fingerprint: String,
    pub compiler_known_exports: BTreeSet<String>,
    pub generated_types: Vec<GeneratedSchemaType>,
    pub schema_symbols: BTreeSet<ObjectId>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedProfileModule {
    pub module_path: String,
    pub source: String,
    pub metadata: ProfileModuleMetadata,
}

impl GeneratedProfileModule {
    pub fn lookup_static_symbol(
        &self,
        authority: &ProfileAuthority,
        name: &str,
    ) -> Result<ObjectId, SchemaContractError> {
        let object = authority.profile.schema.resolve_symbol(name)?;
        if !self.metadata.schema_symbols.contains(&object.identity) {
            return Err(SchemaContractError::new(
                SchemaContractErrorKind::UnknownSymbol,
                format!("schema symbol '{name}' is absent from generated module metadata"),
            ));
        }
        Ok(object.identity.clone())
    }
}

pub fn generate_profile_module(
    authority: &ProfileAuthority,
) -> Result<GeneratedProfileModule, SchemaContractError> {
    let generated_types = generated_types(authority)?;
    let compiler_known_exports = COMPILER_KNOWN_PROFILE_EXPORTS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();
    let mut source = format!(
        "# Generated by Sifr. Do not edit.\n# profile-identity: {}\n\nfrom enum import Enum\n\nclass Schema:\n    pass\n",
        authority.nominal_identity
    );
    for generated in &generated_types {
        render_generated_type(&mut source, generated)?;
    }
    let metadata = ProfileModuleMetadata {
        profile_name: authority.profile.name.clone(),
        nominal_identity: authority.nominal_identity.clone(),
        profile_fingerprint: authority.profile_fingerprint.as_str().to_string(),
        schema_fingerprint: authority.schema_fingerprint.as_str().to_string(),
        compiler_known_exports,
        generated_types,
        schema_symbols: authority.profile.schema.objects.keys().cloned().collect(),
    };
    Ok(GeneratedProfileModule {
        module_path: format!("sifr.sql.schemas.{}", authority.profile.name),
        source,
        metadata,
    })
}

fn render_generated_type(
    source: &mut String,
    generated: &GeneratedSchemaType,
) -> Result<(), SchemaContractError> {
    match generated {
        GeneratedSchemaType::Enum { path, variants, .. } => {
            let name = encode_generated_path(path)?;
            writeln!(source, "\nclass {name}(Enum):").map_err(format_error)?;
            for (index, variant) in variants.iter().enumerate() {
                writeln!(
                    source,
                    "    {} = {index}",
                    encode_generated_identifier(variant)?
                )
                .map_err(format_error)?;
            }
            if variants.is_empty() {
                source.push_str("    pass\n");
            }
        }
        GeneratedSchemaType::Domain {
            path, storage_type, ..
        } => {
            let name = encode_generated_path(path)?;
            writeln!(source, "\nclass {name}:\n    value: {storage_type}").map_err(format_error)?;
        }
        GeneratedSchemaType::Composite { path, fields, .. } => {
            let name = encode_generated_path(path)?;
            writeln!(source, "\nclass {name}:").map_err(format_error)?;
            for (field, field_type) in fields {
                writeln!(
                    source,
                    "    {}: {field_type}",
                    encode_generated_identifier(field)?
                )
                .map_err(format_error)?;
            }
            if fields.is_empty() {
                source.push_str("    pass\n");
            }
        }
    }
    Ok(())
}

fn generated_types(
    authority: &ProfileAuthority,
) -> Result<Vec<GeneratedSchemaType>, SchemaContractError> {
    let mut generated = Vec::new();
    for object in authority.profile.schema.objects.values() {
        let qualified = qualified_generated_path(object.identity.as_str())?;
        let candidate = match object.kind {
            SchemaObjectKind::Enum => Some(GeneratedSchemaType::Enum {
                identity: object.identity.clone(),
                path: generated_path("enums", &qualified),
                variants: identifier_list_property(object, "variants")?,
            }),
            SchemaObjectKind::Domain => Some(GeneratedSchemaType::Domain {
                identity: object.identity.clone(),
                path: generated_path("domains", &qualified),
                storage_type: type_property(object, "sifr_type")?.to_string(),
            }),
            SchemaObjectKind::Composite => Some(GeneratedSchemaType::Composite {
                identity: object.identity.clone(),
                path: generated_path("composites", &qualified),
                fields: type_map_property(object, "fields")?,
            }),
            _ => None,
        };
        if let Some(candidate) = candidate {
            if generated
                .iter()
                .any(|existing: &GeneratedSchemaType| existing.path() == candidate.path())
            {
                return Err(SchemaContractError::new(
                    SchemaContractErrorKind::InvalidSchema,
                    format!(
                        "generated schema type path '{}' is ambiguous",
                        candidate.path().join(".")
                    ),
                ));
            }
            generated.push(candidate);
        }
    }
    generated.sort_by(|left, right| left.path().cmp(right.path()));
    Ok(generated)
}

fn type_property<'a>(
    object: &'a crate::SchemaObject,
    name: &str,
) -> Result<&'a str, SchemaContractError> {
    match object.semantic.get(name) {
        Some(SemanticValue::Text(value)) if valid_type_path(value) => Ok(value),
        _ => Err(invalid_generated_property(object, name)),
    }
}

fn identifier_list_property(
    object: &crate::SchemaObject,
    name: &str,
) -> Result<Vec<String>, SchemaContractError> {
    let Some(SemanticValue::List(values)) = object.semantic.get(name) else {
        return Err(invalid_generated_property(object, name));
    };
    let variants = values
        .iter()
        .map(|value| match value {
            SemanticValue::Text(value) if valid_identifier(value) => Ok(value.clone()),
            _ => Err(invalid_generated_property(object, name)),
        })
        .collect::<Result<Vec<_>, _>>()?;
    if variants.iter().collect::<BTreeSet<_>>().len() != variants.len() {
        return Err(invalid_generated_property(object, name));
    }
    Ok(variants)
}

fn type_map_property(
    object: &crate::SchemaObject,
    name: &str,
) -> Result<BTreeMap<String, String>, SchemaContractError> {
    let Some(SemanticValue::Map(values)) = object.semantic.get(name) else {
        return Err(invalid_generated_property(object, name));
    };
    values
        .iter()
        .map(|(key, value)| match value {
            SemanticValue::Text(value) if valid_identifier(key) && valid_type_path(value) => {
                Ok((key.clone(), value.clone()))
            }
            _ => Err(invalid_generated_property(object, name)),
        })
        .collect()
}

fn invalid_generated_property(object: &crate::SchemaObject, name: &str) -> SchemaContractError {
    SchemaContractError::new(
        SchemaContractErrorKind::InvalidSchema,
        format!(
            "schema object '{}' needs canonical '{name}' metadata for Sifr generation",
            object.identity
        ),
    )
}

fn qualified_generated_path(identity: &str) -> Result<Vec<String>, SchemaContractError> {
    identity
        .split('.')
        .map(|name| {
            if valid_identifier(name) {
                Ok(name.to_string())
            } else {
                Err(SchemaContractError::new(
                    SchemaContractErrorKind::InvalidSchema,
                    format!("schema type identity '{identity}' cannot be emitted as Sifr"),
                ))
            }
        })
        .collect()
}

fn generated_path(category: &str, qualified: &[String]) -> Vec<String> {
    std::iter::once(category.to_string())
        .chain(qualified.iter().cloned())
        .collect()
}

use crate::identifier::{is_sifr_keyword, valid_identifier};

fn valid_type_path(value: &str) -> bool {
    !value.is_empty()
        && value
            .split('.')
            .all(|part| valid_identifier(part) && !is_sifr_keyword(part))
}

fn format_error(_: std::fmt::Error) -> SchemaContractError {
    SchemaContractError::new(
        SchemaContractErrorKind::Serialization,
        "cannot render generated profile module",
    )
}
