use crate::{
    ObjectId, ProfileAuthority, SchemaContractError, SchemaContractErrorKind, SchemaObjectKind,
    SemanticValue,
};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

pub const COMPILER_KNOWN_PROFILE_EXPORTS: &[&str] = &[
    "Schema",
    "all",
    "any",
    "composites",
    "connect",
    "domains",
    "enums",
    "not_",
    "open_pool",
    "query",
    "schema",
    "sql",
    "symbol",
];

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum GeneratedSchemaType {
    Enum {
        name: String,
        variants: Vec<String>,
    },
    Domain {
        name: String,
        storage_type: String,
    },
    Composite {
        name: String,
        fields: BTreeMap<String, String>,
    },
}

impl GeneratedSchemaType {
    fn name(&self) -> &str {
        match self {
            Self::Enum { name, .. } | Self::Domain { name, .. } | Self::Composite { name, .. } => {
                name
            }
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileModuleMetadata {
    pub profile_name: String,
    pub nominal_identity: String,
    pub profile_fingerprint: String,
    pub schema_fingerprint: String,
    pub compiler_known_exports: BTreeSet<String>,
    pub generated_types: Vec<GeneratedSchemaType>,
    pub schema_symbols: BTreeSet<ObjectId>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedProfileModule {
    pub module_path: String,
    pub source: String,
    pub metadata: ProfileModuleMetadata,
}

impl GeneratedProfileModule {
    pub fn lookup_static_symbol(
        &self,
        authority: &ProfileAuthority,
        name: &str,
    ) -> Result<ObjectId, SchemaContractError> {
        let object = authority.profile.schema.resolve_symbol(name)?;
        Ok(object.identity.clone())
    }
}

pub fn generate_profile_module(
    authority: &ProfileAuthority,
) -> Result<GeneratedProfileModule, SchemaContractError> {
    let generated_types = generated_types(authority)?;
    let compiler_known_exports = COMPILER_KNOWN_PROFILE_EXPORTS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();
    let mut source = format!(
        "# Generated by Sifr. Do not edit.\n# profile-identity: {}\n\nfrom enum import Enum\n\nclass Schema:\n    pass\n",
        authority.nominal_identity
    );
    for generated in &generated_types {
        match generated {
            GeneratedSchemaType::Enum { name, variants } => {
                write!(source, "\nclass {name}(Enum):\n").map_err(format_error)?;
                for (index, variant) in variants.iter().enumerate() {
                    writeln!(source, "    {variant} = {index}").map_err(format_error)?;
                }
            }
            GeneratedSchemaType::Domain { name, storage_type } => {
                writeln!(source, "\nclass {name}:\n    value: {storage_type}")
                    .map_err(format_error)?;
            }
            GeneratedSchemaType::Composite { name, fields } => {
                writeln!(source, "\nclass {name}:").map_err(format_error)?;
                for (field, field_type) in fields {
                    writeln!(source, "    {field}: {field_type}").map_err(format_error)?;
                }
                if fields.is_empty() {
                    source.push_str("    pass\n");
                }
            }
        }
    }
    let metadata = ProfileModuleMetadata {
        profile_name: authority.profile.name.clone(),
        nominal_identity: authority.nominal_identity.clone(),
        profile_fingerprint: authority.profile_fingerprint.as_str().to_string(),
        schema_fingerprint: authority.schema_fingerprint.as_str().to_string(),
        compiler_known_exports,
        generated_types,
        schema_symbols: authority.profile.schema.objects.keys().cloned().collect(),
    };
    Ok(GeneratedProfileModule {
        module_path: format!("sifr.sql.schemas.{}", authority.profile.name),
        source,
        metadata,
    })
}

fn generated_types(
    authority: &ProfileAuthority,
) -> Result<Vec<GeneratedSchemaType>, SchemaContractError> {
    let reserved = COMPILER_KNOWN_PROFILE_EXPORTS
        .iter()
        .copied()
        .collect::<BTreeSet<_>>();
    let mut generated = Vec::new();
    for object in authority.profile.schema.objects.values() {
        let Some(name) = local_name(object.identity.as_str()) else {
            continue;
        };
        let candidate = match object.kind {
            SchemaObjectKind::Enum => Some(GeneratedSchemaType::Enum {
                name: name.to_string(),
                variants: identifier_list_property(object, "variants")?,
            }),
            SchemaObjectKind::Domain => Some(GeneratedSchemaType::Domain {
                name: name.to_string(),
                storage_type: type_property(object, "sifr_type")?.to_string(),
            }),
            SchemaObjectKind::Composite => Some(GeneratedSchemaType::Composite {
                name: name.to_string(),
                fields: type_map_property(object, "fields")?,
            }),
            _ => None,
        };
        if let Some(candidate) = candidate {
            if reserved.contains(candidate.name()) {
                continue;
            }
            if generated
                .iter()
                .any(|existing: &GeneratedSchemaType| existing.name() == candidate.name())
            {
                return Err(SchemaContractError::new(
                    SchemaContractErrorKind::ReservedExport,
                    format!("generated schema type '{}' is ambiguous", candidate.name()),
                ));
            }
            generated.push(candidate);
        }
    }
    generated.sort_by(|left, right| left.name().cmp(right.name()));
    Ok(generated)
}

fn type_property<'a>(
    object: &'a crate::SchemaObject,
    name: &str,
) -> Result<&'a str, SchemaContractError> {
    match object.semantic.get(name) {
        Some(SemanticValue::Text(value)) if valid_type_path(value) => Ok(value),
        _ => Err(invalid_generated_property(object, name)),
    }
}

fn identifier_list_property(
    object: &crate::SchemaObject,
    name: &str,
) -> Result<Vec<String>, SchemaContractError> {
    let Some(SemanticValue::List(values)) = object.semantic.get(name) else {
        return Err(invalid_generated_property(object, name));
    };
    let variants = values
        .iter()
        .map(|value| match value {
            SemanticValue::Text(value) if valid_identifier(value) => Ok(value.clone()),
            _ => Err(invalid_generated_property(object, name)),
        })
        .collect::<Result<Vec<_>, _>>()?;
    if variants.iter().collect::<BTreeSet<_>>().len() != variants.len() {
        return Err(invalid_generated_property(object, name));
    }
    Ok(variants)
}

fn type_map_property(
    object: &crate::SchemaObject,
    name: &str,
) -> Result<BTreeMap<String, String>, SchemaContractError> {
    let Some(SemanticValue::Map(values)) = object.semantic.get(name) else {
        return Err(invalid_generated_property(object, name));
    };
    values
        .iter()
        .map(|(key, value)| match value {
            SemanticValue::Text(value) if valid_identifier(key) && valid_type_path(value) => {
                Ok((key.clone(), value.clone()))
            }
            _ => Err(invalid_generated_property(object, name)),
        })
        .collect()
}

fn invalid_generated_property(object: &crate::SchemaObject, name: &str) -> SchemaContractError {
    SchemaContractError::new(
        SchemaContractErrorKind::InvalidSchema,
        format!(
            "schema object '{}' needs canonical '{name}' metadata for Sifr generation",
            object.identity
        ),
    )
}

fn local_name(identity: &str) -> Option<&str> {
    identity
        .rsplit('.')
        .next()
        .filter(|name| valid_identifier(name))
}

fn valid_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|first| first == '_' || first.is_alphabetic())
        && chars.all(|character| character == '_' || character.is_alphanumeric())
}

fn valid_type_path(value: &str) -> bool {
    !value.is_empty() && value.split('.').all(valid_identifier)
}

fn format_error(_: std::fmt::Error) -> SchemaContractError {
    SchemaContractError::new(
        SchemaContractErrorKind::Serialization,
        "cannot render generated profile module",
    )
}
