[package]
name = "sifr-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
sifr_syntax = { path = "../../crates/sifr_syntax" }
sifr_frontend = { path = "../../crates/sifr_frontend" }

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"
test = false
doc = false
bench = false

[workspace]

[[bin]]
name = "lowering"
path = "fuzz_targets/lowering.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ownership"
path = "fuzz_targets/ownership.rs"
test = false
doc = false
bench = false
