mod dependency_plan;
mod generated_stdlib_features;
mod runtime_features;
pub use dependency_plan::{
    sysroot_dependency_plan_with_sysroot, try_generated_cargo_dependencies,
    try_sysroot_dependency_plan, CargoVendorMode, SysrootCrate, SysrootCrateDependency,
    SysrootDependencyPlan,
};
pub use generated_stdlib_features::planned_sifr_stdlib_features;

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum StdlibFeature {
    Base64,
    BigDecimal,
    Blake2,
    Bytes,
    Chrono,
    Cookie,
    EncodingRs,
    Flate2,
    Fs,
    H2,
    Http,
    HttpBody,
    HttpBodyUtil,
    Hyper,
    HyperUtil,
    IcuCollator,
    IcuDatetime,
    IcuDecimal,
    IcuLocale,
    IcuPlurals,
    Ipc,
    Md5,
    Metrics,
    NumBigint,
    NumTraits,
    PercentEncoding,
    PythonRuntime,
    Rand,
    RandDistr,
    Rayon,
    Regex,
    Rustls,
    RustlsPemfile,
    RustlsPlatformVerifier,
    RustDecimal,
    SerdeJson,
    Sha1,
    Sha2,
    SifrRuntime,
    Sys,
    Tokio,
    TokioRustls,
    Toml,
    TowerService,
    Tracing,
    UnicodeNames,
    UnicodeNormalization,
    UnicodeSegmentation,
    Url,
    Uuid,
    Zip,
}

impl StdlibFeature {
    #[must_use]
    pub const fn id(self) -> &'static str {
        match self {
            Self::Base64 => "base64",
            Self::BigDecimal => "bigdecimal",
            Self::Blake2 => "blake2",
            Self::Bytes => "bytes",
            Self::Chrono => "chrono",
            Self::Cookie => "cookie",
            Self::EncodingRs => "encoding_rs",
            Self::Flate2 => "flate2",
            Self::Fs => "fs",
            Self::H2 => "h2",
            Self::Http => "http",
            Self::HttpBody => "http-body",
            Self::HttpBodyUtil => "http-body-util",
            Self::Hyper => "hyper",
            Self::HyperUtil => "hyper-util",
            Self::IcuCollator => "icu_collator",
            Self::IcuDatetime => "icu_datetime",
            Self::IcuDecimal => "icu_decimal",
            Self::IcuLocale => "icu_locale",
            Self::IcuPlurals => "icu_plurals",
            Self::Ipc => "ipc",
            Self::Md5 => "md5",
            Self::Metrics => "metrics",
            Self::NumBigint => "num-bigint",
            Self::NumTraits => "num-traits",
            Self::PercentEncoding => "percent-encoding",
            Self::PythonRuntime => "sifr_runtime/python",
            Self::Rand => "rand",
            Self::RandDistr => "rand_distr",
            Self::Rayon => "rayon",
            Self::Regex => "regex",
            Self::Rustls => "rustls",
            Self::RustlsPemfile => "rustls-pemfile",
            Self::RustlsPlatformVerifier => "rustls-platform-verifier",
            Self::RustDecimal => "rust_decimal",
            Self::SerdeJson => "serde_json",
            Self::Sha1 => "sha1",
            Self::Sha2 => "sha2",
            Self::SifrRuntime => "sifr_runtime",
            Self::Sys => "sys",
            Self::Tokio => "tokio",
            Self::TokioRustls => "tokio-rustls",
            Self::Toml => "toml",
            Self::TowerService => "tower-service",
            Self::Tracing => "tracing",
            Self::UnicodeNames => "unicode_names2",
            Self::UnicodeNormalization => "unicode-normalization",
            Self::UnicodeSegmentation => "unicode-segmentation",
            Self::Url => "url",
            Self::Uuid => "uuid",
            Self::Zip => "zip",
        }
    }
}

#[must_use]
pub fn feature_for_codegen_requirement(name: &str) -> Option<StdlibFeature> {
    match name {
        "base64" => Some(StdlibFeature::Base64),
        "bigdecimal" => Some(StdlibFeature::BigDecimal),
        "blake2" => Some(StdlibFeature::Blake2),
        "bytes" => Some(StdlibFeature::Bytes),
        "chrono" => Some(StdlibFeature::Chrono),
        "cookie" => Some(StdlibFeature::Cookie),
        "encoding_rs" | "encoding-rs" => Some(StdlibFeature::EncodingRs),
        "flate2" => Some(StdlibFeature::Flate2),
        "fs" => Some(StdlibFeature::Fs),
        "h2" => Some(StdlibFeature::H2),
        "http" => Some(StdlibFeature::Http),
        "http-body" | "http_body" => Some(StdlibFeature::HttpBody),
        "http-body-util" | "http_body_util" => Some(StdlibFeature::HttpBodyUtil),
        "hyper" => Some(StdlibFeature::Hyper),
        "hyper-util" | "hyper_util" => Some(StdlibFeature::HyperUtil),
        "icu_collator" | "icu-collator" => Some(StdlibFeature::IcuCollator),
        "icu_datetime" | "icu-datetime" => Some(StdlibFeature::IcuDatetime),
        "icu_decimal" | "icu-decimal" => Some(StdlibFeature::IcuDecimal),
        "icu_locale" | "icu-locale" => Some(StdlibFeature::IcuLocale),
        "icu_plurals" | "icu-plurals" => Some(StdlibFeature::IcuPlurals),
        "ipc" | "postcard" => Some(StdlibFeature::Ipc),
        "md5" => Some(StdlibFeature::Md5),
        "metrics" => Some(StdlibFeature::Metrics),
        "num-bigint" => Some(StdlibFeature::NumBigint),
        "num-traits" => Some(StdlibFeature::NumTraits),
        "percent-encoding" | "percent_encoding" => Some(StdlibFeature::PercentEncoding),
        "sifr_runtime/python" | "sifr-runtime/python" | "python-runtime" => {
            Some(StdlibFeature::PythonRuntime)
        }
        "rand" => Some(StdlibFeature::Rand),
        "rand_distr" => Some(StdlibFeature::RandDistr),
        "rayon" => Some(StdlibFeature::Rayon),
        "regex" => Some(StdlibFeature::Regex),
        "rustls" => Some(StdlibFeature::Rustls),
        "rustls-pemfile" | "rustls_pemfile" => Some(StdlibFeature::RustlsPemfile),
        "rustls-platform-verifier" | "rustls_platform_verifier" => {
            Some(StdlibFeature::RustlsPlatformVerifier)
        }
        "rust_decimal" => Some(StdlibFeature::RustDecimal),
        "serde_json" => Some(StdlibFeature::SerdeJson),
        "sha1" => Some(StdlibFeature::Sha1),
        "sha2" => Some(StdlibFeature::Sha2),
        "sifr_runtime" | "sifr-runtime" => Some(StdlibFeature::SifrRuntime),
        "sys" => Some(StdlibFeature::Sys),
        "tokio" => Some(StdlibFeature::Tokio),
        "tokio-rustls" | "tokio_rustls" => Some(StdlibFeature::TokioRustls),
        "toml" => Some(StdlibFeature::Toml),
        "tower-service" | "tower_service" => Some(StdlibFeature::TowerService),
        "tracing" => Some(StdlibFeature::Tracing),
        "unicode_names2" => Some(StdlibFeature::UnicodeNames),
        "unicode-normalization" | "unicode_normalization" => {
            Some(StdlibFeature::UnicodeNormalization)
        }
        "unicode-segmentation" | "unicode_segmentation" => Some(StdlibFeature::UnicodeSegmentation),
        "url" => Some(StdlibFeature::Url),
        "uuid" => Some(StdlibFeature::Uuid),
        "zip" => Some(StdlibFeature::Zip),
        _ => None,
    }
}

#[must_use]
pub fn features_for_stdlib_module(module_name: &str) -> &'static [StdlibFeature] {
    match module_name {
        "sifr.collections" | "_sifr.collections" => &[],
        "_sifr.fs" => &[StdlibFeature::Fs],
        "sifr.env" | "sifr.sys" | "_sifr.sys" => &[StdlibFeature::Sys],
        "sifr.time" | "_sifr.time" => &[],
        "sifr.random" | "_sifr.crypto" => &[],
        "sifr.uuid" | "_sifr.uuid" => &[],
        "sifr.re" | "_sifr.regex" => &[],
        "sifr.os" | "sifr.shutil" => &[StdlibFeature::Fs, StdlibFeature::Sys],
        "sifr.pathlib" => &[StdlibFeature::Fs],
        "sifr.hash" | "sifr.hashlib" => &[],
        "sifr.bytes" | "_sifr.bytes" => &[],
        "sifr.encoding" | "_sifr.encoding" => &[],
        "sifr.unicode" | "_sifr.unicode" => &[],
        "sifr.i18n" | "_sifr.i18n" => &[],
        "sifr.base64" => &[],
        "sifr.ipc" | "_sifr.ipc" => &[StdlibFeature::Ipc],
        "sifr.net" | "_sifr.net" => &[
            StdlibFeature::SifrRuntime,
            StdlibFeature::Tokio,
            StdlibFeature::Tracing,
        ],
        "sifr.tls" | "_sifr.tls" => &[
            StdlibFeature::SifrRuntime,
            StdlibFeature::Tokio,
            StdlibFeature::TokioRustls,
            StdlibFeature::Rustls,
            StdlibFeature::RustlsPemfile,
            StdlibFeature::RustlsPlatformVerifier,
            StdlibFeature::Tracing,
        ],
        "sifr.url" | "_sifr.url" => &[],
        "sifr.http" | "_sifr.http" => &[StdlibFeature::Http],
        "sifr.python" | "sifr.python_core" | "_sifr.python" => &[StdlibFeature::PythonRuntime],
        "sifr.parallel" => &[StdlibFeature::Rayon],
        "sifr.runtime" | "_sifr.runtime" => &[StdlibFeature::Metrics, StdlibFeature::Tracing],
        "sifr.tomllib" | "_sifr.toml" => &[StdlibFeature::Toml],
        "sifr.datetime" | "_sifr.datetime" => &[],
        "sifr.gzip" | "sifr.zipfile" | "_sifr.compress" => &[],
        "_bigint" => &[StdlibFeature::NumBigint, StdlibFeature::NumTraits],
        _ => &[],
    }
}
