[package]
name = "sifr_runtime"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
encoding_rs = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
unicode-normalization = { workspace = true, optional = true }
unicode-segmentation = { workspace = true, optional = true }
unicode_names2 = { workspace = true, optional = true }

[features]
default = []
unicode = ["dep:unicode-normalization", "dep:unicode-segmentation", "dep:unicode_names2"]

[lints]
workspace = true
