#![allow(clippy::expect_used)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

static NEXT_FIXTURE_ID: AtomicU64 = AtomicU64::new(0);

struct TestPackage {
    root: PathBuf,
}

impl TestPackage {
    fn library() -> Self {
        let package = Self::new("library", "sifr-python-readonly-library", "readonly_lib");
        std::fs::write(
            package.root.join("src/__init__.sifr"),
            "from sifr.python import PythonError\n\n\n@python(math.sqrt)\ndef sqrt(value: float) -> Result[float, PythonError]: ...\n",
        )
        .expect("library source should be written");
        package
    }

    #[cfg(unix)]
    fn application() -> Option<Self> {
        if Command::new("uv").arg("--version").output().is_err() {
            eprintln!("skipping Python application fixture: uv is unavailable");
            return None;
        }
        let package = Self::new("application", "sifr-python-readonly-app", "readonly_app");
        std::fs::write(
            package.root.join("src/main.sifr"),
            "from sifr.python import PythonError\n\n\n@python(math.sqrt)\ndef sqrt(value: float) -> Result[float, PythonError]: ...\n\n\ndef main():\n    pass\n",
        )
        .expect("application source should be written");
        std::fs::create_dir(package.root.join("src/bin"))
            .expect("secondary application directory should be written");
        std::fs::write(
            package.root.join("src/bin/secondary.sifr"),
            "from sifr.python import PythonError\n\n\n@python(math.ceil)\ndef ceil(value: float) -> Result[int, PythonError]: ...\n\n\ndef main():\n    pass\n",
        )
        .expect("secondary application source should be written");
        std::fs::write(
            package.root.join("pyproject.toml"),
            "[project]\nname = \"sifr-python-readonly-app\"\nversion = \"0.1.0\"\nrequires-python = \">=3.11\"\ndependencies = []\n",
        )
        .expect("pyproject should be written");
        let status = Command::new("uv")
            .args(["lock", "--offline", "--project"])
            .arg(&package.root)
            .status()
            .expect("uv lock should run");
        assert!(status.success(), "uv lock fixture should succeed");
        let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let shared_venv = repository.join("verification/.venv");
        if !shared_venv.join("bin/python").is_file() {
            eprintln!("skipping Python application fixture: verification/.venv is unavailable");
            return None;
        }
        std::os::unix::fs::symlink(&shared_venv, package.root.join(".venv"))
            .expect("shared verification venv should link");
        std::fs::write(
            package.root.join("sifr.toml"),
            manifest("readonly_app", "\n[python]\nvenv = \".venv\"\npyproject = \"pyproject.toml\"\nlock = \"uv.lock\"\n\n[trust]\npython = [\"math\"]\n"),
        )
        .expect("application manifest should be updated");
        Some(package)
    }

    fn new(label: &str, cargo_name: &str, sifr_name: &str) -> Self {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock should move forward")
            .as_nanos();
        let fixture_id = NEXT_FIXTURE_ID.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!(
            "sifr-python-readonly-{label}-{}-{nonce}-{fixture_id}",
            std::process::id()
        ));
        std::fs::create_dir(&root).expect("unique fixture root should be created");
        std::fs::create_dir(root.join("src")).expect("source directory should exist");
        std::fs::write(root.join("src/lib.rs"), "").expect("pure marker should be written");
        std::fs::write(
            root.join("Cargo.toml"),
            format!(
                "[package]\nname = \"{cargo_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[package.metadata.sifr]\nmanifest = \"sifr.toml\"\n\n[workspace]\n"
            ),
        )
        .expect("Cargo manifest should be written");
        std::fs::write(
            root.join("Cargo.lock"),
            format!(
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"{cargo_name}\"\nversion = \"0.1.0\"\n"
            ),
        )
        .expect("Cargo lock should be written");
        std::fs::write(root.join("sifr.toml"), manifest(sifr_name, ""))
            .expect("Sifr manifest should be written");
        Self { root }
    }
}

impl Drop for TestPackage {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.root);
    }
}

#[test]
fn library_check_and_doctor_are_deferred_deterministic_and_non_mutating() {
    let package = TestPackage::library();
    let before = snapshot(&package.root);

    let check = run(&package.root, &["python", "check", "--json"]);
    let normal_check = run(&package.root, &["check", "src/__init__.sifr", "--frozen"]);
    assert!(check.status.success(), "stderr: {}", stderr(&check));
    assert!(
        normal_check.status.success(),
        "normal library check must share deferral: {}",
        stderr(&normal_check)
    );
    let report: serde_json::Value = serde_json::from_slice(&check.stdout).expect("valid JSON");
    assert_eq!(report["application"], false);
    assert_eq!(report["environment"]["status"], "deferred");
    assert_eq!(report["trust"], "deferred-to-final-application");
    assert_eq!(report["required_imports"], serde_json::json!(["math"]));
    assert_eq!(report["targets"][0]["target"], "math.sqrt");
    assert_eq!(report["targets"][0]["status"], "deferred");

    let first = run(&package.root, &["python", "doctor", "--json"]);
    let second = run(&package.root, &["python", "doctor", "--json"]);
    assert!(first.status.success(), "stderr: {}", stderr(&first));
    assert_eq!(
        first.stdout, second.stdout,
        "doctor output must be deterministic"
    );
    let doctor: serde_json::Value = serde_json::from_slice(&first.stdout).expect("valid JSON");
    assert_eq!(
        doctor["suggestions"][0]["file"],
        "final-application/sifr.toml"
    );
    assert_eq!(
        doctor["suggestions"][0]["patch"],
        "@@ [python]\n+venv = \".venv\"\n+pyproject = \"pyproject.toml\"\n+lock = \"uv.lock\"\n@@ [trust]\n+python = [\"math\"]"
    );
    assert_eq!(
        snapshot(&package.root),
        before,
        "commands must not mutate the package"
    );
}

#[cfg(unix)]
#[test]
fn final_application_python_check_matches_normal_check_and_resolves_targets() {
    let Some(package) = TestPackage::application() else {
        return;
    };
    let before = snapshot(&package.root);
    let python_check = run(&package.root, &["python", "check", "--json"]);
    let normal_check = run(&package.root, &["check", "src/main.sifr", "--frozen"]);
    assert!(
        python_check.status.success(),
        "stderr: {}",
        stderr(&python_check)
    );
    assert!(
        normal_check.status.success(),
        "stderr: {}",
        stderr(&normal_check)
    );
    let report: serde_json::Value =
        serde_json::from_slice(&python_check.stdout).expect("valid JSON");
    assert_eq!(report["application"], true);
    assert_eq!(report["environment"]["status"], "resolved");
    assert_eq!(report["trust"], "verified");
    assert_eq!(
        report["targets"],
        serde_json::json!([
            {"target": "math.ceil", "status": "verified"},
            {"target": "math.sqrt", "status": "verified"}
        ])
    );
    assert_eq!(
        snapshot(&package.root),
        before,
        "checks must not mutate the package"
    );

    std::fs::write(
        package.root.join("src/main.sifr"),
        "from sifr.python import PythonError\n\n\n@python(math.not_a_real_target)\ndef missing(value: float) -> Result[float, PythonError]: ...\n\n\ndef main():\n    pass\n",
    )
    .expect("invalid target fixture should be written");
    let invalid_before = snapshot(&package.root);
    let python_failure = run(&package.root, &["python", "check"]);
    let normal_failure = run(&package.root, &["check", "src/main.sifr", "--frozen"]);
    assert_eq!(python_failure.status.code(), Some(1));
    assert_eq!(normal_failure.status.code(), Some(1));
    assert!(stderr(&python_failure).contains("SIFR-PYIMP-0001"));
    assert!(stderr(&normal_failure).contains("SIFR-PYIMP-0001"));
    assert_eq!(snapshot(&package.root), invalid_before);
}

#[cfg(unix)]
#[test]
fn library_with_root_environment_selection_resolves_and_matches_normal_check() {
    let Some(package) = TestPackage::application() else {
        return;
    };
    std::fs::remove_file(package.root.join("src/main.sifr"))
        .expect("application entrypoint should be removed");
    std::fs::remove_dir_all(package.root.join("src/bin"))
        .expect("secondary application entrypoint should be removed");
    std::fs::write(
        package.root.join("src/__init__.sifr"),
        "from sifr.python import PythonError\n\n\n@python(math.sqrt)\ndef sqrt(value: float) -> Result[float, PythonError]: ...\n",
    )
    .expect("library source should be written");

    let resolved_before = snapshot(&package.root);
    let resolved = run(&package.root, &["python", "check", "--json"]);
    assert!(resolved.status.success(), "stderr: {}", stderr(&resolved));
    let report: serde_json::Value =
        serde_json::from_slice(&resolved.stdout).expect("valid resolved JSON");
    assert_eq!(report["application"], false);
    assert_eq!(report["environment"]["status"], "resolved");
    assert_eq!(report["trust"], "verified");
    assert_eq!(report["targets"][0]["status"], "verified");
    assert_eq!(snapshot(&package.root), resolved_before);

    std::fs::write(
        package.root.join("src/__init__.sifr"),
        "from sifr.python import PythonError\n\n\n@python(math.not_a_real_target)\ndef missing(value: float) -> Result[float, PythonError]: ...\n",
    )
    .expect("invalid library target should be written");
    let invalid_before = snapshot(&package.root);
    let python_failure = run(&package.root, &["python", "check"]);
    let normal_failure = run(&package.root, &["check", "src/__init__.sifr", "--frozen"]);
    assert_eq!(python_failure.status.code(), Some(1));
    assert_eq!(normal_failure.status.code(), Some(1));
    assert!(stderr(&python_failure).contains("SIFR-PYIMP-0001"));
    assert!(stderr(&normal_failure).contains("SIFR-PYIMP-0001"));
    assert_eq!(snapshot(&package.root), invalid_before);
}

#[cfg(unix)]
#[test]
fn library_with_discovered_environment_resolves_and_matches_normal_check() {
    let Some(package) = TestPackage::application() else {
        return;
    };
    std::fs::remove_file(package.root.join("src/main.sifr"))
        .expect("application entrypoint should be removed");
    std::fs::remove_dir_all(package.root.join("src/bin"))
        .expect("secondary application entrypoint should be removed");
    let source = package.root.join("src/__init__.sifr");
    std::fs::write(
        &source,
        "from sifr.python import PythonError\n\n\n@python(math.sqrt)\ndef sqrt(value: float) -> Result[float, PythonError]: ...\n",
    )
    .expect("library source should be written");
    std::fs::write(
        package.root.join("sifr.toml"),
        manifest("readonly_app", "\n[trust]\npython = [\"math\"]\n"),
    )
    .expect("discovery-based library manifest should be written");

    let resolved_before = snapshot(&package.root);
    let resolved = run(&package.root, &["python", "check", "--json"]);
    let normal = run(&package.root, &["check", "src/__init__.sifr", "--frozen"]);
    assert!(resolved.status.success(), "stderr: {}", stderr(&resolved));
    assert!(normal.status.success(), "stderr: {}", stderr(&normal));
    let report: serde_json::Value =
        serde_json::from_slice(&resolved.stdout).expect("valid discovered JSON");
    assert_eq!(report["application"], false);
    assert_eq!(report["environment"]["status"], "resolved");
    assert_eq!(report["trust"], "verified");
    assert_eq!(report["targets"][0]["status"], "verified");
    assert_eq!(snapshot(&package.root), resolved_before);

    std::fs::write(package.root.join("sifr.toml"), manifest("readonly_app", ""))
        .expect("untrusted discovery-based library manifest should be written");
    let deferred_before = snapshot(&package.root);
    let deferred = run(&package.root, &["python", "check", "--json"]);
    let normal_deferred = run(&package.root, &["check", "src/__init__.sifr", "--frozen"]);
    let doctor = run(&package.root, &["python", "doctor", "--json"]);
    assert!(deferred.status.success(), "stderr: {}", stderr(&deferred));
    assert!(
        normal_deferred.status.success(),
        "stderr: {}",
        stderr(&normal_deferred)
    );
    assert!(doctor.status.success(), "stderr: {}", stderr(&doctor));
    let report: serde_json::Value =
        serde_json::from_slice(&deferred.stdout).expect("valid deferred JSON");
    assert_eq!(report["environment"]["status"], "deferred");
    assert_eq!(report["trust"], "deferred-to-final-application");
    let doctor: serde_json::Value =
        serde_json::from_slice(&doctor.stdout).expect("valid doctor JSON");
    assert_eq!(doctor["suggestions"].as_array().map(Vec::len), Some(1));
    assert_eq!(
        doctor["suggestions"][0]["patch"],
        "@@ [trust]\n+python = [\"math\"]"
    );
    assert_eq!(snapshot(&package.root), deferred_before);

    std::fs::write(
        package.root.join("sifr.toml"),
        manifest("readonly_app", "\n[trust]\npython = [\"math\"]\n"),
    )
    .expect("trusted discovery-based library manifest should be restored");

    std::fs::write(
        source,
        "from sifr.python import PythonError\n\n\n@python(math.not_a_real_target)\ndef missing(value: float) -> Result[float, PythonError]: ...\n",
    )
    .expect("invalid discovered target should be written");
    let invalid_before = snapshot(&package.root);
    let python_failure = run(&package.root, &["python", "check"]);
    let normal_failure = run(&package.root, &["check", "src/__init__.sifr", "--frozen"]);
    assert_eq!(python_failure.status.code(), Some(1));
    assert_eq!(normal_failure.status.code(), Some(1));
    assert!(stderr(&python_failure).contains("SIFR-PYIMP-0001"));
    assert!(stderr(&normal_failure).contains("SIFR-PYIMP-0001"));
    assert_eq!(snapshot(&package.root), invalid_before);
}

#[test]
fn trusted_library_without_environment_defers_only_environment_selection() {
    let package = TestPackage::library();
    std::fs::write(
        package.root.join("sifr.toml"),
        manifest("readonly_lib", "\n[trust]\npython = [\"math\"]\n"),
    )
    .expect("trusted library manifest should be written");
    let before = snapshot(&package.root);

    let check = run(&package.root, &["python", "check", "--json"]);
    let normal = run(&package.root, &["check", "src/__init__.sifr", "--frozen"]);
    let doctor = run(&package.root, &["python", "doctor", "--json"]);
    assert!(check.status.success(), "stderr: {}", stderr(&check));
    assert!(normal.status.success(), "stderr: {}", stderr(&normal));
    assert!(doctor.status.success(), "stderr: {}", stderr(&doctor));
    let report: serde_json::Value = serde_json::from_slice(&check.stdout).expect("valid JSON");
    assert_eq!(report["environment"]["status"], "deferred");
    assert_eq!(report["trust"], "verified");
    let doctor: serde_json::Value = serde_json::from_slice(&doctor.stdout).expect("doctor JSON");
    assert_eq!(
        doctor["suggestions"][0]["patch"],
        "@@ [python]\n+venv = \".venv\"\n+pyproject = \"pyproject.toml\"\n+lock = \"uv.lock\""
    );
    assert_eq!(snapshot(&package.root), before);
}

#[test]
fn python_check_requires_a_package_without_creating_files() {
    let package = TestPackage::new("empty", "sifr-python-readonly-empty", "readonly_empty");
    std::fs::remove_file(package.root.join("sifr.toml")).expect("remove package marker");
    let before = snapshot(&package.root);
    let output = run(&package.root, &["python", "check"]);
    assert_eq!(output.status.code(), Some(2));
    assert!(stderr(&output).contains("require a Sifr package"));
    assert_eq!(snapshot(&package.root), before);
}

fn manifest(name: &str, suffix: &str) -> String {
    format!(
        "[package]\nname = \"{name}\"\nedition = \"2026\"\nsifr-version = \">=0.3,<0.4\"\n\n[source]\nroot = \"src\"\n{suffix}"
    )
}

fn run(cwd: &Path, args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_sifr"))
        .args(args)
        .current_dir(cwd)
        .output()
        .expect("sifr command should run")
}

fn stderr(output: &std::process::Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

fn snapshot(root: &Path) -> BTreeMap<String, Vec<u8>> {
    let mut files = BTreeMap::new();
    collect_snapshot(root, root, &mut files);
    files
}

fn collect_snapshot(root: &Path, current: &Path, files: &mut BTreeMap<String, Vec<u8>>) {
    let mut entries = std::fs::read_dir(current)
        .expect("snapshot directory should be readable")
        .map(|entry| entry.expect("snapshot entry should be readable"))
        .collect::<Vec<_>>();
    entries.sort_by_key(std::fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        let metadata = std::fs::symlink_metadata(&path).expect("snapshot metadata should exist");
        if metadata.file_type().is_symlink() {
            files.insert(
                path.strip_prefix(root)
                    .expect("snapshot path should be relative")
                    .display()
                    .to_string(),
                std::fs::read_link(&path)
                    .expect("symlink target should be readable")
                    .as_os_str()
                    .as_encoded_bytes()
                    .to_vec(),
            );
        } else if metadata.is_dir() {
            collect_snapshot(root, &path, files);
        } else {
            files.insert(
                path.strip_prefix(root)
                    .expect("snapshot path should be relative")
                    .display()
                    .to_string(),
                std::fs::read(&path).expect("snapshot file should be readable"),
            );
        }
    }
}
