[package]
name = "sifr_package"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
sifr_diagnostics = { workspace = true }
sifr_frontend = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
