[package]
name = "sifr_package"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
sifr_compiler_component = { workspace = true }
sifr_diagnostics = { workspace = true }
sifr_frontend = { workspace = true }
sifr_sql_contract = { workspace = true }
sifr_python_ast = { workspace = true }
sifr_syntax = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
semver = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
