[package]
name = "sifr_lint"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
globset = { workspace = true }
ignore = { workspace = true }
sifr_diagnostics = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
