[package]
name = "sifr_sql_postgresql_runtime"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
bytes = { workspace = true }
futures-core = { workspace = true }
postgres-types = { workspace = true, features = ["derive"] }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
sifr_runtime = { workspace = true }
sifr_sql_runtime = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
tokio-postgres = { workspace = true, features = ["runtime"] }
tokio-postgres-rustls = { workspace = true, features = ["aws-lc-rs"] }

[dev-dependencies]
sha2 = { workspace = true }
static_assertions = { workspace = true }

[lints]
workspace = true
