"""Canonical Rust-interop fixture, crate, diagnostic, and tier inventories."""

REQUIRED_FIXTURES = {
    "advanced_data_matrix",
    "advanced_data_runtime_matrix",
    "arrow_record_batch",
    "async_ecosystem_matrix",
    "async_runtime_core",
    "async_runtime_reqwest",
    "blocking_diagnostics",
    "bridge_type_matrix",
    "bridge_version_field_removal",
    "callback_subscription_core",
    "callback_subscription_ecosystem",
    "callbacks_call_scoped",
    "callbacks_threadsafe",
    "cargo_locked_offline",
    "close_after_use",
    "direct_crate_crc32",
    "direct_crate_matrix",
    "direct_crate_negative_type",
    "dotted_path_resolution",
    "ecosystem_backend_certification",
    "ecosystem_cli_certification",
    "local_bridge_blake3",
    "native_build_script",
    "opaque_handle_tokenizer",
    "opaque_resource_core",
    "opaque_resource_package_core",
    "opaque_resource_matrix",
    "panic_abort_profile",
    "panic_boundary",
    "panic_boundary_wrapper_emission",
    "proc_macro_trust",
    "same_workspace_crate",
    "shared_bridge_crate",
    "structural_bridge_calls",
    "tensor_dlpack_bridge",
    "zero_copy_bytes",
    "zero_copy_runtime_matrix",
    "zero_copy_view_matrix",
}

REQUIRED_DIAGNOSTICS = {
    "SIFR-RUST-ASYNC-0001",
    "SIFR-RUST-CARGO-0001",
    "SIFR-RUST-CB-0001",
    "SIFR-RUST-CONFIG-0001",
    "SIFR-RUST-HANDLE-0001",
    "SIFR-RUST-PANIC-0001",
    "SIFR-RUST-RESOLVE-0001",
    "SIFR-RUST-TRUST-0001",
    "SIFR-RUST-TYPE-0001",
    "SIFR-RUST-ZC-0001",
}

REQUIRED_CRATES = {
    "anyhow",
    "arrow",
    "axum",
    "bindgen",
    "blake3",
    "bytemuck",
    "bytes",
    "candle",
    "cc",
    "clap",
    "crc32fast",
    "cxx",
    "datafusion",
    "flate2",
    "futures",
    "http",
    "http-body",
    "indexmap",
    "memmap2",
    "ndarray",
    "notify",
    "polars",
    "prost-build",
    "rayon",
    "redis",
    "regex",
    "reqwest",
    "rusqlite",
    "serde",
    "serde_derive",
    "serde_json",
    "sha2",
    "sqlx",
    "thiserror",
    "tokio",
    "tokio-postgres",
    "tokio-tungstenite",
    "tower",
    "tower-http",
    "tracing",
    "tracing-subscriber",
    "uuid",
    "zerocopy",
    "zstd",
}

VALID_EVIDENCE_STATUS = {
    "planned",
    "probe-only",
    "runtime-observed",
    "passing",
    "failing",
}
EXECUTION_KINDS = {
    "compiler-diagnostic",
    "contract-only",
    "cargo-probe",
    "runtime-observed",
}
ALLOWED_EXECUTION_KINDS = {
    0: {"compiler-diagnostic"},
    1: {"cargo-probe"},
    2: {"contract-only", "cargo-probe", "runtime-observed"},
    3: {"cargo-probe"},
    4: {"contract-only", "cargo-probe", "runtime-observed"},
}

EXPECTED_FEATURE_POLICIES = {
    "candle": {"backend": "cpu-only", "default_features": False},
    "flate2": {"default_features": False, "features": ["rust_backend"]},
    "prost-build": {"generated_output": "deterministic"},
    "redis": {"default_features": False, "features": ["tokio-comp"]},
    "reqwest": {"default_features": False, "features": ["rustls-tls", "json"]},
    "rusqlite": {"features": ["bundled"]},
    "sqlx": {
        "default_features": False,
        "features": ["runtime-tokio-rustls", "postgres", "macros"],
    },
    "tokio-postgres": {"default_features": False, "features": ["runtime"]},
    "tokio-tungstenite": {"default_features": False},
    "tracing-subscriber": {"features": ["env-filter"]},
    "zerocopy": {"features": ["derive"]},
}
