[package]
name = "sifr_diagnostics"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
ruff_text_size = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
static_assertions = { workspace = true }

[lints]
workspace = true
