[workspace]
members = ["rust/anyhow", "rust/clap", "rust/tracing", "rust/tracing_subscriber"]
resolver = "2"

[package]
name = "cli-feature-package"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { path = "rust/anyhow" }
clap = { path = "rust/clap" }
tracing = { path = "rust/tracing" }
tracing-subscriber = { path = "rust/tracing_subscriber", features = ["env-filter"] }

[package.metadata.sifr]
manifest = "sifr.toml"
