#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/distribution/generate_dispatchers.sh --install-root <dir> [options]

Generate the public Sifr installer bootstrap scripts.

The generated scripts do not embed channel versions or download installers from
the website. They resolve moving channels from the GitHub channels release
asset and download immutable installers from GitHub version releases.

Options:
  --install-root <dir>                 Destination install root directory, usually apps/sifr-site/public/install
  --channel-metadata-url <url>         Channel metadata URL (default: GitHub channels release asset)
  --installer-release-base-url <url>   Version release base URL (default: GitHub releases download base)
  --default-channel <channel>          /install default (default: stable)
  --help                               Show this help
EOF
}

INSTALL_ROOT=""
CHANNEL_METADATA_URL="https://github.com/sifr-lang/sifr/releases/download/channels/channels.json"
INSTALLER_RELEASE_BASE_URL="https://github.com/sifr-lang/sifr/releases/download"
DEFAULT_CHANNEL="stable"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-root)
      INSTALL_ROOT="${2:-}"
      shift 2
      ;;
    --channel-metadata-url)
      CHANNEL_METADATA_URL="${2:-}"
      shift 2
      ;;
    --installer-release-base-url)
      INSTALLER_RELEASE_BASE_URL="${2:-}"
      shift 2
      ;;
    --default-channel)
      DEFAULT_CHANNEL="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${INSTALL_ROOT}" ]]; then
  echo "--install-root is required" >&2
  usage >&2
  exit 2
fi
case "${DEFAULT_CHANNEL}" in
  alpha|beta|stable) ;;
  *)
    echo "--default-channel must be alpha, beta, or stable" >&2
    exit 2
    ;;
esac

write_dispatcher() {
  local path="$1"
  local default_channel="$2"
  local entrypoint_name="$3"

  cat >"${path}" <<EOF
#!/usr/bin/env sh
# Generated by scripts/distribution/generate_dispatchers.sh. Do not hand-edit.
# Entrypoint: ${entrypoint_name}

set -eu

DEFAULT_CHANNEL="${default_channel}"
CHANNEL_METADATA_URL="${CHANNEL_METADATA_URL}"
INSTALLER_RELEASE_BASE_URL="${INSTALLER_RELEASE_BASE_URL}"

fail() {
  echo "sifr installer dispatcher: \$*" >&2
  exit 2
}

release_channel_for_version() {
  if echo "\$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+$'; then
    echo "alpha"
  elif echo "\$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$'; then
    echo "beta"
  elif echo "\$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "stable"
  else
    fail "version must be stable SemVer or a prerelease using -alpha.N or -beta.N: \$1"
  fi
}

normalize_channel() {
  case "\$1" in
    alpha|beta|stable)
      echo "\$1"
      ;;
    "")
      fail "channel must not be empty"
      ;;
    *)
      fail "unknown release channel: \$1"
      ;;
  esac
}

download() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "\$1" -o "\$2"
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O "\$2" "\$1"
  else
    fail "curl or wget is required to download Sifr"
  fi
}

channel_version_from_metadata() {
  channel="\$1"
  metadata_file="\$2"
  sed -n 's/.*"'\${channel}'"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' "\${metadata_file}" | head -n 1
}

release_installer_sha_from_metadata() {
  version="\$1"
  channel="\$2"
  metadata_file="\$3"
  sed -n 's/.*"'\${version}'":{"channel":"'\${channel}'","installer_sha256":"\\([0-9a-f]\\{64\\}\\)","source_commit":"[0-9a-f]\\{40\\}","status":"active","targets":{.*/\\1/p' \
    "\${metadata_file}" | head -n 1
}

validate_release_index() {
  metadata_file="\$1"
  requested_channel="\$2"
  [ "\$(wc -l <"\${metadata_file}" | tr -d '[:space:]')" = "1" ] ||
    fail "channel metadata must be canonical single-line schema-v2 JSON"
  grep -Eq '^\{"channels":\{.*\},"ga_status":"(preview|active)","generation":[1-9][0-9]*,"releases":\{.*\},"schema_version":2\}$' \
    "\${metadata_file}" ||
    fail "channel metadata must use the exact canonical schema-v2 shape"
  grep -Eq '"schema_version"[[:space:]]*:[[:space:]]*2([,}]|[[:space:]]*$)' "\${metadata_file}" ||
    fail "channel metadata schema_version must be integer 2"
  grep -Eq '"generation"[[:space:]]*:[[:space:]]*[1-9][0-9]*' "\${metadata_file}" ||
    fail "channel metadata generation must be positive"
  grep -Eq '"ga_status"[[:space:]]*:[[:space:]]*"(preview|active)"' "\${metadata_file}" ||
    fail "channel metadata ga_status must be preview or active"
  grep -Eq '"releases"[[:space:]]*:' "\${metadata_file}" ||
    fail "channel metadata releases are missing"
  if [ "\${requested_channel}" = "stable" ]; then
    grep -Eq '"ga_status"[[:space:]]*:[[:space:]]*"active"' "\${metadata_file}" ||
      fail "stable channel installs require active GA metadata"
  fi
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "\$1" | awk '{print \$1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "\$1" | awk '{print \$1}'
  else
    fail "sha256sum or shasum is required to verify the installer"
  fi
}

env_channel="\${SIFR_CHANNEL:-}"
arg_channel=""
version_pin=""
installer_args=""

while [ "\$#" -gt 0 ]; do
  case "\$1" in
    --channel)
      [ "\$#" -ge 2 ] || fail "--channel requires a value"
      arg_channel="\$2"
      shift 2
      ;;
    --channel=*)
      arg_channel="\${1#--channel=}"
      shift
      ;;
    --version)
      [ "\$#" -ge 2 ] || fail "--version requires a value"
      version_pin="\$2"
      shift 2
      ;;
    --version=*)
      version_pin="\${1#--version=}"
      shift
      ;;
    *)
      installer_args="\${installer_args}
\$1"
      shift
      ;;
  esac
done

if [ -n "\${env_channel}" ]; then
  env_channel="\$(normalize_channel "\${env_channel}")"
fi
if [ -n "\${arg_channel}" ]; then
  arg_channel="\$(normalize_channel "\${arg_channel}")"
fi
if [ -n "\${env_channel}" ] && [ -n "\${arg_channel}" ] && [ "\${env_channel}" != "\${arg_channel}" ]; then
  fail "SIFR_CHANNEL=\${env_channel} conflicts with --channel \${arg_channel}"
fi

explicit_channel="\${arg_channel:-\${env_channel}}"
tmp_dir="\$(mktemp -d "\${TMPDIR:-/tmp}/sifr-install-dispatch.XXXXXX")"
cleanup() {
  rm -rf "\${tmp_dir}"
}
trap cleanup EXIT HUP INT TERM

if [ -n "\${version_pin}" ]; then
  version_channel="\$(release_channel_for_version "\${version_pin}")"
  if [ -n "\${explicit_channel}" ] && [ "\${explicit_channel}" != "\${version_channel}" ]; then
    fail "--version \${version_pin} conflicts with selected channel \${explicit_channel}"
  fi
  resolved_channel="\${version_channel}"
else
  resolved_channel="\$(normalize_channel "\${explicit_channel:-\${DEFAULT_CHANNEL}}")"
fi
metadata_url="\${CHANNEL_METADATA_URL}"
metadata_path="\${tmp_dir}/channels.json"
if ! download "\${metadata_url}" "\${metadata_path}"; then
  fail "channel metadata unavailable: \${metadata_url}"
fi
validate_release_index "\${metadata_path}" "\${resolved_channel}"

if [ -n "\${version_pin}" ]; then
  resolved_version="\${version_pin}"
else
  resolved_version="\$(channel_version_from_metadata "\${resolved_channel}" "\${metadata_path}")"
  [ -n "\${resolved_version}" ] || fail "channel \${resolved_channel} missing from metadata"
  configured_version_channel="\$(release_channel_for_version "\${resolved_version}")"
  if [ "\${configured_version_channel}" != "\${resolved_channel}" ]; then
    fail "malformed channel metadata: \${resolved_channel} points at \${resolved_version}"
  fi
fi

expected_installer_sha="\$(release_installer_sha_from_metadata \
  "\${resolved_version}" "\${resolved_channel}" "\${metadata_path}")"
[ -n "\${expected_installer_sha}" ] ||
  fail "version \${resolved_version} is not an active governed release"
case "\${expected_installer_sha}" in
  0000000000000000000000000000000000000000000000000000000000000000)
    fail "version \${resolved_version} has an invalid zero installer digest"
    ;;
esac

release_base_url="\${INSTALLER_RELEASE_BASE_URL}"
installer_url="\${release_base_url%/}/\${resolved_version}/sifr-installer-\${resolved_version}"

if [ "\${SIFR_DISPATCH_TRACE:-0}" = "1" ]; then
  echo "sifr dispatcher channel=\${resolved_channel} version=\${resolved_version} url=\${installer_url}"
fi

installer_path="\${tmp_dir}/installer.sh"
if ! download "\${installer_url}" "\${installer_path}"; then
  fail "GitHub installer unavailable: \${installer_url}"
fi
actual_installer_sha="\$(sha256_file "\${installer_path}")"
[ "\${actual_installer_sha}" = "\${expected_installer_sha}" ] ||
  fail "installer SHA-256 mismatch for \${resolved_version}"

chmod +x "\${installer_path}"
set --
if [ -n "\${installer_args}" ]; then
  while IFS= read -r installer_arg; do
    [ -n "\${installer_arg}" ] || continue
    set -- "\$@" "\${installer_arg}"
  done <<EOFARGS
\${installer_args}
EOFARGS
fi
sh "\${installer_path}" "\$@"
EOF

  chmod 755 "${path}"
}

mkdir -p "${INSTALL_ROOT}"
rm -rf "${INSTALL_ROOT}/versions" "${INSTALL_ROOT}/metadata"

write_dispatcher "${INSTALL_ROOT}/index" "${DEFAULT_CHANNEL}" "index"
write_dispatcher "${INSTALL_ROOT}/stable" "stable" "stable"
write_dispatcher "${INSTALL_ROOT}/alpha" "alpha" "alpha"
write_dispatcher "${INSTALL_ROOT}/beta" "beta" "beta"

echo "generated GitHub-backed dispatchers under ${INSTALL_ROOT}"
