#!/usr/bin/env bash

set -euo pipefail

TARGETS=(
  "aarch64-apple-darwin"
  "x86_64-apple-darwin"
  "x86_64-unknown-linux-gnu"
  "aarch64-unknown-linux-gnu"
)

usage() {
  cat <<'EOF'
Usage: scripts/distribution/generate_version_installer.sh --version <preview> --artifact-dir <dir> --out <path> [options]

Generate an immutable Sifr version installer that embeds artifact names and SHA-256 checksums.

Options:
  --version <preview>          Semver prerelease version
  --artifact-dir <dir>         Directory containing sifr-<version>-<target>.tar.gz and .sha256 files
  --out <path>                 Output installer path
  --artifact-base-url <url>    Public artifact base URL (default: GitHub release URL for the version)
  --help                       Show this help
EOF
}

VERSION=""
ARTIFACT_DIR=""
OUT=""
ARTIFACT_BASE_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      VERSION="${2:-}"
      shift 2
      ;;
    --artifact-dir)
      ARTIFACT_DIR="${2:-}"
      shift 2
      ;;
    --out)
      OUT="${2:-}"
      shift 2
      ;;
    --artifact-base-url)
      ARTIFACT_BASE_URL="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${VERSION}" || -z "${ARTIFACT_DIR}" || -z "${OUT}" ]]; then
  echo "--version, --artifact-dir, and --out are required" >&2
  usage >&2
  exit 2
fi

if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc)\.[0-9]+$ ]]; then
  echo "version must be a semver prerelease using -alpha.N, -beta.N, or -rc.N: ${VERSION}" >&2
  exit 2
fi

if [[ -z "${ARTIFACT_BASE_URL}" ]]; then
  ARTIFACT_BASE_URL="https://github.com/sifr-lang/sifr/releases/download/${VERSION}"
fi

sha256_file() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${path}" | awk '{print $1}'
  else
    shasum -a 256 "${path}" | awk '{print $1}'
  fi
}

case_entries=""
for target in "${TARGETS[@]}"; do
  archive_name="sifr-${VERSION}-${target}.tar.gz"
  archive_path="${ARTIFACT_DIR}/${archive_name}"
  checksum_path="${archive_path}.sha256"
  if [[ ! -f "${archive_path}" ]]; then
    echo "artifact missing for target ${target}: ${archive_path}" >&2
    exit 2
  fi
  if [[ ! -f "${checksum_path}" ]]; then
    echo "checksum missing for target ${target}: ${checksum_path}" >&2
    exit 2
  fi
  expected="$(tr -d '[:space:]' <"${checksum_path}")"
  actual="$(sha256_file "${archive_path}")"
  if [[ "${expected}" != "${actual}" ]]; then
    echo "checksum mismatch for ${archive_name}: expected ${expected}, got ${actual}" >&2
    exit 2
  fi
  case_entries="${case_entries}
    ${target})
      archive_name=\"${archive_name}\"
      archive_sha256=\"${expected}\"
      ;;"
done

mkdir -p "$(dirname "${OUT}")"
cat >"${OUT}" <<EOF
#!/usr/bin/env sh
# Generated by scripts/distribution/generate_version_installer.sh. Do not hand-edit.

set -eu

APP_NAME="sifr"
APP_VERSION="${VERSION}"
ARTIFACT_BASE_URL="${ARTIFACT_BASE_URL}"

fail() {
  echo "sifr installer: \$*" >&2
  exit 2
}

download() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "\$1" -o "\$2"
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O "\$2" "\$1"
  else
    fail "curl or wget is required to download artifacts"
  fi
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "\$1" | awk '{print \$1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "\$1" | awk '{print \$1}'
  else
    fail "sha256sum or shasum is required to verify artifacts"
  fi
}

detect_target() {
  if [ -n "\${SIFR_TARGET:-}" ]; then
    echo "\${SIFR_TARGET}"
    return 0
  fi

  os="\$(uname -s)"
  arch="\$(uname -m)"
  case "\${os}:\${arch}" in
    Darwin:arm64|Darwin:aarch64)
      echo "aarch64-apple-darwin"
      ;;
    Darwin:x86_64)
      echo "x86_64-apple-darwin"
      ;;
    Linux:x86_64)
      echo "x86_64-unknown-linux-gnu"
      ;;
    Linux:aarch64|Linux:arm64)
      echo "aarch64-unknown-linux-gnu"
      ;;
    *)
      fail "unsupported platform: \${os}/\${arch}"
      ;;
  esac
}

target="\$(detect_target)"
archive_name=""
archive_sha256=""

case "\${target}" in${case_entries}
    *)
      fail "unsupported target: \${target}"
      ;;
esac

base_url="\${SIFR_ARTIFACT_BASE_URL:-\${ARTIFACT_BASE_URL}}"
artifact_url="\${base_url%/}/\${archive_name}"
install_dir="\${SIFR_INSTALL_DIR:-\${HOME}/.sifr/bin}"

if [ "\${SIFR_INSTALLER_TRACE:-0}" = "1" ]; then
  echo "sifr installer version=\${APP_VERSION} target=\${target} archive=\${archive_name}"
fi

tmp_dir="\$(mktemp -d "\${TMPDIR:-/tmp}/sifr-install.XXXXXX")"
cleanup() {
  rm -rf "\${tmp_dir}"
}
trap cleanup EXIT HUP INT TERM

archive_path="\${tmp_dir}/\${archive_name}"
extract_dir="\${tmp_dir}/extract"
mkdir -p "\${extract_dir}"

download "\${artifact_url}" "\${archive_path}"
actual_sha256="\$(sha256_file "\${archive_path}")"
if [ "\${actual_sha256}" != "\${archive_sha256}" ]; then
  fail "checksum mismatch for \${archive_name}: expected \${archive_sha256}, got \${actual_sha256}"
fi

tar -xzf "\${archive_path}" -C "\${extract_dir}"
if [ ! -f "\${extract_dir}/sifr" ]; then
  fail "artifact \${archive_name} does not contain sifr at archive root"
fi

mkdir -p "\${install_dir}"
tmp_binary="\${install_dir}/.sifr.\$\$.tmp"
cp "\${extract_dir}/sifr" "\${tmp_binary}"
chmod 755 "\${tmp_binary}"
mv "\${tmp_binary}" "\${install_dir}/sifr"

echo "installed sifr \${APP_VERSION} to \${install_dir}/sifr"
EOF

chmod 755 "${OUT}"
echo "generated version installer ${OUT}"
