#!/usr/bin/env bash

set -euo pipefail

TARGETS=(
  "aarch64-apple-darwin"
  "x86_64-apple-darwin"
  "x86_64-unknown-linux-gnu"
  "aarch64-unknown-linux-gnu"
)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  cat <<'EOF'
Usage: scripts/distribution/generate_version_installer.sh --version <preview> --artifact-dir <dir> --out <path> [options]

Generate an immutable Sifr version installer that embeds artifact names and SHA-256 checksums.

Options:
  --version <preview>          Semver prerelease version
  --artifact-dir <dir>         Directory containing sifr-<version>-<target>.tar.gz and .sha256 files
  --out <path>                 Output installer path
  --artifact-base-url <url>    Public artifact base URL (default: GitHub release URL for the version)
  --help                       Show this help
EOF
}

VERSION=""
ARTIFACT_DIR=""
OUT=""
ARTIFACT_BASE_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      VERSION="${2:-}"
      shift 2
      ;;
    --artifact-dir)
      ARTIFACT_DIR="${2:-}"
      shift 2
      ;;
    --out)
      OUT="${2:-}"
      shift 2
      ;;
    --artifact-base-url)
      ARTIFACT_BASE_URL="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${VERSION}" || -z "${ARTIFACT_DIR}" || -z "${OUT}" ]]; then
  echo "--version, --artifact-dir, and --out are required" >&2
  usage >&2
  exit 2
fi

if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc)\.[0-9]+$ ]]; then
  echo "version must be a semver prerelease using -alpha.N, -beta.N, or -rc.N: ${VERSION}" >&2
  exit 2
fi

if [[ -z "${ARTIFACT_BASE_URL}" ]]; then
  ARTIFACT_BASE_URL="https://github.com/sifr-lang/sifr/releases/download/${VERSION}"
fi

sha256_file() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${path}" | awk '{print $1}'
  else
    shasum -a 256 "${path}" | awk '{print $1}'
  fi
}

case_entries=""
for target in "${TARGETS[@]}"; do
  archive_name="sifr-${VERSION}-${target}.tar.gz"
  archive_path="${ARTIFACT_DIR}/${archive_name}"
  checksum_path="${archive_path}.sha256"
  if [[ ! -f "${archive_path}" ]]; then
    echo "artifact missing for target ${target}: ${archive_path}" >&2
    exit 2
  fi
  if [[ ! -f "${checksum_path}" ]]; then
    echo "checksum missing for target ${target}: ${checksum_path}" >&2
    exit 2
  fi
  expected="$(tr -d '[:space:]' <"${checksum_path}")"
  actual="$(sha256_file "${archive_path}")"
  if [[ "${expected}" != "${actual}" ]]; then
    echo "checksum mismatch for ${archive_name}: expected ${expected}, got ${actual}" >&2
    exit 2
  fi
  python3 "${SCRIPT_DIR}/verify_release_archive.py" \
    "${archive_path}" \
    --version "${VERSION}" \
    --target "${target}"
  case_entries="${case_entries}
    ${target})
      archive_name=\"${archive_name}\"
      archive_sha256=\"${expected}\"
      ;;"
done

mkdir -p "$(dirname "${OUT}")"
cat >"${OUT}" <<EOF
#!/usr/bin/env sh
# Generated by scripts/distribution/generate_version_installer.sh. Do not hand-edit.

set -eu

APP_NAME="sifr"
APP_VERSION="${VERSION}"
ARTIFACT_BASE_URL="${ARTIFACT_BASE_URL}"
NO_MODIFY_PATH="\${SIFR_NO_MODIFY_PATH:-0}"
INSTALL_LOCK_HELD="\${SIFR_INSTALL_LOCK_HELD:-0}"
FORCE_INSTALL=0
APP_CHANNEL="${VERSION#*-}"
APP_CHANNEL="\${APP_CHANNEL%%.*}"

fail() {
  echo "sifr installer: \$*" >&2
  exit 2
}

usage() {
  cat <<'EOFUSAGE'
Usage: sifr-installer.sh [options]

Options:
  --no-modify-path    Do not update shell profiles to add Sifr to PATH
  --force             Reinstall the same version or downgrade from a newer installed version
  --help              Show this help

Environment:
  SIFR_INSTALL_DIR        Install directory (default: \$HOME/.sifr/bin)
  SIFR_SYSROOT_INSTALL_DIR
                          Sysroot/toolchain root (default: parent of SIFR_INSTALL_DIR when it ends in /bin)
  SIFR_INSTALL_MANIFEST_DIR
                          Install manifest directory (default: \$HOME/.sifr for the default install dir,
                          otherwise SIFR_INSTALL_DIR)
  SIFR_NO_MODIFY_PATH=1   Do not update shell profiles
  SIFR_INSTALL_LOCK_HELD=1
                          Internal self-update handoff; caller already holds the install lock
  SIFR_TARGET             Override target triple for validation
EOFUSAGE
}

while [ "\$#" -gt 0 ]; do
  case "\$1" in
    --no-modify-path)
      NO_MODIFY_PATH=1
      shift
      ;;
    --force)
      FORCE_INSTALL=1
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: \$1"
      ;;
  esac
done

download() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "\$1" -o "\$2"
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O "\$2" "\$1"
  else
    fail "curl or wget is required to download artifacts"
  fi
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "\$1" | awk '{print \$1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "\$1" | awk '{print \$1}'
  else
    fail "sha256sum or shasum is required to verify artifacts"
  fi
}

semver_parts() {
  version="\$1"
  core="\${version%%-*}"
  prerelease=""
  if [ "\${core}" != "\${version}" ]; then
    prerelease="\${version#*-}"
  fi

  major="\${core%%.*}"
  rest="\${core#*.}"
  minor="\${rest%%.*}"
  patch="\${rest#*.}"
  rank=4
  prerelease_number=0

  if [ -n "\${prerelease}" ]; then
    prerelease_label="\${prerelease%%.*}"
    prerelease_number="\${prerelease#*.}"
    case "\${prerelease_label}" in
      alpha)
        rank=1
        ;;
      beta)
        rank=2
        ;;
      rc)
        rank=3
        ;;
      *)
        return 1
        ;;
    esac
  fi

  printf '%s %s %s %s %s\n' "\${major}" "\${minor}" "\${patch}" "\${rank}" "\${prerelease_number}"
}

compare_numbers() {
  left="\$1"
  right="\$2"
  if [ "\${left}" -lt "\${right}" ]; then
    echo -1
  elif [ "\${left}" -gt "\${right}" ]; then
    echo 1
  else
    echo 0
  fi
}

compare_versions() {
  left_parts="\$(semver_parts "\$1")" || return 1
  right_parts="\$(semver_parts "\$2")" || return 1

  set -- \${left_parts}
  left_major="\$1"
  left_minor="\$2"
  left_patch="\$3"
  left_rank="\$4"
  left_prerelease_number="\$5"

  set -- \${right_parts}
  right_major="\$1"
  right_minor="\$2"
  right_patch="\$3"
  right_rank="\$4"
  right_prerelease_number="\$5"

  result="\$(compare_numbers "\${left_major}" "\${right_major}")"
  [ "\${result}" = "0" ] || { echo "\${result}"; return 0; }
  result="\$(compare_numbers "\${left_minor}" "\${right_minor}")"
  [ "\${result}" = "0" ] || { echo "\${result}"; return 0; }
  result="\$(compare_numbers "\${left_patch}" "\${right_patch}")"
  [ "\${result}" = "0" ] || { echo "\${result}"; return 0; }
  result="\$(compare_numbers "\${left_rank}" "\${right_rank}")"
  [ "\${result}" = "0" ] || { echo "\${result}"; return 0; }
  compare_numbers "\${left_prerelease_number}" "\${right_prerelease_number}"
}

manifest_version() {
  manifest_path="\$1"
  [ -f "\${manifest_path}" ] || return 1
  sed -n 's/^.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*$/\1/p' "\${manifest_path}" | head -n 1
}

binary_version() {
  binary_path="\$1"
  [ -x "\${binary_path}" ] || return 1
  version_output="\$("\${binary_path}" --version 2>/dev/null || true)"
  set -- \${version_output}
  [ "\${1:-}" = "\${APP_NAME}" ] || return 1
  case "\${2:-}" in
    0.0.0)
      return 1
      ;;
    [0-9]*.[0-9]*.[0-9]*)
      echo "\$2"
      ;;
    *)
      return 1
      ;;
  esac
}

detect_installed_version() {
  version="\$(manifest_version "\${manifest_path}" || true)"
  if [ -n "\${version}" ]; then
    echo "\${version}"
    return 0
  fi

  binary_version "\${installed_binary}" || true
}

canonical_path() {
  path="\$1"
  dir="\$(dirname "\${path}")"
  file="\$(basename "\${path}")"
  physical_dir="\$(cd "\${dir}" 2>/dev/null && pwd -P)" || return 1
  printf '%s/%s\n' "\${physical_dir}" "\${file}"
}

toml_string_field() {
  field="\$1"
  path="\$2"
  awk -F= -v field="\${field}" '
    {
      key = \$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      gsub(/^"|"$/, "", key)
      if (key != field) {
        next
      }
      value = \$2
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]*$/, "", value)
      if (value ~ /^"/) {
        sub(/^"/, "", value)
        sub(/"$/, "", value)
      }
      print value
      exit
    }
  ' "\${path}"
}

write_install_manifest() {
  mkdir -p "\${manifest_dir}"
  manifest_tmp="\$(mktemp "\${manifest_dir}/.install.json.XXXXXX")"
  canonical_binary_path="\$(canonical_path "\${installed_binary}" || printf '%s\n' "\${installed_binary}")"
  canonical_sysroot_path="\$(canonical_path "\${sysroot_dir}/sysroot.toml" || printf '%s/sysroot.toml\n' "\${sysroot_dir}")"
  canonical_sysroot_path="\$(dirname "\${canonical_sysroot_path}")"
  sysroot_schema_version="\$(toml_string_field "schema-version" "\${sysroot_dir}/sysroot.toml")"
  sysroot_sifr_version="\$(toml_string_field "sifr-version" "\${sysroot_dir}/sysroot.toml")"
  sysroot_target_triple="\$(toml_string_field "target-triple" "\${sysroot_dir}/sysroot.toml")"
  sysroot_content_sha256="\$(toml_string_field "sysroot-content-sha256" "\${sysroot_dir}/sysroot.toml")"
  if [ "\${NO_MODIFY_PATH}" = "1" ]; then
    modify_path=false
  else
    modify_path=true
  fi
  {
    printf '%s\n' '{'
    printf '  "schema_version": 2,\n'
    printf '  "name": "%s",\n' "\${APP_NAME}"
    printf '  "version": "%s",\n' "\${APP_VERSION}"
    printf '  "channel": "%s",\n' "\${APP_CHANNEL}"
    printf '  "target": "%s",\n' "\${target}"
    printf '  "install_dir": "%s",\n' "\${install_dir}"
    printf '  "binary_path": "%s",\n' "\${canonical_binary_path}"
    printf '  "sysroot_path": "%s",\n' "\${canonical_sysroot_path}"
    printf '  "sysroot_schema_version": %s,\n' "\${sysroot_schema_version}"
    printf '  "sysroot_sifr_version": "%s",\n' "\${sysroot_sifr_version}"
    printf '  "sysroot_target_triple": "%s",\n' "\${sysroot_target_triple}"
    printf '  "sysroot_content_sha256": "%s",\n' "\${sysroot_content_sha256}"
    printf '  "artifact": "%s",\n' "\${archive_name}"
    printf '  "modify_path": %s\n' "\${modify_path}"
    printf '%s\n' '}'
  } >"\${manifest_tmp}"
  mv "\${manifest_tmp}" "\${manifest_path}"
  manifest_tmp=""
}

acquire_install_lock() {
  mkdir -p "\${install_dir}"
  install_lock_path="\${install_dir}/.sifr-update.lock"
  if [ "\${INSTALL_LOCK_HELD}" = "1" ]; then
    if [ ! -d "\${install_lock_path}" ]; then
      fail "SIFR_INSTALL_LOCK_HELD=1 but install lock is not present at \${install_lock_path}"
    fi
    return 0
  fi
  while ! mkdir "\${install_lock_path}" 2>/dev/null; do
    sleep 1
  done
}

release_install_lock() {
  if [ "\${INSTALL_LOCK_HELD}" = "1" ]; then
    return 0
  fi
  if [ -n "\${install_lock_path:-}" ]; then
    rmdir "\${install_lock_path}" 2>/dev/null || true
  fi
}

detect_target() {
  if [ -n "\${SIFR_TARGET:-}" ]; then
    echo "\${SIFR_TARGET}"
    return 0
  fi

  os="\$(uname -s)"
  arch="\$(uname -m)"
  case "\${os}:\${arch}" in
    Darwin:arm64|Darwin:aarch64)
      echo "aarch64-apple-darwin"
      ;;
    Darwin:x86_64)
      echo "x86_64-apple-darwin"
      ;;
    Linux:x86_64)
      echo "x86_64-unknown-linux-gnu"
      ;;
    Linux:aarch64|Linux:arm64)
      echo "aarch64-unknown-linux-gnu"
      ;;
    *)
      fail "unsupported platform: \${os}/\${arch}"
    ;;
  esac
}

profile_path_expr() {
  path="\$1"
  if [ -n "\${HOME:-}" ]; then
    case "\${path}" in
      "\${HOME}/"*)
        suffix="\${path#"\${HOME}/"}"
        printf '\${HOME}/%s\n' "\${suffix}"
        return 0
        ;;
    esac
  fi
  printf '%s\n' "\${path}"
}

write_env_script_sh() {
  install_dir_expr="\$1"
  env_script_path="\$2"
  {
    printf '%s\n' '#!/usr/bin/env sh'
    printf '%s\n' '# Adds Sifr binaries to PATH if needed.'
    printf '%s\n' 'case ":\${PATH}:" in'
    printf '  *:"%s":*)\n' "\${install_dir_expr}"
    printf '%s\n' '    ;;'
    printf '%s\n' '  *)'
    printf '    export PATH="%s:\${PATH}"\n' "\${install_dir_expr}"
    printf '%s\n' '    ;;'
    printf '%s\n' 'esac'
  } >"\${env_script_path}"
}

write_env_script_fish() {
  install_dir_expr="\$1"
  fish_env_script_path="\$2"
  {
    printf 'if not contains "%s" \$PATH\n' "\${install_dir_expr}"
    printf '    set -x PATH "%s" \$PATH\n' "\${install_dir_expr}"
    printf '%s\n' 'end'
  } >"\${fish_env_script_path}"
}

append_source_line() {
  profile_path="\$1"
  source_line="\$2"
  if [ -f "\${profile_path}" ] && grep -F "\${source_line}" "\${profile_path}" >/dev/null 2>&1; then
    return 0
  fi
  {
    [ ! -f "\${profile_path}" ] || printf '\n'
    printf '%s\n' "\${source_line}"
  } >>"\${profile_path}"
  return 1
}

configure_path() {
  [ "\${NO_MODIFY_PATH}" = "1" ] && return 0
  [ -n "\${HOME:-}" ] || return 0

  install_dir_on_path=0
  case ":\${PATH}:" in
    *:"\${install_dir}":*)
      install_dir_on_path=1
      ;;
  esac

  sifr_home="\${HOME}/.sifr"
  env_script_path="\${sifr_home}/env"
  fish_config_dir="\${HOME}/.config/fish/conf.d"
  fish_env_script_path="\${fish_config_dir}/sifr.env.fish"
  install_dir_expr="\$(profile_path_expr "\${install_dir}")"
  env_script_expr="\$(profile_path_expr "\${env_script_path}")"
  fish_env_script_expr="\$(profile_path_expr "\${fish_env_script_path}")"
  source_line=". \"\${env_script_expr}\""
  shell_name="\${SHELL##*/}"
  changed=0

  mkdir -p "\${sifr_home}"
  write_env_script_sh "\${install_dir_expr}" "\${env_script_path}"

  if [ "\${install_dir_on_path}" = "1" ]; then
    if [ -d "\${HOME}/.config/fish" ] || [ "\${shell_name}" = "fish" ]; then
      mkdir -p "\${fish_config_dir}"
      write_env_script_fish "\${install_dir_expr}" "\${fish_env_script_path}"
    fi
    return 0
  fi

  if append_source_line "\${HOME}/.profile" "\${source_line}"; then
    :
  else
    changed=1
  fi

  if [ -f "\${HOME}/.bashrc" ] || [ "\${shell_name}" = "bash" ]; then
    if append_source_line "\${HOME}/.bashrc" "\${source_line}"; then :; else changed=1; fi
  fi
  if [ -f "\${HOME}/.bash_profile" ]; then
    if append_source_line "\${HOME}/.bash_profile" "\${source_line}"; then :; else changed=1; fi
  fi

  zsh_home="\${ZDOTDIR:-\${HOME}}"
  if [ -f "\${zsh_home}/.zshrc" ] || [ "\${shell_name}" = "zsh" ]; then
    if append_source_line "\${zsh_home}/.zshrc" "\${source_line}"; then :; else changed=1; fi
  fi

  if [ -d "\${HOME}/.config/fish" ] || [ "\${shell_name}" = "fish" ]; then
    mkdir -p "\${fish_config_dir}"
    write_env_script_fish "\${install_dir_expr}" "\${fish_env_script_path}"
    changed=1
  fi

  if [ "\${changed}" = "1" ]; then
    echo "configured Sifr PATH via \${env_script_path}"
    echo "restart your shell or run: . \"\${env_script_path}\""
    if [ -f "\${fish_env_script_path}" ]; then
      echo "fish users can also run: source \"\${fish_env_script_expr}\""
    fi
  fi
}

target="\$(detect_target)"
archive_name=""
archive_sha256=""

case "\${target}" in${case_entries}
    *)
      fail "unsupported target: \${target}"
      ;;
esac

base_url="\${SIFR_ARTIFACT_BASE_URL:-\${ARTIFACT_BASE_URL}}"
artifact_url="\${base_url%/}/\${archive_name}"
install_dir="\${SIFR_INSTALL_DIR:-}"
if [ -z "\${install_dir}" ]; then
  [ -n "\${HOME:-}" ] || fail "HOME or SIFR_INSTALL_DIR is required"
  install_dir="\${HOME}/.sifr/bin"
fi

manifest_dir="\${SIFR_INSTALL_MANIFEST_DIR:-}"
default_sysroot_dir=""
if [ "\$(basename "\${install_dir}")" = "bin" ]; then
  default_sysroot_dir="\$(dirname "\${install_dir}")"
else
  default_sysroot_dir="\${install_dir}"
fi
if [ -z "\${manifest_dir}" ]; then
  if [ -n "\${HOME:-}" ] && [ "\${install_dir}" = "\${HOME}/.sifr/bin" ]; then
    manifest_dir="\${HOME}/.sifr"
  elif [ "\$(basename "\${install_dir}")" = "bin" ]; then
    manifest_dir="\$(dirname "\${install_dir}")"
  else
    manifest_dir="\${install_dir}"
  fi
fi
manifest_path="\${manifest_dir}/install.json"
sysroot_dir="\${SIFR_SYSROOT_INSTALL_DIR:-\${default_sysroot_dir}}"
installed_binary="\${install_dir}/sifr"
install_lock_path=""
manifest_tmp=""
backup_root=""
rollback_active=0
installed_version="\$(detect_installed_version)"

rollback_install_transaction() {
  if [ "\${rollback_active}" != "1" ] || [ -z "\${backup_root}" ] || [ ! -d "\${backup_root}" ]; then
    return 0
  fi
  for relative in .cargo vendor crates lib Cargo.toml Cargo.lock sysroot.toml bin/sifr; do
    case "\${relative}" in
      bin/sifr)
        destination="\${installed_binary}"
        ;;
      *)
        destination="\${sysroot_dir}/\${relative}"
        ;;
    esac
    rm -rf "\${destination}"
    if [ -e "\${backup_root}/\${relative}" ]; then
      mkdir -p "\$(dirname "\${destination}")"
      mv "\${backup_root}/\${relative}" "\${destination}"
    fi
  done
  rm -rf "\${backup_root}"
}

if [ -x "\${installed_binary}" ] && [ -n "\${installed_version}" ]; then
  version_order="\$(compare_versions "\${installed_version}" "\${APP_VERSION}")" || version_order=""
  case "\${version_order}" in
    0)
      if [ "\${FORCE_INSTALL}" = "0" ]; then
        echo "Sifr \${APP_VERSION} is already installed at \${installed_binary}"
        configure_path
        exit 0
      fi
      echo "Reinstalling Sifr \${APP_VERSION} at \${installed_binary}"
      ;;
    -1)
      echo "Updating Sifr \${installed_version} -> \${APP_VERSION}"
      ;;
    1)
      if [ "\${FORCE_INSTALL}" = "0" ]; then
        fail "installed Sifr \${installed_version} is newer than requested \${APP_VERSION}; use --force to downgrade"
      fi
      echo "Downgrading Sifr \${installed_version} -> \${APP_VERSION} (--force)"
      ;;
    *)
      echo "Updating existing Sifr installation (version unknown) -> \${APP_VERSION}"
      ;;
  esac
elif [ -x "\${installed_binary}" ]; then
  echo "Updating existing Sifr installation (version unknown) -> \${APP_VERSION}"
else
  echo "Installing Sifr \${APP_VERSION}"
fi

if [ "\${SIFR_INSTALLER_TRACE:-0}" = "1" ]; then
  echo "sifr installer version=\${APP_VERSION} target=\${target} archive=\${archive_name}"
fi

tmp_dir="\$(mktemp -d "\${TMPDIR:-/tmp}/sifr-install.XXXXXX")"
cleanup() {
  rollback_install_transaction
  release_install_lock
  if [ -n "\${manifest_tmp:-}" ] && [ -f "\${manifest_tmp}" ]; then
    rm -f "\${manifest_tmp}"
  fi
  rm -rf "\${tmp_dir}"
}
trap cleanup EXIT HUP INT TERM

archive_path="\${tmp_dir}/\${archive_name}"
extract_dir="\${tmp_dir}/extract"
mkdir -p "\${extract_dir}"

download "\${artifact_url}" "\${archive_path}"
actual_sha256="\$(sha256_file "\${archive_path}")"
if [ "\${actual_sha256}" != "\${archive_sha256}" ]; then
  fail "checksum mismatch for \${archive_name}: expected \${archive_sha256}, got \${actual_sha256}"
fi

validate_archive_listing() {
  listing_path="\${tmp_dir}/archive.list"
  tar -tzf "\${archive_path}" >"\${listing_path}"
  while IFS= read -r member; do
    case "\${member}" in
      ""|/*|../*|*/../*|*/..|..)
        fail "artifact \${archive_name} contains unsafe path \${member}"
        ;;
    esac
  done <"\${listing_path}"
}

validate_archive_listing
tar -xzf "\${archive_path}" -C "\${extract_dir}"
if find "\${extract_dir}" -type l -print -quit | grep . >/dev/null 2>&1; then
  fail "artifact \${archive_name} contains symlinks"
fi

require_extracted_file() {
  relative="\$1"
  if [ ! -f "\${extract_dir}/\${relative}" ]; then
    fail "artifact \${archive_name} is missing \${relative}"
  fi
}

require_extracted_dir() {
  relative="\$1"
  if [ ! -d "\${extract_dir}/\${relative}" ]; then
    fail "artifact \${archive_name} is missing \${relative}"
  fi
}

validate_extracted_toolchain() {
  require_extracted_file "bin/sifr"
  require_extracted_file "Cargo.toml"
  require_extracted_file "Cargo.lock"
  require_extracted_file "sysroot.toml"
  require_extracted_file ".cargo/config.toml"
  require_extracted_dir "vendor"
  require_extracted_file "crates/sifr_runtime/Cargo.toml"
  require_extracted_file "crates/sifr_stdlib/Cargo.toml"
  require_extracted_dir "lib/sifr/stdlib/sifr"
  require_extracted_dir "lib/sifr/stdlib/_sifr"
  extracted_target="\$(toml_string_field "target-triple" "\${extract_dir}/sysroot.toml")"
  if [ "\${extracted_target}" != "\${target}" ]; then
    fail "artifact \${archive_name} sysroot target \${extracted_target} does not match installer target \${target}"
  fi
}

begin_install_transaction() {
  rollback_active=1
  backup_root="\${sysroot_dir}/.sifr-install-backup.\$\$"
  rm -rf "\${backup_root}"
  mkdir -p "\${backup_root}"
}

backup_path() {
  relative="\$1"
  destination="\$2"
  backup="\${backup_root}/\${relative}"
  if [ -e "\${destination}" ]; then
    mkdir -p "\$(dirname "\${backup}")"
    mv "\${destination}" "\${backup}"
  fi
}

backup_managed_toolchain() {
  backup_path ".cargo" "\${sysroot_dir}/.cargo"
  backup_path "vendor" "\${sysroot_dir}/vendor"
  backup_path "crates" "\${sysroot_dir}/crates"
  backup_path "lib" "\${sysroot_dir}/lib"
  backup_path "Cargo.toml" "\${sysroot_dir}/Cargo.toml"
  backup_path "Cargo.lock" "\${sysroot_dir}/Cargo.lock"
  backup_path "sysroot.toml" "\${sysroot_dir}/sysroot.toml"
  backup_path "bin/sifr" "\${installed_binary}"
}

replace_sysroot_path() {
  relative="\$1"
  source="\${extract_dir}/\${relative}"
  destination="\${sysroot_dir}/\${relative}"
  backup_path "\${relative}" "\${destination}"
  mkdir -p "\$(dirname "\${destination}")"
  mv "\${source}" "\${destination}"
}

install_binary_from_stage() {
  tmp_binary="\${install_dir}/.sifr.\$\$.tmp"
  mkdir -p "\${install_dir}"
  cp "\${extract_dir}/bin/sifr" "\${tmp_binary}"
  chmod 755 "\${tmp_binary}"
  backup_path "bin/sifr" "\${installed_binary}"
  mv "\${tmp_binary}" "\${installed_binary}"
}

commit_install_transaction() {
  rollback_active=0
  rm -rf "\${backup_root}"
}

validate_extracted_toolchain

acquire_install_lock
mkdir -p "\${install_dir}" "\${sysroot_dir}"
begin_install_transaction
backup_managed_toolchain
replace_sysroot_path ".cargo"
replace_sysroot_path "vendor"
replace_sysroot_path "crates"
replace_sysroot_path "lib"
replace_sysroot_path "Cargo.toml"
replace_sysroot_path "Cargo.lock"
replace_sysroot_path "sysroot.toml"
install_binary_from_stage
write_install_manifest
commit_install_transaction

echo "installed sifr \${APP_VERSION} to \${install_dir}/sifr"
configure_path
EOF

chmod 755 "${OUT}"
echo "generated version installer ${OUT}"
