#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/distribution/generate_dispatchers.sh --install-root <dir> --alpha-version <version> --beta-version <version>

Generate the public Sifr preview installer dispatchers.

Options:
  --install-root <dir>      Destination install root directory, usually apps/sifr-site/public/install
  --alpha-version <ver>     Immutable generated installer version for the alpha channel
  --beta-version <ver>      Immutable generated installer version for the beta channel and default entrypoint
  --base-url <url>          Public installer base URL (default: https://sifr.sh/install)
  --help                    Show this help
EOF
}

INSTALL_ROOT=""
ALPHA_VERSION=""
BETA_VERSION=""
BASE_URL="https://sifr.sh/install"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-root)
      INSTALL_ROOT="${2:-}"
      shift 2
      ;;
    --alpha-version)
      ALPHA_VERSION="${2:-}"
      shift 2
      ;;
    --beta-version)
      BETA_VERSION="${2:-}"
      shift 2
      ;;
    --base-url)
      BASE_URL="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${INSTALL_ROOT}" || -z "${ALPHA_VERSION}" || -z "${BETA_VERSION}" ]]; then
  echo "--install-root, --alpha-version, and --beta-version are required" >&2
  usage >&2
  exit 2
fi

preview_version_channel() {
  local version="$1"
  if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc)\.[0-9]+$ ]]; then
    return 1
  fi
  printf '%s\n' "${BASH_REMATCH[1]}"
}

if [[ "$(preview_version_channel "${ALPHA_VERSION}")" != "alpha" ]]; then
  echo "alpha version must use an -alpha.N prerelease label: ${ALPHA_VERSION}" >&2
  exit 2
fi

if [[ "$(preview_version_channel "${BETA_VERSION}")" != "beta" ]]; then
  echo "beta version must use a -beta.N prerelease label: ${BETA_VERSION}" >&2
  exit 2
fi

mkdir -p "${INSTALL_ROOT}/versions"
mkdir -p "${INSTALL_ROOT}/metadata"

cat >"${INSTALL_ROOT}/metadata/channels.json" <<EOF
{
  "schema_version": 1,
  "channels": {
    "alpha": "${ALPHA_VERSION}",
    "beta": "${BETA_VERSION}"
  }
}
EOF

write_dispatcher() {
  local path="$1"
  local default_channel="$2"

  cat >"${path}" <<EOF
#!/usr/bin/env sh
# Generated by scripts/distribution/generate_dispatchers.sh. Do not hand-edit.

set -eu

DEFAULT_CHANNEL="${default_channel}"
ALPHA_VERSION="${ALPHA_VERSION}"
BETA_VERSION="${BETA_VERSION}"
DEFAULT_INSTALL_BASE_URL="${BASE_URL}"

fail() {
  echo "sifr installer dispatcher: \$*" >&2
  exit 2
}

preview_channel_for_version() {
  if echo "\$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+$'; then
    echo "alpha"
  elif echo "\$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+-beta\.[0-9]+$'; then
    echo "beta"
  elif echo "\$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$'; then
    echo "rc"
  elif echo "\$1" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    fail "stable-looking version pins are disabled until stable GA: \$1"
  else
    fail "version must be a semver prerelease using -alpha.N, -beta.N, or -rc.N: \$1"
  fi
}

normalize_channel() {
  case "\$1" in
    alpha|beta)
      echo "\$1"
      ;;
    stable)
      fail "stable channel installs are disabled until a stable channel is supported"
      ;;
    "")
      fail "channel must not be empty"
      ;;
    *)
      fail "unknown preview channel: \$1"
      ;;
  esac
}

download() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "\$1" -o "\$2"
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O "\$2" "\$1"
  else
    fail "curl or wget is required to download the immutable installer"
  fi
}

env_channel="\${SIFR_CHANNEL:-}"
arg_channel=""
version_pin=""
installer_args=""

while [ "\$#" -gt 0 ]; do
  case "\$1" in
    --channel)
      [ "\$#" -ge 2 ] || fail "--channel requires a value"
      arg_channel="\$2"
      shift 2
      ;;
    --channel=*)
      arg_channel="\${1#--channel=}"
      shift
      ;;
    --version)
      [ "\$#" -ge 2 ] || fail "--version requires a value"
      version_pin="\$2"
      shift 2
      ;;
    --version=*)
      version_pin="\${1#--version=}"
      shift
      ;;
    *)
      installer_args="\${installer_args}
\$1"
      shift
      ;;
  esac
done

if [ -n "\${env_channel}" ]; then
  env_channel="\$(normalize_channel "\${env_channel}")"
fi
if [ -n "\${arg_channel}" ]; then
  arg_channel="\$(normalize_channel "\${arg_channel}")"
fi
if [ -n "\${env_channel}" ] && [ -n "\${arg_channel}" ] && [ "\${env_channel}" != "\${arg_channel}" ]; then
  fail "SIFR_CHANNEL=\${env_channel} conflicts with --channel \${arg_channel}"
fi

explicit_channel="\${arg_channel:-\${env_channel}}"

if [ -n "\${version_pin}" ]; then
  version_channel="\$(preview_channel_for_version "\${version_pin}")"
  if [ -n "\${explicit_channel}" ] && [ "\${explicit_channel}" != "\${version_channel}" ]; then
    fail "--version \${version_pin} conflicts with selected channel \${explicit_channel}"
  fi
  resolved_version="\${version_pin}"
  resolved_channel="\${version_channel}"
else
  resolved_channel="\$(normalize_channel "\${explicit_channel:-\${DEFAULT_CHANNEL}}")"
  case "\${resolved_channel}" in
    alpha)
      resolved_version="\${ALPHA_VERSION}"
      ;;
    beta)
      resolved_version="\${BETA_VERSION}"
      ;;
    *)
      fail "unreachable dispatcher channel: \${resolved_channel}"
      ;;
  esac
  configured_version_channel="\$(preview_channel_for_version "\${resolved_version}")"
  if [ "\${configured_version_channel}" != "\${resolved_channel}" ]; then
    fail "malformed dispatcher configuration: \${resolved_channel} points at \${resolved_version}"
  fi
fi

base_url="\${SIFR_INSTALL_BASE_URL:-\${DEFAULT_INSTALL_BASE_URL}}"
installer_url="\${base_url%/}/versions/\${resolved_version}"

if [ "\${SIFR_DISPATCH_TRACE:-0}" = "1" ]; then
  echo "sifr dispatcher channel=\${resolved_channel} version=\${resolved_version} url=\${installer_url}"
fi

tmp_dir="\$(mktemp -d "\${TMPDIR:-/tmp}/sifr-install-dispatch.XXXXXX")"
cleanup() {
  rm -rf "\${tmp_dir}"
}
trap cleanup EXIT HUP INT TERM

installer_path="\${tmp_dir}/installer.sh"
if ! download "\${installer_url}" "\${installer_path}"; then
  fail "immutable generated installer unavailable: \${installer_url}"
fi

chmod +x "\${installer_path}"
set --
if [ -n "\${installer_args}" ]; then
  while IFS= read -r installer_arg; do
    [ -n "\${installer_arg}" ] || continue
    set -- "\$@" "\${installer_arg}"
  done <<EOFARGS
\${installer_args}
EOFARGS
fi
sh "\${installer_path}" "\$@"
EOF

  chmod 755 "${path}"
}

write_dispatcher "${INSTALL_ROOT}/index" "beta"
write_dispatcher "${INSTALL_ROOT}/alpha" "alpha"
write_dispatcher "${INSTALL_ROOT}/beta" "beta"

echo "generated dispatchers and channel metadata under ${INSTALL_ROOT}"
