[package]
name = "sifr_stdlib_manifest"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
sifr_sysroot = { workspace = true }
sifr_type_system = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
