/// Rust methods used by compiler-owned IR patterns whose temporary locals have
/// no source HIR place.
///
/// Some backend method spellings also occur in source-visible lowering. Those
/// roots are retained independently through `protected_mutable_place_roots`;
/// this table is the fallback for unprotected compiler-synthesized locals.
pub(super) const COMPILER_GENERATED_MUTATING_METHODS: &[&str] = &[
    "__aenter__",
    "__aexit__",
    "__next__",
    "__sifr_add_task",
    "__sifr_join_all",
    "__sifr_spawn_infallible",
    "__sifr_spawn_result",
    "aclose",
    "anext",
    "append",
    "by_index",
    "by_name",
    "clear",
    "entry",
    "extend",
    "flush",
    "get_mut",
    "insert",
    "increment",
    "kill",
    "merge_from",
    "next",
    "pop",
    "push",
    "push_str",
    "read_string",
    "remove",
    "reverse",
    "rotate",
    "seek",
    "set",
    "set_bool",
    "set_level",
    "set_list",
    "setstate",
    "sort",
    "sort_by",
    "take",
    "try_wait",
    "retain",
    "write",
    "write_all",
    "writerow",
    "writerows",
    "writeln",
];
