use crate::session::Session;
use lsp_server::{Connection, Message};
use serde_json::{json, Value};

#[test]
fn closing_python_package_diagnostic_owner_republishes_on_remaining_document() {
    let (mut session, _temp, owner_uri, remaining_uri) = open_two_document_python_package();

    let owner_diagnostics = crate::diagnostics::document_diagnostics(&mut session, &owner_uri)
        .expect("owner diagnostics");
    assert!(contains_code(&owner_diagnostics, "SIFR-PYZC-0001"));
    let remaining_diagnostics =
        crate::diagnostics::document_diagnostics(&mut session, &remaining_uri)
            .expect("remaining diagnostics");
    assert!(!contains_code(&remaining_diagnostics, "SIFR-PYZC-0001"));

    let (server, client) = Connection::memory();
    super::handle(
        &mut session,
        &server,
        "textDocument/didClose",
        json!({"textDocument": {"uri": owner_uri}}),
    )
    .expect("close owner document");

    let publications = client
        .receiver
        .try_iter()
        .filter_map(|message| match message {
            Message::Notification(notification)
                if notification.method == "textDocument/publishDiagnostics" =>
            {
                Some(notification.params)
            }
            _ => None,
        })
        .collect::<Vec<_>>();
    assert!(publications.iter().any(|params| {
        params.get("uri").and_then(Value::as_str) == Some(owner_uri.as_str())
            && params
                .get("diagnostics")
                .and_then(Value::as_array)
                .is_some_and(Vec::is_empty)
    }));
    assert!(publications.iter().any(|params| {
        params.get("uri").and_then(Value::as_str) == Some(remaining_uri.as_str())
            && params
                .get("diagnostics")
                .and_then(Value::as_array)
                .is_some_and(|diagnostics| contains_code(diagnostics, "SIFR-PYZC-0001"))
    }));
}

#[test]
fn unanalyzable_document_cannot_own_python_package_diagnostics() {
    let (mut session, temp, owner_uri, _remaining_uri) = open_two_document_python_package();
    let excluded_dir = temp.path().join("a");
    std::fs::create_dir(&excluded_dir).expect("create excluded module directory");
    let excluded_path = excluded_dir.join("aux.sifr");
    let excluded_source = "def aux() -> int:\n    return 1\n";
    std::fs::write(&excluded_path, excluded_source).expect("write excluded source");
    let excluded_uri = url::Url::from_file_path(excluded_path)
        .expect("excluded URI")
        .to_string();
    assert!(excluded_uri < owner_uri);
    session
        .open_document(
            excluded_uri.clone(),
            crate::capabilities::LANGUAGE_ID,
            Some(1),
            excluded_source.to_string(),
        )
        .expect("open excluded document");

    let excluded_error = crate::diagnostics::document_diagnostics(&mut session, &excluded_uri)
        .expect_err("excluded document must remain outside project analysis");
    assert!(excluded_error.message().contains("analysis is unavailable"));
    let owner_diagnostics = crate::diagnostics::document_diagnostics(&mut session, &owner_uri)
        .expect("publishable owner diagnostics");
    assert!(contains_code(&owner_diagnostics, "SIFR-PYZC-0001"));
}

fn contains_code(diagnostics: &[Value], code: &str) -> bool {
    diagnostics
        .iter()
        .any(|diagnostic| diagnostic.get("code").and_then(Value::as_str) == Some(code))
}

fn open_two_document_python_package() -> (Session, tempfile::TempDir, String, String) {
    let temp = tempfile::tempdir().expect("temp dir");
    let src = temp.path().join("src");
    std::fs::create_dir(&src).expect("create src");
    let repository = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let python_project = repository.join("verification/areas/python_interop");
    link_directory(&python_project.join(".venv"), &temp.path().join(".venv"));
    std::fs::write(
        temp.path().join("Cargo.toml"),
        "[package]\nname = \"lsp-owner-fixture\"\nversion = \"0.0.0\"\nedition = \"2024\"\n\n[package.metadata.sifr]\nmanifest = \"sifr.toml\"\n\n[workspace]\n",
    )
    .expect("write Cargo manifest");
    std::fs::write(
        temp.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"lsp-owner-fixture\"\nversion = \"0.0.0\"\n",
    )
    .expect("write Cargo lock");
    std::fs::write(src.join("lib.rs"), "").expect("write Rust marker");
    std::fs::copy(
        python_project.join("pyproject.toml"),
        temp.path().join("pyproject.toml"),
    )
    .expect("copy Python project");
    std::fs::copy(python_project.join("uv.lock"), temp.path().join("uv.lock"))
        .expect("copy Python lock");
    std::fs::write(
        temp.path().join("sifr.toml"),
        "[package]\nname = \"lsp-owner\"\nedition = \"2026\"\nsifr-version = \">=0.3,<0.4\"\n\n[source]\nroot = \"src\"\n\n[python]\nvenv = \".venv\"\npyproject = \"pyproject.toml\"\nlock = \"uv.lock\"\n",
    )
    .expect("write Sifr manifest");
    std::fs::write(
        temp.path().join("sifr.python-certifications.json"),
        "{\"schema_version\":3,\"environment_digest\":\"stale\",\"arrow\":[],\"dlpack\":[]}\n",
    )
    .expect("write stale certification artifact");

    let owner_source = "from z import value\n\ndef main() -> int:\n    return value()\n";
    let remaining_source = "def value() -> int:\n    return 1\n";
    let owner_path = src.join("main.sifr");
    let remaining_path = temp.path().join("z.sifr");
    std::fs::write(&owner_path, owner_source).expect("write owner source");
    std::fs::write(&remaining_path, remaining_source).expect("write remaining source");
    let owner_uri = url::Url::from_file_path(owner_path)
        .expect("owner URI")
        .to_string();
    let remaining_uri = url::Url::from_file_path(remaining_path)
        .expect("remaining URI")
        .to_string();
    let mut session = Session::new();
    for (uri, source) in [
        (&owner_uri, owner_source),
        (&remaining_uri, remaining_source),
    ] {
        session
            .open_document(
                uri.clone(),
                crate::capabilities::LANGUAGE_ID,
                Some(1),
                source.to_string(),
            )
            .expect("open document");
    }
    (session, temp, owner_uri, remaining_uri)
}

fn link_directory(source: &std::path::Path, destination: &std::path::Path) {
    #[cfg(unix)]
    std::os::unix::fs::symlink(source, destination).expect("link Python interpreter");
    #[cfg(windows)]
    std::os::windows::fs::symlink_dir(source, destination).expect("link Python environment");
}
