fn main() {
    let a: i64 = 10 as i64;
    let b: i64 = 12 as i64;
    println!("{}", a & b);
    println!("{}", a | b);
    println!("{}", a ^ b);
    println!("{}", a << (2 as i64));
    println!("{}", a >> (1 as i64));
    let x: i64 = 42 as i64;
    println!("{}", !(x));
    println!("{}", !(0 as i64));
    let y: i64 = -(7 as i64);
    println!("{}", (y));
    println!("{}", (42 as i64));
    let mut flags: i64 = 0 as i64;
    flags |= 1 as i64;
    flags |= 4 as i64;
    println!("{}", flags);
    flags &= 3 as i64;
    println!("{}", flags);
    flags ^= 3 as i64;
    println!("{}", flags);
    flags <<= 3 as i64;
    println!("{}", flags);
    flags >>= 2 as i64;
    println!("{}", flags);
    let mut p: i64 = 0 as i64;
    let mut q: i64 = 0 as i64;
    let mut r: i64 = 0 as i64;
    r = 99 as i64;
    q = r;
    p = q;
    println!("{}", p);
    println!("{}", q);
    println!("{}", r);
}
