[package]
name = "sifr_frontend"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
sifr_diagnostics = { workspace = true }
sifr_lowering = { workspace = true }
sifr_source = { workspace = true }
sifr_syntax = { workspace = true }
sifr_type_system = { workspace = true }
sifr_python_ast = { workspace = true }
sifr_structural_identity = { workspace = true }
ruff_text_size = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
