[package]
name = "sifr_compiler_component"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sifr_diagnostics = { workspace = true }
wasmtime = { workspace = true }

[dev-dependencies]
wat = { workspace = true }

[lints]
workspace = true
