// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
use sifr_type_system::Type;
impl Encode<wire::Ref<wire::Type>> for Type {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::Type>> {
        let value = match self {
            Type::Int => wire::Type::Int,
            Type::FixedInt(v0) => wire::Type::FixedInt(v0.encode(cx)?),
            Type::Float => wire::Type::Float,
            Type::Bool => wire::Type::Bool,
            Type::Str => wire::Type::Str,
            Type::Bytes => wire::Type::Bytes,
            Type::None => wire::Type::None,
            Type::Function(v0) => wire::Type::Function(v0.encode(cx)?),
            Type::AsyncFunction(v0) => wire::Type::AsyncFunction(v0.encode(cx)?),
            Type::Coroutine(v0, v1) => wire::Type::Coroutine(v0.encode(cx)?, v1.encode(cx)?),
            Type::Task(v0, v1) => wire::Type::Task(v0.encode(cx)?, v1.encode(cx)?),
            Type::TaskResult(v0, v1) => wire::Type::TaskResult(v0.encode(cx)?, v1.encode(cx)?),
            Type::Failure(v0) => wire::Type::Failure(v0.encode(cx)?),
            Type::TimeoutResult(v0) => wire::Type::TimeoutResult(v0.encode(cx)?),
            Type::Select2(v0, v1) => wire::Type::Select2(v0.encode(cx)?, v1.encode(cx)?),
            Type::BlockingTask(v0, v1) => wire::Type::BlockingTask(v0.encode(cx)?, v1.encode(cx)?),
            Type::JoinSet(v0, v1) => wire::Type::JoinSet(v0.encode(cx)?, v1.encode(cx)?),
            Type::Awaitable(v0) => wire::Type::Awaitable(v0.encode(cx)?),
            Type::AsyncIterator(v0, v1) => {
                wire::Type::AsyncIterator(v0.encode(cx)?, v1.encode(cx)?)
            }
            Type::AsyncGenerator(v0, v1) => {
                wire::Type::AsyncGenerator(v0.encode(cx)?, v1.encode(cx)?)
            }
            Type::PythonBuffer(v0) => wire::Type::PythonBuffer(v0.encode(cx)?),
            Type::PythonArrow(v0) => wire::Type::PythonArrow(v0.encode(cx)?),
            Type::PythonDlpackTensor(v0) => wire::Type::PythonDlpackTensor(v0.encode(cx)?),
            Type::PythonDlpackStream => wire::Type::PythonDlpackStream,
            Type::List(v0) => wire::Type::List(v0.encode(cx)?),
            Type::Dict(v0, v1) => wire::Type::Dict(v0.encode(cx)?, v1.encode(cx)?),
            Type::Set(v0) => wire::Type::Set(v0.encode(cx)?),
            Type::Tuple(v0) => wire::Type::Tuple(v0.encode(cx)?),
            Type::Template(v0) => wire::Type::Template(v0.encode(cx)?),
            Type::StructuralRecord(v0) => wire::Type::StructuralRecord(v0.encode(cx)?),
            Type::Range => wire::Type::Range,
            Type::Iterable(v0) => wire::Type::Iterable(v0.encode(cx)?),
            Type::Iterator(v0) => wire::Type::Iterator(v0.encode(cx)?),
            Type::Any => wire::Type::Any,
            Type::Never => wire::Type::Never,
            Type::Union(v0) => wire::Type::Union(v0.encode(cx)?),
            Type::Intersection(v0) => wire::Type::Intersection(v0.encode(cx)?),
            Type::LiteralInt(v0) => wire::Type::LiteralInt(v0.encode(cx)?),
            Type::LiteralStr(v0) => wire::Type::LiteralStr(v0.encode(cx)?),
            Type::LiteralBool(v0) => wire::Type::LiteralBool(v0.encode(cx)?),
            Type::Unknown => wire::Type::Unknown,
            Type::Result(v0, v1) => wire::Type::Result(v0.encode(cx)?, v1.encode(cx)?),
            Type::Callable(v0, v1, v2) => {
                wire::Type::Callable(v0.encode(cx)?, v1.encode(cx)?, v2.encode(cx)?)
            }
            Type::AsyncCallable(v0, v1, v2) => {
                wire::Type::AsyncCallable(v0.encode(cx)?, v1.encode(cx)?, v2.encode(cx)?)
            }
            Type::Decimal => wire::Type::Decimal,
            Type::BigDecimal => wire::Type::BigDecimal,
            Type::TypeVar(name) => {
                let (_, binder, slot) = cx
                    .parameters
                    .iter()
                    .rev()
                    .find(|(p, _, _)| p == name)
                    .ok_or_else(|| {
                        wire::MetadataError(format!(
                            "unbound type parameter {name} in {}",
                            cx.owner
                        ))
                    })?;
                wire::Type::TypeVar {
                    binder: *binder,
                    slot: *slot,
                }
            }
            Type::Alias {
                name,
                type_args,
                body,
            } => {
                let declaration = cx.declaration(name, wire::DeclarationKind::Alias)?;
                wire::Type::Alias {
                    name: name.encode(cx)?,
                    declaration,
                    type_args: type_args.encode(cx)?,
                    body: if **body == Type::Unknown {
                        None
                    } else {
                        Some(body.encode(cx)?)
                    },
                }
            }
            Type::Class {
                identity,
                name,
                type_args,
                fields,
                methods,
                parent_class,
            } => {
                let declaration = cx.declaration(
                    identity.as_deref().unwrap_or(name),
                    wire::DeclarationKind::Class,
                )?;
                let value = wire::NominalView {
                    name: name.encode(cx)?,
                    identity: identity.encode(cx)?,
                    fields: fields.encode(cx)?,
                    methods: methods.encode(cx)?,
                    parent_class: parent_class.encode(cx)?,
                    enum_variants: Vec::new(),
                    newtype_inner: None,
                };
                let view = cx.records.intern(&value)?;
                wire::Type::Class {
                    declaration,
                    view,
                    type_args: type_args.encode(cx)?,
                }
            }
            Type::Protocol {
                identity,
                name,
                methods,
            } => {
                let declaration = cx.declaration(
                    identity.as_deref().unwrap_or(name),
                    wire::DeclarationKind::Protocol,
                )?;
                let value = wire::NominalView {
                    name: name.encode(cx)?,
                    identity: identity.encode(cx)?,
                    fields: Vec::new(),
                    methods: methods.encode(cx)?,
                    parent_class: None,
                    enum_variants: Vec::new(),
                    newtype_inner: None,
                };
                let view = cx.records.intern(&value)?;
                wire::Type::Protocol {
                    declaration,
                    view,
                    type_args: Vec::new(),
                }
            }
            Type::Newtype {
                identity,
                name,
                inner,
            } => {
                let declaration = cx.declaration(
                    identity.as_deref().unwrap_or(name),
                    wire::DeclarationKind::Newtype,
                )?;
                let value = wire::NominalView {
                    name: name.encode(cx)?,
                    identity: identity.encode(cx)?,
                    fields: Vec::new(),
                    methods: Vec::new(),
                    parent_class: None,
                    enum_variants: Vec::new(),
                    newtype_inner: Some(inner.encode(cx)?),
                };
                let view = cx.records.intern(&value)?;
                wire::Type::Newtype {
                    declaration,
                    view,
                    type_args: Vec::new(),
                }
            }
            Type::Enum {
                identity,
                name,
                variants,
            } => {
                let declaration = cx.declaration(
                    identity.as_deref().unwrap_or(name),
                    wire::DeclarationKind::Enum,
                )?;
                let value = wire::NominalView {
                    name: name.encode(cx)?,
                    identity: identity.encode(cx)?,
                    fields: Vec::new(),
                    methods: Vec::new(),
                    parent_class: None,
                    enum_variants: variants.encode(cx)?,
                    newtype_inner: None,
                };
                let view = cx.records.intern(&value)?;
                wire::Type::Enum {
                    declaration,
                    view,
                    type_args: Vec::new(),
                }
            }
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::StructuralRecordField>> for sifr_type_system::StructuralRecordField {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StructuralRecordField>> {
        let value = wire::StructuralRecordField {
            name: self.name().encode(cx)?,
            ty: self.ty().encode(cx)?,
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::StructuralRecordType>> for sifr_type_system::StructuralRecordType {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StructuralRecordType>> {
        let value = wire::StructuralRecordType {
            canonical_fields: self.fields().encode(cx)?,
            source_order: self
                .source_fields()
                .iter()
                .map(|v| v.name().encode(cx))
                .collect::<Result<_>>()?,
        };
        cx.records.intern(&value)
    }
}
