from __future__ import annotations

import json
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
AREA_ROOT = REPO_ROOT / "verification" / "areas" / "python_interop"
COMMON_ROOT = REPO_ROOT / "verification" / "areas" / "common"
sys.path.insert(0, str(COMMON_ROOT))

from sifr_binary import resolve_sifr_binary  # noqa: E402


def main() -> int:
    binary = resolve_sifr_binary(REPO_ROOT)
    root = REPO_ROOT / "target" / "verification" / "areas" / "python_interop" / "binding-authoring"
    if root.exists():
        shutil.rmtree(root)
    package = create_package(root)

    run(
        binary,
        package,
        "python",
        "bind",
        "math",
        "--symbols",
        "sqrt,ceil",
        "--override",
        "typing/math_override.pyi",
        "--external-stub",
        "typing/math_external.pyi",
    )
    write_main(package, ["from .math_python import ceil, sqrt"])
    write_manifest(package, ["math", "wrapt"], ["math"])
    run(
        binary,
        package,
        "python",
        "bind",
        "wrapt",
        "--symbols",
        "ObjectProxy",
        "--stub-package",
        "wrapt",
    )
    write_main(
        package,
        ["from .math_python import ceil, sqrt", "from .wrapt_python import ObjectProxy"],
    )
    write_manifest(package, ["math", "redis", "wrapt"], ["math"])
    run(binary, package, "python", "bind", "redis.client", "--symbols", "Redis")
    write_main(
        package,
        [
            "from .math_python import ceil, sqrt",
            "from .redis_client_python import Redis",
            "from .wrapt_python import ObjectProxy",
        ],
    )
    write_manifest(
        package,
        ["_decimal", "math", "redis", "wrapt"],
        ["math"],
    )
    run(binary, package, "python", "bind", "_decimal", "--symbols", "Decimal")
    write_main(
        package,
        [
            "from ._decimal_python import Decimal",
            "from .math_python import ceil, sqrt",
            "from .redis_client_python import Redis",
            "from .wrapt_python import ObjectProxy",
        ],
    )

    artifact_path = package / "sifr.python-bindings.json"
    artifact = json.loads(artifact_path.read_text(encoding="utf-8"))
    require(artifact["schema_version"] == 1, "binding schema drifted")
    require(
        [entry["module"] for entry in artifact["bindings"]]
        == ["_decimal", "math", "redis.client", "wrapt"],
        "bindings must be deterministically sorted",
    )
    kinds = {
        source["symbol"]: source["kind"]
        for binding in artifact["bindings"]
        for source in binding["sources"]
    }
    require(kinds["sqrt"] == "override", "explicit override did not win precedence")
    require(kinds["ceil"] == "external_stub", "configured external stub was not consumed")
    require(kinds["ObjectProxy"] == "stub_package", "stub-only distribution was not consumed")
    require(kinds["Redis"] == "py_typed", "inline py.typed source was not consumed")
    require(kinds["Decimal"] == "introspection", "safe introspection source was not recorded")

    generated = [package / binding["output"] for binding in artifact["bindings"]]
    require(all(path.is_file() for path in generated), "generated binding source is missing")
    require(
        all("Generated by `sifr python bind`" in path.read_text(encoding="utf-8") for path in generated),
        "generated source is not reviewable checked-in Sifr",
    )

    original_artifact = artifact_path.read_bytes()
    tampered = json.loads(original_artifact)
    retained = next(entry for entry in tampered["bindings"] if entry["module"] == "wrapt")
    require(retained["distribution"] is not None, "wrapt distribution identity is missing")
    retained["distribution"]["version"] += ".stale"
    retained["source_fingerprint"] = binding_fingerprint(retained)
    tampered["environment_digest"] = "f" * 64
    artifact_path.write_text(json.dumps(tampered, indent=2) + "\n", encoding="utf-8")
    stale_snapshot = snapshot(package)
    stale = run(
        binary,
        package,
        "python",
        "bind",
        "math",
        "--symbols",
        "sqrt,ceil",
        "--override",
        "typing/math_override.pyi",
        "--external-stub",
        "typing/math_external.pyi",
        expected=1,
    )
    require("wrapt" in stale.stderr and "drift" in stale.stderr.lower(),
            "environment update did not revalidate retained bindings")
    require(snapshot(package) == stale_snapshot,
            "retained-binding environment drift mutated package inputs")
    artifact_path.write_bytes(original_artifact)

    collision_snapshot = snapshot(package)
    collision = run(
        binary,
        package,
        "python",
        "bind",
        "wrapt",
        "--symbols",
        "ObjectProxy",
        "--stub-package",
        "wrapt",
        "--output",
        "src/math_python.sifr",
        expected=1,
    )
    require("duplicate Python binding output" in collision.stderr,
            "binding output collision did not fail before writing")
    require(snapshot(package) == collision_snapshot,
            "failed binding output collision mutated package inputs")

    user_output = package / "src" / "user_owned.sifr"
    user_output.write_text("def user_owned():\n    pass\n", encoding="utf-8")
    user_snapshot = snapshot(package)
    user_collision = run(
        binary,
        package,
        "python",
        "bind",
        "math",
        "--symbols",
        "sqrt",
        "--override",
        "typing/math_override.pyi",
        "--output",
        "src/user_owned.sifr",
        expected=1,
    )
    require("refusing to overwrite non-generated" in user_collision.stderr,
            "binding authoring allowed a user-owned output overwrite")
    require(snapshot(package) == user_snapshot,
            "failed user-owned output overwrite mutated package inputs")

    positional_snapshot = snapshot(package)
    positional_only = run(
        binary,
        package,
        "python",
        "bind",
        "math",
        "--symbols",
        "pow",
        "--override",
        "typing/positional_only.pyi",
        expected=1,
    )
    require("optional positional-only" in positional_only.stderr,
            "optional positional-only declaration did not fail closed")
    require(snapshot(package) == positional_snapshot,
            "failed positional-only authoring mutated package inputs")

    write_runtime_main(package)
    runtime = run(binary, package, "run", "src/main.sifr", "--frozen")
    require("binding runtime ok" in runtime.stdout,
            "cross-module PythonError binding execution did not run")

    before = snapshot(package)
    run(binary, package, "python", "bind", "--check")
    run(binary, package, "check", "src/main.sifr", "--frozen")
    require(snapshot(package) == before, "binding checks mutated package inputs")

    overload = run(
        binary,
        package,
        "python",
        "bind",
        "math",
        "--symbols",
        "mean",
        "--override",
        "typing/overload.pyi",
        expected=1,
    )
    require("overloaded symbols require" in overload.stderr, "overload failure did not fail closed")
    unresolved = run(
        binary,
        package,
        "python",
        "bind",
        "math",
        "--symbols",
        "Fraction",
        "--override",
        "typing/unresolved.pyi",
        expected=1,
    )
    require("Any" in unresolved.stderr, "untyped boundary did not fail closed")

    override = package / "typing" / "math_override.pyi"
    override.write_text("def sqrt(value: int) -> int: ...\n", encoding="utf-8")
    drift_snapshot = snapshot(package)
    drift = run(binary, package, "python", "bind", "--check", expected=1)
    normal_drift = run(binary, package, "check", "src/main.sifr", "--frozen", expected=1)
    require("drift" in drift.stderr.lower(), "bind --check did not report typing drift")
    require("drift" in normal_drift.stderr.lower(), "ordinary check did not report typing drift")
    require(snapshot(package) == drift_snapshot, "drift checks mutated package inputs")

    print(
        "python interop binding authoring ok: "
        "sources=5 generated=4 untyped_failures=2 drift_checks=2 mutations=0"
    )
    return 0


def create_package(root: Path) -> Path:
    (root / "src").mkdir(parents=True)
    (root / "typing").mkdir()
    (root / "src" / "lib.rs").write_text("// pure Sifr package marker\n", encoding="utf-8")
    (root / "src" / "main.sifr").write_text("def main():\n    pass\n", encoding="utf-8")
    (root / "typing" / "math_override.pyi").write_text(
        "def sqrt(value: float) -> float: ...\n", encoding="utf-8"
    )
    (root / "typing" / "math_external.pyi").write_text(
        "def ceil(value: float) -> int: ...\n", encoding="utf-8"
    )
    (root / "typing" / "overload.pyi").write_text(
        "from typing import overload\n"
        "@overload\ndef mean(data: list[int]) -> float: ...\n"
        "@overload\ndef mean(data: list[float]) -> float: ...\n",
        encoding="utf-8",
    )
    (root / "typing" / "unresolved.pyi").write_text(
        "from typing import Any\ndef Fraction(value: Any) -> Any: ...\n", encoding="utf-8"
    )
    (root / "typing" / "positional_only.pyi").write_text(
        "def pow(x: float, y: float = 2.0, /) -> float: ...\n", encoding="utf-8"
    )
    (root / ".venv").symlink_to(AREA_ROOT / ".venv", target_is_directory=True)
    (root / "pyproject.toml").symlink_to(AREA_ROOT / "pyproject.toml")
    (root / "uv.lock").symlink_to(AREA_ROOT / "uv.lock")
    name = "sifr-python-binding-authoring"
    (root / "Cargo.toml").write_text(
        f'[package]\nname = "{name}"\nversion = "0.1.0"\nedition = "2024"\n\n'
        '[package.metadata.sifr]\nmanifest = "sifr.toml"\n\n[workspace]\n',
        encoding="utf-8",
    )
    (root / "Cargo.lock").write_text(
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        f'version = 4\n\n[[package]]\nname = "{name}"\nversion = "0.1.0"\n',
        encoding="utf-8",
    )
    write_manifest(root, ["math"], ["math"])
    return root


def write_manifest(root: Path, imports: list[str], native: list[str]) -> None:
    quoted_imports = ", ".join(json.dumps(item) for item in imports)
    quoted_native = ", ".join(json.dumps(item) for item in native)
    (root / "sifr.toml").write_text(
        '[package]\nname = "binding_authoring"\nedition = "2026"\n'
        'sifr-version = ">=0.3,<0.4"\n\n[source]\nroot = "src"\n\n'
        '[python]\nvenv = ".venv"\npyproject = "pyproject.toml"\nlock = "uv.lock"\n\n'
        f'[trust]\npython = [{quoted_imports}]\npython-native = [{quoted_native}]\n',
        encoding="utf-8",
    )


def write_main(root: Path, imports: list[str]) -> None:
    (root / "src" / "main.sifr").write_text(
        "\n".join(imports) + "\n\n\ndef main():\n    pass\n",
        encoding="utf-8",
    )


def write_runtime_main(root: Path) -> None:
    (root / "src" / "main.sifr").write_text(
        "from .math_python import sqrt as py_sqrt\n"
        "from sifr.python import PythonError\n\n\n"
        "def main() -> Result[None, PythonError]:\n"
        "    try:\n"
        "        value: float = py_sqrt(144.0)\n"
        "        if value != 12.0:\n"
        "            raise PythonError(\"unexpected binding result\")\n"
        "        print(\"binding runtime ok\")\n"
        "        return None\n"
        "    except PythonError as error:\n"
        "        raise error\n",
        encoding="utf-8",
    )


def binding_fingerprint(binding: dict[str, object]) -> str:
    digest = hashlib.sha256()
    digest.update(b"sifr-python-binding-v1\0")
    digest.update(str(binding["module"]).encode())
    for symbol in binding["symbols"]:
        digest.update(b"\0")
        digest.update(str(symbol).encode())
    digest.update(b"\0")
    digest.update(str(binding["soabi"]).encode())
    distribution = binding["distribution"]
    if distribution is not None:
        digest.update(b"\0")
        digest.update(str(distribution["name"]).encode())
        digest.update(b"\0")
        digest.update(str(distribution["version"]).encode())
    precedence = {
        "override": 0,
        "stub_package": 1,
        "py_typed": 2,
        "external_stub": 3,
        "introspection": 4,
    }
    for source in binding["sources"]:
        digest.update(bytes([precedence[source["kind"]]]))
        digest.update(str(source["symbol"]).encode())
        digest.update(b"\0")
        digest.update(str(source["identity"]).encode())
        digest.update(b"\0")
        digest.update(str(source["digest"]).encode())
    return digest.hexdigest()


def run(
    binary: Path,
    cwd: Path,
    *arguments: str,
    expected: int = 0,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        [str(binary), *arguments],
        cwd=cwd,
        text=True,
        capture_output=True,
        check=False,
        timeout=180,
    )
    require(
        result.returncode == expected,
        f"{' '.join(arguments)} exited {result.returncode}, expected {expected}: {result.stderr}",
    )
    return result


def snapshot(root: Path) -> dict[str, tuple[str, bytes]]:
    files: dict[str, tuple[str, bytes]] = {}
    for path in sorted(root.rglob("*")):
        if "target" in path.relative_to(root).parts:
            continue
        relative = str(path.relative_to(root))
        if path.is_symlink():
            files[relative] = ("link", str(path.readlink()).encode())
        elif path.is_file():
            files[relative] = ("file", path.read_bytes())
    return files


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


if __name__ == "__main__":
    raise SystemExit(main())
