use super::Session;

#[test]
fn sifr_only_package_does_not_adopt_an_ancestor_cargo_workspace() {
    let temp = tempfile::tempdir().expect("temp dir");
    std::fs::write(
        temp.path().join("Cargo.toml"),
        "[workspace]\nmembers = []\n",
    )
    .expect("write outer Cargo workspace");
    std::fs::write(
        temp.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n",
    )
    .expect("write outer Cargo lock");
    let package = temp.path().join("nested");
    let src = package.join("src");
    std::fs::create_dir_all(&src).expect("create source root");
    std::fs::write(
        package.join("sifr.toml"),
        "[package]\nname = \"nested\"\nedition = \"2026\"\nsifr-version = \">=0.3,<0.4\"\n\n[source]\nroot = \"src\"\n",
    )
    .expect("write Sifr manifest");
    let source = "def main() -> int:\n    return 1\n";
    let path = src.join("main.sifr");
    std::fs::write(&path, source).expect("write source");
    let uri = url::Url::from_file_path(&path)
        .expect("file uri")
        .to_string();
    let mut session = Session::new();
    session
        .open_document(
            uri.clone(),
            crate::capabilities::LANGUAGE_ID,
            Some(1),
            source.to_string(),
        )
        .expect("open document");

    let diagnostics = crate::diagnostics::document_diagnostics(&mut session, &uri)
        .expect("Sifr-only diagnostics");

    assert!(
        diagnostics.is_empty(),
        "unexpected diagnostics: {diagnostics:?}"
    );
    assert!(!package.join("Cargo.toml").exists());
    assert!(!package.join("Cargo.lock").exists());
}
