// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::RustTargetPath>> for sifr_ir::RustTargetPath {
    fn decode(reference: &wire::Ref<wire::RustTargetPath>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                segments: Decode::decode(&value.segments, cx)?,
                span: Decode::decode(&value.span, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustInteropDecoratorKind>> for sifr_ir::RustInteropDecoratorKind {
    fn decode(
        reference: &wire::Ref<wire::RustInteropDecoratorKind>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::RustInteropDecoratorKind::Function => Self::Function,
                wire::RustInteropDecoratorKind::Opaque => Self::Opaque,
                wire::RustInteropDecoratorKind::Async => Self::Async,
                wire::RustInteropDecoratorKind::Callback => Self::Callback,
                wire::RustInteropDecoratorKind::Structural => Self::Structural,
                wire::RustInteropDecoratorKind::ZeroCopy => Self::ZeroCopy,
                wire::RustInteropDecoratorKind::View => Self::View,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustInteropEffect>> for sifr_ir::RustInteropEffect {
    fn decode(reference: &wire::Ref<wire::RustInteropEffect>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::RustInteropEffect::Sync => Self::Sync,
                wire::RustInteropEffect::Async => Self::Async,
                wire::RustInteropEffect::BlockingIo => Self::BlockingIo,
                wire::RustInteropEffect::CpuHeavy => Self::CpuHeavy,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustInteropAbiRequirements>> for sifr_ir::RustInteropAbiRequirements {
    fn decode(
        reference: &wire::Ref<wire::RustInteropAbiRequirements>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                async_boundary: Decode::decode(&value.async_boundary, cx)?,
                opaque_handle: Decode::decode(&value.opaque_handle, cx)?,
                zero_copy: Decode::decode(&value.zero_copy, cx)?,
                view: Decode::decode(&value.view, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustInteropArgument>> for sifr_ir::RustInteropArgument {
    fn decode(reference: &wire::Ref<wire::RustInteropArgument>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                name: Decode::decode(&value.name, cx)?,
                value: Decode::decode(&value.value, cx)?,
                span: Decode::decode(&value.span, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustInteropValue>> for sifr_ir::RustInteropValue {
    fn decode(reference: &wire::Ref<wire::RustInteropValue>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::RustInteropValue::Boolean(v0) => Self::Boolean(Decode::decode(v0, cx)?),
                wire::RustInteropValue::Symbol(v0) => Self::Symbol(Decode::decode(v0, cx)?),
                wire::RustInteropValue::Integer(v0) => Self::Integer(Decode::decode(v0, cx)?),
                wire::RustInteropValue::IntegerList(v0) => {
                    Self::IntegerList(Decode::decode(v0, cx)?)
                }
                wire::RustInteropValue::PolicyCall {
                    name,
                    argument,
                    span,
                } => Self::PolicyCall {
                    name: Decode::decode(name, cx)?,
                    argument: Decode::decode(argument, cx)?,
                    span: Decode::decode(span, cx)?,
                },
                wire::RustInteropValue::TargetPath(v0) => Self::TargetPath(Decode::decode(v0, cx)?),
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustCallbackBackpressure>> for sifr_ir::RustCallbackBackpressure {
    fn decode(
        reference: &wire::Ref<wire::RustCallbackBackpressure>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::RustCallbackBackpressure::Direct => Self::Direct,
                wire::RustCallbackBackpressure::Bounded(v0) => {
                    Self::Bounded(Decode::decode(v0, cx)?)
                }
                wire::RustCallbackBackpressure::Unbounded => Self::Unbounded,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustCallbackOverflow>> for sifr_ir::RustCallbackOverflow {
    fn decode(reference: &wire::Ref<wire::RustCallbackOverflow>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::RustCallbackOverflow::Error => Self::Error,
                wire::RustCallbackOverflow::DropOldest => Self::DropOldest,
                wire::RustCallbackOverflow::DropNewest => Self::DropNewest,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustCallbackShutdown>> for sifr_ir::RustCallbackShutdown {
    fn decode(reference: &wire::Ref<wire::RustCallbackShutdown>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::RustCallbackShutdown::Drain => Self::Drain,
                wire::RustCallbackShutdown::Cancel => Self::Cancel,
                wire::RustCallbackShutdown::DetachForbidden => Self::DetachForbidden,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustThreadsafeCallbackContract>>
    for sifr_ir::RustThreadsafeCallbackContract
{
    fn decode(
        reference: &wire::Ref<wire::RustThreadsafeCallbackContract>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                backpressure: Decode::decode(&value.backpressure, cx)?,
                overflow: Decode::decode(&value.overflow, cx)?,
                shutdown: Decode::decode(&value.shutdown, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::RustInteropDeclaration>> for sifr_ir::RustInteropDeclaration {
    fn decode(
        reference: &wire::Ref<wire::RustInteropDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                kind: Decode::decode(&value.kind, cx)?,
                target: Decode::decode(&value.target, cx)?,
                arguments: Decode::decode(&value.arguments, cx)?,
                span: Decode::decode(&value.span, cx)?,
                effect: Decode::decode(&value.effect, cx)?,
                abi_requirements: Decode::decode(&value.abi_requirements, cx)?,
                consumes_receiver: Decode::decode(&value.consumes_receiver, cx)?,
            })
        })
    }
}
