// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::HirSqlMigrationStepKind>> for sifr_ir::HirSqlMigrationStepKind {
    fn decode(
        reference: &wire::Ref<wire::HirSqlMigrationStepKind>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirSqlMigrationStepKind::Ddl => Self::Ddl,
                wire::HirSqlMigrationStepKind::SqlData => Self::SqlData,
                wire::HirSqlMigrationStepKind::SifrData => Self::SifrData,
                wire::HirSqlMigrationStepKind::Assertion => Self::Assertion,
                wire::HirSqlMigrationStepKind::Backfill => Self::Backfill,
                wire::HirSqlMigrationStepKind::Transaction => Self::Transaction,
                wire::HirSqlMigrationStepKind::RecoveryPoint => Self::RecoveryPoint,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlMigrationStep>> for sifr_ir::HirSqlMigrationStep {
    fn decode(reference: &wire::Ref<wire::HirSqlMigrationStep>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                migration_identity: Decode::decode(&value.migration_identity, cx)?,
                parent_identity: Decode::decode(&value.parent_identity, cx)?,
                step_identity: Decode::decode(&value.step_identity, cx)?,
                input_state_identity: Decode::decode(&value.input_state_identity, cx)?,
                output_state_identity: Decode::decode(&value.output_state_identity, cx)?,
                input_plan_type: Decode::decode(&value.input_plan_type, cx)?,
                output_plan_type: Decode::decode(&value.output_plan_type, cx)?,
                callback_db_type: Decode::decode(&value.callback_db_type, cx)?,
                referenced_objects: Decode::decode(&value.referenced_objects, cx)?,
                affected_objects: Decode::decode(&value.affected_objects, cx)?,
                kind: Decode::decode(&value.kind, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlMigrationGraph>> for sifr_ir::HirSqlMigrationGraph {
    fn decode(reference: &wire::Ref<wire::HirSqlMigrationGraph>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                provider_family: Decode::decode(&value.provider_family, cx)?,
                head: Decode::decode(&value.head, cx)?,
                target_fingerprint: Decode::decode(&value.target_fingerprint, cx)?,
                steps: Decode::decode(&value.steps, cx)?,
            })
        })
    }
}
