// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::HirModule>> for sifr_ir::HirModule {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirModule>> {
        let value = wire::HirModule {
            functions: self.functions.encode(cx)?,
            classes: self.classes.encode(cx)?,
            imports: self.imports.encode(cx)?,
            constants: self.constants.encode(cx)?,
            generic_functions: self.generic_functions.encode(cx)?,
            type_param_bounds: self.type_param_bounds.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirImport>> for sifr_ir::HirImport {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirImport>> {
        let value = wire::HirImport {
            module: self.module.encode(cx)?,
            names: self.names.encode(cx)?,
            aliases: self.aliases.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirClassKind>> for sifr_ir::HirClassKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirClassKind>> {
        let value = match self {
            sifr_ir::HirClassKind::Regular => wire::HirClassKind::Regular,
            sifr_ir::HirClassKind::Protocol => wire::HirClassKind::Protocol,
            sifr_ir::HirClassKind::Enum => wire::HirClassKind::Enum,
            sifr_ir::HirClassKind::PythonOpaque(v0) => {
                wire::HirClassKind::PythonOpaque(v0.encode(cx)?)
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirClass>> for sifr_ir::HirClass {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirClass>> {
        cx.with_owner(
            &self.name,
            &self.type_params,
            super::class_kind(self),
            |cx| {
                let value = wire::HirClass {
                    name: self.name.encode(cx)?,
                    identity: self.identity.encode(cx)?,
                    fields: self.fields.encode(cx)?,
                    field_defaults: self.field_defaults.encode(cx)?,
                    field_default_identities: self.field_default_identities.encode(cx)?,
                    declaration_metadata: self.declaration_metadata.encode(cx)?,
                    methods: self.methods.encode(cx)?,
                    is_hashable: self.is_hashable.encode(cx)?,
                    is_error_type: self.is_error_type.encode(cx)?,
                    kind: self.kind.encode(cx)?,
                    operator_impls: self.operator_impls.encode(cx)?,
                    newtype_inner: self.newtype_inner.encode(cx)?,
                    implements_protocols: self.implements_protocols.encode(cx)?,
                    parent_class: self.parent_class.encode(cx)?,
                    parent_type: self.parent_type.encode(cx)?,
                    type_params: self.type_params.encode(cx)?,
                    enum_variants: self.enum_variants.encode(cx)?,
                    rust_interop: self.rust_interop.encode(cx)?,
                };
                cx.records.intern(&value).map_err(Into::into)
            },
        )
    }
}
impl Encode<wire::Ref<wire::MethodKind>> for sifr_ir::MethodKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::MethodKind>> {
        let value = match self {
            sifr_ir::MethodKind::Regular => wire::MethodKind::Regular,
            sifr_ir::MethodKind::ClassMethod => wire::MethodKind::ClassMethod,
            sifr_ir::MethodKind::StaticMethod => wire::MethodKind::StaticMethod,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::MethodCallSource>> for sifr_ir::MethodCallSource {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::MethodCallSource>> {
        let value = wire::MethodCallSource {
            call_range: self.call_range.encode(cx)?,
            receiver_range: self.receiver_range.encode(cx)?,
            arg_ranges: self.arg_ranges.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::FieldIdentity>> for sifr_ir::FieldIdentity {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::FieldIdentity>> {
        let value = wire::FieldIdentity {
            declaring_class: self.declaring_class.encode(cx)?,
            field: self.field.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PlaceProjection>> for sifr_ir::PlaceProjection {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PlaceProjection>> {
        let value = match self {
            sifr_ir::PlaceProjection::Field(v0) => wire::PlaceProjection::Field(v0.encode(cx)?),
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::Place>> for sifr_ir::Place {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::Place>> {
        let value = wire::Place {
            root: self.root.encode(cx)?,
            projections: self.projections.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::MutableReceiverTarget>> for sifr_ir::MutableReceiverTarget {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::MutableReceiverTarget>> {
        let value = match self {
            sifr_ir::MutableReceiverTarget::Place(v0) => {
                wire::MutableReceiverTarget::Place(v0.encode(cx)?)
            }
            sifr_ir::MutableReceiverTarget::OwnedTemporary => {
                wire::MutableReceiverTarget::OwnedTemporary
            }
            sifr_ir::MutableReceiverTarget::SpecializedIndexedStorage(v0) => {
                wire::MutableReceiverTarget::SpecializedIndexedStorage(v0.encode(cx)?)
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::MutableArgumentTarget>> for sifr_ir::MutableArgumentTarget {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::MutableArgumentTarget>> {
        let value = match self {
            sifr_ir::MutableArgumentTarget::Place(v0) => {
                wire::MutableArgumentTarget::Place(v0.encode(cx)?)
            }
            sifr_ir::MutableArgumentTarget::OwnedTemporary => {
                wire::MutableArgumentTarget::OwnedTemporary
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirFunction>> for sifr_ir::HirFunction {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirFunction>> {
        cx.with_owner(
            &self.name,
            &self.type_params,
            wire::DeclarationKind::Function,
            |cx| {
                let value = wire::HirFunction {
                    name: self.name.encode(cx)?,
                    params: self.params.encode(cx)?,
                    return_type: self.return_type.encode(cx)?,
                    body: self.body.encode(cx)?,
                    is_async: self.is_async.encode(cx)?,
                    method_kind: self.method_kind.encode(cx)?,
                    receiver: self.receiver.encode(cx)?,
                    decorators: self.decorators.encode(cx)?,
                    rust_interop: self.rust_interop.encode(cx)?,
                    python_interop: self.python_interop.encode(cx)?,
                    compiler_intrinsic: self.compiler_intrinsic.encode(cx)?,
                    type_params: self.type_params.encode(cx)?,
                };
                cx.records.intern(&value).map_err(Into::into)
            },
        )
    }
}
impl Encode<wire::Ref<wire::CompilerIntrinsicId>> for sifr_ir::CompilerIntrinsicId {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::CompilerIntrinsicId>> {
        let value = match self {
            sifr_ir::CompilerIntrinsicId::TestAssertEqual => {
                wire::CompilerIntrinsicId::TestAssertEqual
            }
            sifr_ir::CompilerIntrinsicId::TestAssertNotEqual => {
                wire::CompilerIntrinsicId::TestAssertNotEqual
            }
            sifr_ir::CompilerIntrinsicId::TestAssertTrue => {
                wire::CompilerIntrinsicId::TestAssertTrue
            }
            sifr_ir::CompilerIntrinsicId::TestAssertFalse => {
                wire::CompilerIntrinsicId::TestAssertFalse
            }
            sifr_ir::CompilerIntrinsicId::TestAssertAlmostEqual => {
                wire::CompilerIntrinsicId::TestAssertAlmostEqual
            }
            sifr_ir::CompilerIntrinsicId::TestAssertGreaterThan => {
                wire::CompilerIntrinsicId::TestAssertGreaterThan
            }
            sifr_ir::CompilerIntrinsicId::TestAssertLessThan => {
                wire::CompilerIntrinsicId::TestAssertLessThan
            }
            sifr_ir::CompilerIntrinsicId::OpenBinary => wire::CompilerIntrinsicId::OpenBinary,
            sifr_ir::CompilerIntrinsicId::OpenText => wire::CompilerIntrinsicId::OpenText,
            sifr_ir::CompilerIntrinsicId::BytesFromHex => wire::CompilerIntrinsicId::BytesFromHex,
            sifr_ir::CompilerIntrinsicId::BytesWithSize => wire::CompilerIntrinsicId::BytesWithSize,
            sifr_ir::CompilerIntrinsicId::BytesFromIntegers => {
                wire::CompilerIntrinsicId::BytesFromIntegers
            }
            sifr_ir::CompilerIntrinsicId::StringEncode => wire::CompilerIntrinsicId::StringEncode,
            sifr_ir::CompilerIntrinsicId::StringEncodeWithEncoding => {
                wire::CompilerIntrinsicId::StringEncodeWithEncoding
            }
            sifr_ir::CompilerIntrinsicId::BytesDecode => wire::CompilerIntrinsicId::BytesDecode,
            sifr_ir::CompilerIntrinsicId::BytesDecodeWithEncoding => {
                wire::CompilerIntrinsicId::BytesDecodeWithEncoding
            }
            sifr_ir::CompilerIntrinsicId::TaskCurrentContext => {
                wire::CompilerIntrinsicId::TaskCurrentContext
            }
            sifr_ir::CompilerIntrinsicId::PythonFromValue => {
                wire::CompilerIntrinsicId::PythonFromValue
            }
            sifr_ir::CompilerIntrinsicId::PythonToValue => wire::CompilerIntrinsicId::PythonToValue,
            sifr_ir::CompilerIntrinsicId::PythonKwarg => wire::CompilerIntrinsicId::PythonKwarg,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirAsyncWithKind>> for sifr_ir::HirAsyncWithKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirAsyncWithKind>> {
        let value = match self {
            sifr_ir::HirAsyncWithKind::TaskScope => wire::HirAsyncWithKind::TaskScope,
            sifr_ir::HirAsyncWithKind::TaskGroup { context } => wire::HirAsyncWithKind::TaskGroup {
                context: context.encode(cx)?,
            },
            sifr_ir::HirAsyncWithKind::TaskTimeout { duration } => {
                wire::HirAsyncWithKind::TaskTimeout {
                    duration: duration.encode(cx)?,
                }
            }
            sifr_ir::HirAsyncWithKind::UserDefined {
                context,
                enter_value_ty,
                enter_error_ty,
                exit_error_ty,
                active_error_ty,
                body_may_raise,
            } => wire::HirAsyncWithKind::UserDefined {
                context: context.encode(cx)?,
                enter_value_ty: enter_value_ty.encode(cx)?,
                enter_error_ty: enter_error_ty.encode(cx)?,
                exit_error_ty: exit_error_ty.encode(cx)?,
                active_error_ty: active_error_ty.encode(cx)?,
                body_may_raise: body_may_raise.encode(cx)?,
            },
            sifr_ir::HirAsyncWithKind::Python {
                context,
                manager_class,
                entered_type,
                enter_error_type,
                exit_error_type,
                entered_is_opaque_borrow,
                active_error_type,
                body_may_raise,
            } => wire::HirAsyncWithKind::Python {
                context: context.encode(cx)?,
                manager_class: manager_class.encode(cx)?,
                entered_type: entered_type.encode(cx)?,
                enter_error_type: enter_error_type.encode(cx)?,
                exit_error_type: exit_error_type.encode(cx)?,
                entered_is_opaque_borrow: entered_is_opaque_borrow.encode(cx)?,
                active_error_type: active_error_type.encode(cx)?,
                body_may_raise: body_may_raise.encode(cx)?,
            },
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirWithItemKind>> for sifr_ir::HirWithItemKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirWithItemKind>> {
        let value = match self {
            sifr_ir::HirWithItemKind::Native {
                has_context_manager_protocol,
            } => wire::HirWithItemKind::Native {
                has_context_manager_protocol: has_context_manager_protocol.encode(cx)?,
            },
            sifr_ir::HirWithItemKind::Python {
                entered_type,
                enter_error_type,
                exit_error_type,
                entered_is_opaque_borrow,
                body_may_raise,
            } => wire::HirWithItemKind::Python {
                entered_type: entered_type.encode(cx)?,
                enter_error_type: enter_error_type.encode(cx)?,
                exit_error_type: exit_error_type.encode(cx)?,
                entered_is_opaque_borrow: entered_is_opaque_borrow.encode(cx)?,
                body_may_raise: body_may_raise.encode(cx)?,
            },
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirWithItem>> for sifr_ir::HirWithItem {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirWithItem>> {
        let value = wire::HirWithItem {
            target: self.target.encode(cx)?,
            context: self.context.encode(cx)?,
            kind: self.kind.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirParam>> for sifr_ir::HirParam {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirParam>> {
        let value = wire::HirParam {
            name: self.name.encode(cx)?,
            ty: self.ty.encode(cx)?,
            default: self.default.encode(cx)?,
            keyword_only: self.keyword_only.encode(cx)?,
            convention: self.convention.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirStmt>> for sifr_ir::HirStmt {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirStmt>> {
        let value = match self {
            sifr_ir::HirStmt::Let {
                name,
                ty,
                value,
                is_mutable,
            } => wire::HirStmt::Let {
                name: name.encode(cx)?,
                ty: ty.encode(cx)?,
                value: value.encode(cx)?,
                is_mutable: is_mutable.encode(cx)?,
            },
            sifr_ir::HirStmt::Assign { name, value } => wire::HirStmt::Assign {
                name: name.encode(cx)?,
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::AugAssign { name, op, value } => wire::HirStmt::AugAssign {
                name: name.encode(cx)?,
                op: op.encode(cx)?,
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::Return { value } => wire::HirStmt::Return {
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::Expr { expr } => wire::HirStmt::Expr {
                expr: expr.encode(cx)?,
            },
            sifr_ir::HirStmt::If {
                condition,
                then_body,
                elif_clauses,
                else_body,
            } => wire::HirStmt::If {
                condition: condition.encode(cx)?,
                then_body: then_body.encode(cx)?,
                elif_clauses: elif_clauses.encode(cx)?,
                else_body: else_body.encode(cx)?,
            },
            sifr_ir::HirStmt::While {
                condition,
                body,
                else_body,
            } => wire::HirStmt::While {
                condition: condition.encode(cx)?,
                body: body.encode(cx)?,
                else_body: else_body.encode(cx)?,
            },
            sifr_ir::HirStmt::For {
                target,
                target_ty,
                iter,
                body,
                else_body,
            } => wire::HirStmt::For {
                target: target.encode(cx)?,
                target_ty: target_ty.encode(cx)?,
                iter: iter.encode(cx)?,
                body: body.encode(cx)?,
                else_body: else_body.encode(cx)?,
            },
            sifr_ir::HirStmt::AsyncFor {
                target,
                target_ty,
                iter,
                iter_error_ty,
                close_error_ty,
                active_error_ty,
                body_may_raise,
                body,
                else_body,
            } => wire::HirStmt::AsyncFor {
                target: target.encode(cx)?,
                target_ty: target_ty.encode(cx)?,
                iter: iter.encode(cx)?,
                iter_error_ty: iter_error_ty.encode(cx)?,
                close_error_ty: close_error_ty.encode(cx)?,
                active_error_ty: active_error_ty.encode(cx)?,
                body_may_raise: body_may_raise.encode(cx)?,
                body: body.encode(cx)?,
                else_body: else_body.encode(cx)?,
            },
            sifr_ir::HirStmt::Break => wire::HirStmt::Break,
            sifr_ir::HirStmt::Continue => wire::HirStmt::Continue,
            sifr_ir::HirStmt::TupleUnpack { targets, value } => wire::HirStmt::TupleUnpack {
                targets: targets.encode(cx)?,
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::StarUnpack {
                before,
                star,
                after,
                value,
                failure,
            } => wire::HirStmt::StarUnpack {
                before: before.encode(cx)?,
                star: star.encode(cx)?,
                after: after.encode(cx)?,
                value: value.encode(cx)?,
                failure: failure.encode(cx)?,
            },
            sifr_ir::HirStmt::Pass => wire::HirStmt::Pass,
            sifr_ir::HirStmt::Assert { test, msg } => wire::HirStmt::Assert {
                test: test.encode(cx)?,
                msg: msg.encode(cx)?,
            },
            sifr_ir::HirStmt::Raise { value } => wire::HirStmt::Raise {
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::TryExcept {
                body,
                handlers,
                body_error_types,
            } => wire::HirStmt::TryExcept {
                body: body.encode(cx)?,
                handlers: handlers.encode(cx)?,
                body_error_types: super::encode::error_type_set(body_error_types, cx)?,
            },
            sifr_ir::HirStmt::TryFinally { body, finalbody } => wire::HirStmt::TryFinally {
                body: body.encode(cx)?,
                finalbody: finalbody.encode(cx)?,
            },
            sifr_ir::HirStmt::FieldAssign {
                object,
                field,
                field_ty,
                value,
            } => wire::HirStmt::FieldAssign {
                object: object.encode(cx)?,
                field: field.encode(cx)?,
                field_ty: field_ty.encode(cx)?,
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::NestedFieldAssign {
                object,
                field,
                field_ty,
                nested_field,
                nested_field_ty,
                value,
            } => wire::HirStmt::NestedFieldAssign {
                object: object.encode(cx)?,
                field: field.encode(cx)?,
                field_ty: field_ty.encode(cx)?,
                nested_field: nested_field.encode(cx)?,
                nested_field_ty: nested_field_ty.encode(cx)?,
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::SubscriptAssign {
                object,
                index,
                value,
                object_ty,
                failure,
            } => wire::HirStmt::SubscriptAssign {
                object: object.encode(cx)?,
                index: index.encode(cx)?,
                value: value.encode(cx)?,
                object_ty: object_ty.encode(cx)?,
                failure: failure.encode(cx)?,
            },
            sifr_ir::HirStmt::NestedSubscriptAssign {
                object,
                outer_index,
                inner_index,
                value,
                object_ty,
                outer_failure,
                inner_failure,
                operation,
            } => wire::HirStmt::NestedSubscriptAssign {
                object: object.encode(cx)?,
                outer_index: outer_index.encode(cx)?,
                inner_index: inner_index.encode(cx)?,
                value: value.encode(cx)?,
                object_ty: object_ty.encode(cx)?,
                outer_failure: outer_failure.encode(cx)?,
                inner_failure: inner_failure.encode(cx)?,
                operation: operation.encode(cx)?,
            },
            sifr_ir::HirStmt::AttributeNestedSubscriptAssign {
                object,
                field,
                outer_index,
                inner_index,
                value,
                field_ty,
                outer_failure,
                inner_failure,
                operation,
            } => wire::HirStmt::AttributeNestedSubscriptAssign {
                object: object.encode(cx)?,
                field: field.encode(cx)?,
                outer_index: outer_index.encode(cx)?,
                inner_index: inner_index.encode(cx)?,
                value: value.encode(cx)?,
                field_ty: field_ty.encode(cx)?,
                outer_failure: outer_failure.encode(cx)?,
                inner_failure: inner_failure.encode(cx)?,
                operation: operation.encode(cx)?,
            },
            sifr_ir::HirStmt::SubscriptAugAssign {
                object,
                index,
                op,
                value,
                object_ty,
                failure,
            } => wire::HirStmt::SubscriptAugAssign {
                object: object.encode(cx)?,
                index: index.encode(cx)?,
                op: op.encode(cx)?,
                value: value.encode(cx)?,
                object_ty: object_ty.encode(cx)?,
                failure: failure.encode(cx)?,
            },
            sifr_ir::HirStmt::AttributeAugAssign {
                object,
                field,
                op,
                value,
            } => wire::HirStmt::AttributeAugAssign {
                object: object.encode(cx)?,
                field: field.encode(cx)?,
                op: op.encode(cx)?,
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::AttributeSubscriptAssign {
                object,
                field,
                index,
                value,
                field_ty,
                failure,
                operation,
            } => wire::HirStmt::AttributeSubscriptAssign {
                object: object.encode(cx)?,
                field: field.encode(cx)?,
                index: index.encode(cx)?,
                value: value.encode(cx)?,
                field_ty: field_ty.encode(cx)?,
                failure: failure.encode(cx)?,
                operation: operation.encode(cx)?,
            },
            sifr_ir::HirStmt::Delete {
                object,
                index,
                failure,
            } => wire::HirStmt::Delete {
                object: object.encode(cx)?,
                index: index.encode(cx)?,
                failure: failure.encode(cx)?,
            },
            sifr_ir::HirStmt::Yield { value } => wire::HirStmt::Yield {
                value: value.encode(cx)?,
            },
            sifr_ir::HirStmt::With { items, body } => wire::HirStmt::With {
                items: items.encode(cx)?,
                body: body.encode(cx)?,
            },
            sifr_ir::HirStmt::AsyncWith { kind, target, body } => wire::HirStmt::AsyncWith {
                kind: kind.encode(cx)?,
                target: target.encode(cx)?,
                body: body.encode(cx)?,
            },
            sifr_ir::HirStmt::NestedFunction {
                func,
                move_captures,
                capture_clones,
            } => wire::HirStmt::NestedFunction {
                func: func.encode(cx)?,
                move_captures: move_captures.encode(cx)?,
                capture_clones: capture_clones.encode(cx)?,
            },
            sifr_ir::HirStmt::Match {
                subject,
                subject_ty,
                arms,
            } => wire::HirStmt::Match {
                subject: subject.encode(cx)?,
                subject_ty: subject_ty.encode(cx)?,
                arms: arms.encode(cx)?,
            },
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirCollectionMutation>> for sifr_ir::HirCollectionMutation {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirCollectionMutation>> {
        let value = match self {
            sifr_ir::HirCollectionMutation::Assign => wire::HirCollectionMutation::Assign,
            sifr_ir::HirCollectionMutation::AugAssign(v0) => {
                wire::HirCollectionMutation::AugAssign(v0.encode(cx)?)
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirMatchArm>> for sifr_ir::HirMatchArm {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirMatchArm>> {
        let value = wire::HirMatchArm {
            pattern: self.pattern.encode(cx)?,
            guard: self.guard.encode(cx)?,
            body: self.body.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirPattern>> for sifr_ir::HirPattern {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirPattern>> {
        let value = match self {
            sifr_ir::HirPattern::Wildcard => wire::HirPattern::Wildcard,
            sifr_ir::HirPattern::Capture { name, ty } => wire::HirPattern::Capture {
                name: name.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirPattern::Literal { value } => wire::HirPattern::Literal {
                value: value.encode(cx)?,
            },
            sifr_ir::HirPattern::None => wire::HirPattern::None,
            sifr_ir::HirPattern::Or { patterns } => wire::HirPattern::Or {
                patterns: patterns.encode(cx)?,
            },
            sifr_ir::HirPattern::Class {
                class_name,
                class_type,
                fields,
            } => wire::HirPattern::Class {
                class_name: class_name.encode(cx)?,
                class_type: class_type.encode(cx)?,
                fields: fields.encode(cx)?,
            },
            sifr_ir::HirPattern::Value { path } => wire::HirPattern::Value {
                path: path.encode(cx)?,
            },
            sifr_ir::HirPattern::Tuple { elements } => wire::HirPattern::Tuple {
                elements: elements.encode(cx)?,
            },
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirExceptHandler>> for sifr_ir::HirExceptHandler {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirExceptHandler>> {
        let value = wire::HirExceptHandler {
            error_type: self.error_type.encode(cx)?,
            error_resolved_type: self.error_resolved_type.encode(cx)?,
            name: self.name.encode(cx)?,
            body: self.body.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirFStringPart>> for sifr_ir::HirFStringPart {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirFStringPart>> {
        let value = match self {
            sifr_ir::HirFStringPart::Literal(v0) => wire::HirFStringPart::Literal(v0.encode(cx)?),
            sifr_ir::HirFStringPart::Expr(v0) => wire::HirFStringPart::Expr(v0.encode(cx)?),
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirIteratorOp>> for sifr_ir::HirIteratorOp {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirIteratorOp>> {
        let value = match self {
            sifr_ir::HirIteratorOp::Iter => wire::HirIteratorOp::Iter,
            sifr_ir::HirIteratorOp::Next => wire::HirIteratorOp::Next,
            sifr_ir::HirIteratorOp::Reversed => wire::HirIteratorOp::Reversed,
            sifr_ir::HirIteratorOp::Map => wire::HirIteratorOp::Map,
            sifr_ir::HirIteratorOp::Filter => wire::HirIteratorOp::Filter,
            sifr_ir::HirIteratorOp::Zip => wire::HirIteratorOp::Zip,
            sifr_ir::HirIteratorOp::Enumerate => wire::HirIteratorOp::Enumerate,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirExpr>> for sifr_ir::HirExpr {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirExpr>> {
        let value = match self {
            sifr_ir::HirExpr::IntLiteral(v0) => wire::HirExpr::IntLiteral(v0.encode(cx)?),
            sifr_ir::HirExpr::LargeIntLiteral(v0) => wire::HirExpr::LargeIntLiteral(v0.encode(cx)?),
            sifr_ir::HirExpr::FloatLiteral(v0) => wire::HirExpr::FloatLiteral(v0.encode(cx)?),
            sifr_ir::HirExpr::StringLiteral(v0) => wire::HirExpr::StringLiteral(v0.encode(cx)?),
            sifr_ir::HirExpr::BoolLiteral(v0) => wire::HirExpr::BoolLiteral(v0.encode(cx)?),
            sifr_ir::HirExpr::NoneLiteral => wire::HirExpr::NoneLiteral,
            sifr_ir::HirExpr::Name {
                name,
                binding_id,
                ty,
            } => wire::HirExpr::Name {
                name: name.encode(cx)?,
                binding_id: binding_id.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::BinOp {
                left,
                op,
                right,
                ty,
            } => wire::HirExpr::BinOp {
                left: left.encode(cx)?,
                op: op.encode(cx)?,
                right: right.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::UnaryOp { op, operand, ty } => wire::HirExpr::UnaryOp {
                op: op.encode(cx)?,
                operand: operand.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::Compare {
                left,
                ops,
                comparators,
                ty,
            } => wire::HirExpr::Compare {
                left: left.encode(cx)?,
                ops: ops.encode(cx)?,
                comparators: comparators.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::BoolOp { op, values, ty } => wire::HirExpr::BoolOp {
                op: op.encode(cx)?,
                values: values.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::Call {
                func,
                args,
                mutable_arg_places,
                ty,
            } => wire::HirExpr::Call {
                func: func.encode(cx)?,
                args: args.encode(cx)?,
                mutable_arg_places: mutable_arg_places.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::GenericCall {
                func,
                type_args,
                args,
                mutable_arg_places,
                ty,
            } => wire::HirExpr::GenericCall {
                func: func.encode(cx)?,
                type_args: type_args.encode(cx)?,
                args: args.encode(cx)?,
                mutable_arg_places: mutable_arg_places.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::PythonCall {
                func,
                args,
                provided_arguments,
                record_expansions,
                ty,
            } => wire::HirExpr::PythonCall {
                func: func.encode(cx)?,
                args: args.encode(cx)?,
                provided_arguments: provided_arguments.encode(cx)?,
                record_expansions: record_expansions.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::IntrinsicCall {
                intrinsic,
                args,
                ty,
                call_range,
                arg_ranges,
            } => wire::HirExpr::IntrinsicCall {
                intrinsic: intrinsic.encode(cx)?,
                args: args.encode(cx)?,
                ty: ty.encode(cx)?,
                call_range: call_range.encode(cx)?,
                arg_ranges: arg_ranges.encode(cx)?,
            },
            sifr_ir::HirExpr::Await { value, ty } => wire::HirExpr::Await {
                value: value.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::IteratorCall {
                op,
                args,
                mutable_arg_places,
                ty,
            } => wire::HirExpr::IteratorCall {
                op: op.encode(cx)?,
                args: args.encode(cx)?,
                mutable_arg_places: mutable_arg_places.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::IfExpr {
                condition,
                then_expr,
                else_expr,
                ty,
            } => wire::HirExpr::IfExpr {
                condition: condition.encode(cx)?,
                then_expr: then_expr.encode(cx)?,
                else_expr: else_expr.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::RangeLiteral {
                start,
                end,
                step,
                ty,
            } => wire::HirExpr::RangeLiteral {
                start: start.encode(cx)?,
                end: end.encode(cx)?,
                step: step.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::ListLiteral { elements, ty } => wire::HirExpr::ListLiteral {
                elements: elements.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::SetLiteral { elements, ty } => wire::HirExpr::SetLiteral {
                elements: elements.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::DictLiteral { keys, values, ty } => wire::HirExpr::DictLiteral {
                keys: keys.encode(cx)?,
                values: values.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::TupleLiteral { elements, ty } => wire::HirExpr::TupleLiteral {
                elements: elements.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::Index { object, index, ty } => wire::HirExpr::Index {
                object: object.encode(cx)?,
                index: index.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::MethodCall {
                object,
                method,
                args,
                receiver_convention,
                receiver_target,
                mutable_arg_places,
                source,
                ty,
            } => wire::HirExpr::MethodCall {
                object: object.encode(cx)?,
                method: method.encode(cx)?,
                args: args.encode(cx)?,
                receiver_convention: receiver_convention.encode(cx)?,
                receiver_target: receiver_target.encode(cx)?,
                mutable_arg_places: mutable_arg_places.encode(cx)?,
                source: source.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::ContainsOp {
                element,
                collection,
                ty,
            } => wire::HirExpr::ContainsOp {
                element: element.encode(cx)?,
                collection: collection.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::FString { parts, ty } => wire::HirExpr::FString {
                parts: parts.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::TemplateString(v0) => wire::HirExpr::TemplateString(v0.encode(cx)?),
            sifr_ir::HirExpr::Slice {
                object,
                start,
                stop,
                step,
                ty,
            } => wire::HirExpr::Slice {
                object: object.encode(cx)?,
                start: start.encode(cx)?,
                stop: stop.encode(cx)?,
                step: step.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::WalrusExpr { name, value, ty } => wire::HirExpr::WalrusExpr {
                name: name.encode(cx)?,
                value: value.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::FieldAccess { object, field, ty } => wire::HirExpr::FieldAccess {
                object: object.encode(cx)?,
                field: field.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::StructuralRecordProject { source, fields, ty } => {
                wire::HirExpr::StructuralRecordProject {
                    source: source.encode(cx)?,
                    fields: fields.encode(cx)?,
                    ty: ty.encode(cx)?,
                }
            }
            sifr_ir::HirExpr::ConstructorCall {
                class_name,
                args,
                ty,
            } => wire::HirExpr::ConstructorCall {
                class_name: class_name.encode(cx)?,
                args: args.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::QuestionMark { expr, ty } => wire::HirExpr::QuestionMark {
                expr: expr.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::OkWrap { value, ty } => wire::HirExpr::OkWrap {
                value: value.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::ErrWrap { value, ty } => wire::HirExpr::ErrWrap {
                value: value.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::SuperCall {
                parent_class,
                parent_type,
                method,
                args,
                ty,
            } => wire::HirExpr::SuperCall {
                parent_class: parent_class.encode(cx)?,
                parent_type: parent_type.encode(cx)?,
                method: method.encode(cx)?,
                args: args.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::Lambda { params, body, ty } => wire::HirExpr::Lambda {
                params: params.encode(cx)?,
                body: body.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::ListComp {
                expr,
                generators,
                ty,
            } => wire::HirExpr::ListComp {
                expr: expr.encode(cx)?,
                generators: generators.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::DictComp {
                key_expr,
                val_expr,
                generators,
                ty,
            } => wire::HirExpr::DictComp {
                key_expr: key_expr.encode(cx)?,
                val_expr: val_expr.encode(cx)?,
                generators: generators.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::SetComp {
                expr,
                generators,
                ty,
            } => wire::HirExpr::SetComp {
                expr: expr.encode(cx)?,
                generators: generators.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::GeneratorExpr {
                expr,
                var,
                iter,
                filter,
                ty,
            } => wire::HirExpr::GeneratorExpr {
                expr: expr.encode(cx)?,
                var: var.encode(cx)?,
                iter: iter.encode(cx)?,
                filter: filter.encode(cx)?,
                ty: ty.encode(cx)?,
            },
            sifr_ir::HirExpr::EnumVariant {
                enum_name,
                variant,
                ty,
            } => wire::HirExpr::EnumVariant {
                enum_name: enum_name.encode(cx)?,
                variant: variant.encode(cx)?,
                ty: ty.encode(cx)?,
            },
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTupleTargetBinding>> for sifr_ir::HirTupleTargetBinding {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTupleTargetBinding>> {
        let value = match self {
            sifr_ir::HirTupleTargetBinding::Name(v0) => {
                wire::HirTupleTargetBinding::Name(v0.encode(cx)?)
            }
            sifr_ir::HirTupleTargetBinding::Field { object, field } => {
                wire::HirTupleTargetBinding::Field {
                    object: object.encode(cx)?,
                    field: field.encode(cx)?,
                }
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTupleTarget>> for sifr_ir::HirTupleTarget {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTupleTarget>> {
        let value = wire::HirTupleTarget {
            binding: self.binding.encode(cx)?,
            ty: self.ty.encode(cx)?,
            rebind_existing: self.rebind_existing.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonRecordExpansion>> for sifr_ir::PythonRecordExpansion {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonRecordExpansion>> {
        let value = wire::PythonRecordExpansion {
            span: self.span.encode(cx)?,
            fields: self.fields.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
