// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::PythonTargetPath>> for sifr_ir::PythonTargetPath {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonTargetPath>> {
        let value = wire::PythonTargetPath {
            segments: self.segments.encode(cx)?,
            span: self.span.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonInteropDecoratorKind>> for sifr_ir::PythonInteropDecoratorKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonInteropDecoratorKind>> {
        let value = match self {
            sifr_ir::PythonInteropDecoratorKind::Function => {
                wire::PythonInteropDecoratorKind::Function
            }
            sifr_ir::PythonInteropDecoratorKind::Coroutine => {
                wire::PythonInteropDecoratorKind::Coroutine
            }
            sifr_ir::PythonInteropDecoratorKind::Opaque => wire::PythonInteropDecoratorKind::Opaque,
            sifr_ir::PythonInteropDecoratorKind::Attribute => {
                wire::PythonInteropDecoratorKind::Attribute
            }
            sifr_ir::PythonInteropDecoratorKind::Item => wire::PythonInteropDecoratorKind::Item,
            sifr_ir::PythonInteropDecoratorKind::ContextEnter => {
                wire::PythonInteropDecoratorKind::ContextEnter
            }
            sifr_ir::PythonInteropDecoratorKind::ContextExit => {
                wire::PythonInteropDecoratorKind::ContextExit
            }
            sifr_ir::PythonInteropDecoratorKind::ContextAsyncEnter => {
                wire::PythonInteropDecoratorKind::ContextAsyncEnter
            }
            sifr_ir::PythonInteropDecoratorKind::ContextAsyncExit => {
                wire::PythonInteropDecoratorKind::ContextAsyncExit
            }
            sifr_ir::PythonInteropDecoratorKind::Callback => {
                wire::PythonInteropDecoratorKind::Callback
            }
            sifr_ir::PythonInteropDecoratorKind::Buffer => wire::PythonInteropDecoratorKind::Buffer,
            sifr_ir::PythonInteropDecoratorKind::Arrow => wire::PythonInteropDecoratorKind::Arrow,
            sifr_ir::PythonInteropDecoratorKind::Dlpack => wire::PythonInteropDecoratorKind::Dlpack,
            sifr_ir::PythonInteropDecoratorKind::DlpackStream => {
                wire::PythonInteropDecoratorKind::DlpackStream
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonBufferAccess>> for sifr_ir::PythonBufferAccess {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonBufferAccess>> {
        let value = match self {
            sifr_ir::PythonBufferAccess::Read => wire::PythonBufferAccess::Read,
            sifr_ir::PythonBufferAccess::Write => wire::PythonBufferAccess::Write,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonBufferLayout>> for sifr_ir::PythonBufferLayout {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonBufferLayout>> {
        let value = match self {
            sifr_ir::PythonBufferLayout::Any => wire::PythonBufferLayout::Any,
            sifr_ir::PythonBufferLayout::CContiguous => wire::PythonBufferLayout::CContiguous,
            sifr_ir::PythonBufferLayout::FContiguous => wire::PythonBufferLayout::FContiguous,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonBufferDeclaration>> for sifr_ir::PythonBufferDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonBufferDeclaration>> {
        let value = wire::PythonBufferDeclaration {
            element_type: self.element_type.encode(cx)?,
            access: self.access.encode(cx)?,
            layout: self.layout.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonArrowSchemaMode>> for sifr_ir::PythonArrowSchemaMode {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonArrowSchemaMode>> {
        let value = match self {
            sifr_ir::PythonArrowSchemaMode::Omitted => wire::PythonArrowSchemaMode::Omitted,
            sifr_ir::PythonArrowSchemaMode::Parameter { name, span } => {
                wire::PythonArrowSchemaMode::Parameter {
                    name: name.encode(cx)?,
                    span: span.encode(cx)?,
                }
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonArrowDeclaration>> for sifr_ir::PythonArrowDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonArrowDeclaration>> {
        let value = wire::PythonArrowDeclaration {
            kind: self.kind.encode(cx)?,
            schema: self.schema.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonDlpackDevice>> for sifr_ir::PythonDlpackDevice {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonDlpackDevice>> {
        let value = match self {
            sifr_ir::PythonDlpackDevice::Cpu => wire::PythonDlpackDevice::Cpu,
            sifr_ir::PythonDlpackDevice::Cuda => wire::PythonDlpackDevice::Cuda,
            sifr_ir::PythonDlpackDevice::Any => wire::PythonDlpackDevice::Any,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonDlpackStreamMode>> for sifr_ir::PythonDlpackStreamMode {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonDlpackStreamMode>> {
        let value = match self {
            sifr_ir::PythonDlpackStreamMode::None => wire::PythonDlpackStreamMode::None,
            sifr_ir::PythonDlpackStreamMode::Parameter { name, span } => {
                wire::PythonDlpackStreamMode::Parameter {
                    name: name.encode(cx)?,
                    span: span.encode(cx)?,
                }
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonDlpackDeclaration>> for sifr_ir::PythonDlpackDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonDlpackDeclaration>> {
        let value = wire::PythonDlpackDeclaration {
            device: self.device.encode(cx)?,
            stream: self.stream.encode(cx)?,
            element_type: self.element_type.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonInteropEffect>> for sifr_ir::PythonInteropEffect {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonInteropEffect>> {
        let value = match self {
            sifr_ir::PythonInteropEffect::BlockingIo => wire::PythonInteropEffect::BlockingIo,
            sifr_ir::PythonInteropEffect::Async => wire::PythonInteropEffect::Async,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonCleanupPolicy>> for sifr_ir::PythonCleanupPolicy {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonCleanupPolicy>> {
        let value = match self {
            sifr_ir::PythonCleanupPolicy::Drop => wire::PythonCleanupPolicy::Drop,
            sifr_ir::PythonCleanupPolicy::Close => wire::PythonCleanupPolicy::Close,
            sifr_ir::PythonCleanupPolicy::AsyncClose => wire::PythonCleanupPolicy::AsyncClose,
            sifr_ir::PythonCleanupPolicy::Context => wire::PythonCleanupPolicy::Context,
            sifr_ir::PythonCleanupPolicy::AsyncContext => wire::PythonCleanupPolicy::AsyncContext,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonParameterKind>> for sifr_ir::PythonParameterKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonParameterKind>> {
        let value = match self {
            sifr_ir::PythonParameterKind::Positional => wire::PythonParameterKind::Positional,
            sifr_ir::PythonParameterKind::KeywordOnly => wire::PythonParameterKind::KeywordOnly,
            sifr_ir::PythonParameterKind::PositionalVariadic => {
                wire::PythonParameterKind::PositionalVariadic
            }
            sifr_ir::PythonParameterKind::KeywordVariadic => {
                wire::PythonParameterKind::KeywordVariadic
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonCallbackLifetime>> for sifr_ir::PythonCallbackLifetime {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonCallbackLifetime>> {
        let value = match self {
            sifr_ir::PythonCallbackLifetime::Call => wire::PythonCallbackLifetime::Call,
            sifr_ir::PythonCallbackLifetime::Result => wire::PythonCallbackLifetime::Result,
            sifr_ir::PythonCallbackLifetime::Receiver => wire::PythonCallbackLifetime::Receiver,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonCallbackDispatch>> for sifr_ir::PythonCallbackDispatch {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonCallbackDispatch>> {
        let value = match self {
            sifr_ir::PythonCallbackDispatch::Current => wire::PythonCallbackDispatch::Current,
            sifr_ir::PythonCallbackDispatch::Foreign => wire::PythonCallbackDispatch::Foreign,
            sifr_ir::PythonCallbackDispatch::Asyncio => wire::PythonCallbackDispatch::Asyncio,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonCallbackConcurrency>> for sifr_ir::PythonCallbackConcurrency {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonCallbackConcurrency>> {
        let value = match self {
            sifr_ir::PythonCallbackConcurrency::Serial => wire::PythonCallbackConcurrency::Serial,
            sifr_ir::PythonCallbackConcurrency::Parallel => {
                wire::PythonCallbackConcurrency::Parallel
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonCallbackDeclaration>> for sifr_ir::PythonCallbackDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonCallbackDeclaration>> {
        let value = wire::PythonCallbackDeclaration {
            parameter_name: self.parameter_name.encode(cx)?,
            span: self.span.encode(cx)?,
            lifetime: self.lifetime.encode(cx)?,
            dispatch: self.dispatch.encode(cx)?,
            concurrency: self.concurrency.encode(cx)?,
            argument_types: self.argument_types.encode(cx)?,
            argument_conventions: self.argument_conventions.encode(cx)?,
            success_type: self.success_type.encode(cx)?,
            handler_error_type: self.handler_error_type.encode(cx)?,
            is_async: self.is_async.encode(cx)?,
            owner_class: self.owner_class.encode(cx)?,
            owner_cleanup: self.owner_cleanup.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonInteropParameter>> for sifr_ir::PythonInteropParameter {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonInteropParameter>> {
        let value = wire::PythonInteropParameter {
            name: self.name.encode(cx)?,
            kind: self.kind.encode(cx)?,
            has_default: self.has_default.encode(cx)?,
            omit_when_absent: self.omit_when_absent.encode(cx)?,
            span: self.span.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::PythonInteropDeclaration>> for sifr_ir::PythonInteropDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonInteropDeclaration>> {
        let value = wire::PythonInteropDeclaration {
            kind: self.kind.encode(cx)?,
            target: self.target.encode(cx)?,
            span: self.span.encode(cx)?,
            effect: self.effect.encode(cx)?,
            cleanup: self.cleanup.encode(cx)?,
            consumes_receiver: self.consumes_receiver.encode(cx)?,
            parameters: self.parameters.encode(cx)?,
            required_import_root: self.required_import_root.encode(cx)?,
            callbacks: self.callbacks.encode(cx)?,
            buffer: self.buffer.encode(cx)?,
            arrow: self.arrow.encode(cx)?,
            dlpack: self.dlpack.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
