// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::RustTargetPath>> for sifr_ir::RustTargetPath {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustTargetPath>> {
        let value = wire::RustTargetPath {
            segments: self.segments.encode(cx)?,
            span: self.span.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustInteropDecoratorKind>> for sifr_ir::RustInteropDecoratorKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustInteropDecoratorKind>> {
        let value = match self {
            sifr_ir::RustInteropDecoratorKind::Function => wire::RustInteropDecoratorKind::Function,
            sifr_ir::RustInteropDecoratorKind::Opaque => wire::RustInteropDecoratorKind::Opaque,
            sifr_ir::RustInteropDecoratorKind::Async => wire::RustInteropDecoratorKind::Async,
            sifr_ir::RustInteropDecoratorKind::Callback => wire::RustInteropDecoratorKind::Callback,
            sifr_ir::RustInteropDecoratorKind::Structural => {
                wire::RustInteropDecoratorKind::Structural
            }
            sifr_ir::RustInteropDecoratorKind::ZeroCopy => wire::RustInteropDecoratorKind::ZeroCopy,
            sifr_ir::RustInteropDecoratorKind::View => wire::RustInteropDecoratorKind::View,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustInteropEffect>> for sifr_ir::RustInteropEffect {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustInteropEffect>> {
        let value = match self {
            sifr_ir::RustInteropEffect::Sync => wire::RustInteropEffect::Sync,
            sifr_ir::RustInteropEffect::Async => wire::RustInteropEffect::Async,
            sifr_ir::RustInteropEffect::BlockingIo => wire::RustInteropEffect::BlockingIo,
            sifr_ir::RustInteropEffect::CpuHeavy => wire::RustInteropEffect::CpuHeavy,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustInteropAbiRequirements>> for sifr_ir::RustInteropAbiRequirements {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustInteropAbiRequirements>> {
        let value = wire::RustInteropAbiRequirements {
            async_boundary: self.async_boundary.encode(cx)?,
            opaque_handle: self.opaque_handle.encode(cx)?,
            zero_copy: self.zero_copy.encode(cx)?,
            view: self.view.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustInteropArgument>> for sifr_ir::RustInteropArgument {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustInteropArgument>> {
        let value = wire::RustInteropArgument {
            name: self.name.encode(cx)?,
            value: self.value.encode(cx)?,
            span: self.span.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustInteropValue>> for sifr_ir::RustInteropValue {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustInteropValue>> {
        let value = match self {
            sifr_ir::RustInteropValue::Boolean(v0) => {
                wire::RustInteropValue::Boolean(v0.encode(cx)?)
            }
            sifr_ir::RustInteropValue::Symbol(v0) => wire::RustInteropValue::Symbol(v0.encode(cx)?),
            sifr_ir::RustInteropValue::Integer(v0) => {
                wire::RustInteropValue::Integer(v0.encode(cx)?)
            }
            sifr_ir::RustInteropValue::IntegerList(v0) => {
                wire::RustInteropValue::IntegerList(v0.encode(cx)?)
            }
            sifr_ir::RustInteropValue::PolicyCall {
                name,
                argument,
                span,
            } => wire::RustInteropValue::PolicyCall {
                name: name.encode(cx)?,
                argument: argument.encode(cx)?,
                span: span.encode(cx)?,
            },
            sifr_ir::RustInteropValue::TargetPath(v0) => {
                wire::RustInteropValue::TargetPath(v0.encode(cx)?)
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustCallbackBackpressure>> for sifr_ir::RustCallbackBackpressure {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustCallbackBackpressure>> {
        let value = match self {
            sifr_ir::RustCallbackBackpressure::Direct => wire::RustCallbackBackpressure::Direct,
            sifr_ir::RustCallbackBackpressure::Bounded(v0) => {
                wire::RustCallbackBackpressure::Bounded(v0.encode(cx)?)
            }
            sifr_ir::RustCallbackBackpressure::Unbounded => {
                wire::RustCallbackBackpressure::Unbounded
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustCallbackOverflow>> for sifr_ir::RustCallbackOverflow {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustCallbackOverflow>> {
        let value = match self {
            sifr_ir::RustCallbackOverflow::Error => wire::RustCallbackOverflow::Error,
            sifr_ir::RustCallbackOverflow::DropOldest => wire::RustCallbackOverflow::DropOldest,
            sifr_ir::RustCallbackOverflow::DropNewest => wire::RustCallbackOverflow::DropNewest,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustCallbackShutdown>> for sifr_ir::RustCallbackShutdown {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustCallbackShutdown>> {
        let value = match self {
            sifr_ir::RustCallbackShutdown::Drain => wire::RustCallbackShutdown::Drain,
            sifr_ir::RustCallbackShutdown::Cancel => wire::RustCallbackShutdown::Cancel,
            sifr_ir::RustCallbackShutdown::DetachForbidden => {
                wire::RustCallbackShutdown::DetachForbidden
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustThreadsafeCallbackContract>>
    for sifr_ir::RustThreadsafeCallbackContract
{
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustThreadsafeCallbackContract>> {
        let value = wire::RustThreadsafeCallbackContract {
            backpressure: self.backpressure.encode(cx)?,
            overflow: self.overflow.encode(cx)?,
            shutdown: self.shutdown.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::RustInteropDeclaration>> for sifr_ir::RustInteropDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::RustInteropDeclaration>> {
        let value = wire::RustInteropDeclaration {
            kind: self.kind.encode(cx)?,
            target: self.target.encode(cx)?,
            arguments: self.arguments.encode(cx)?,
            span: self.span.encode(cx)?,
            effect: self.effect.encode(cx)?,
            abi_requirements: self.abi_requirements.encode(cx)?,
            consumes_receiver: self.consumes_receiver.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
