// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
pub(super) fn project(
    defs: &sifr_lowering::ExternalDefs,
    module: &str,
    cx: &mut Encoder,
) -> Result<wire::Ref<wire::SemanticExports>> {
    let value = wire::SemanticExports {
        functions: scoped_map(
            defs.functions.get(module),
            defs.generic_functions.get(module),
            wire::DeclarationKind::Function,
            cx,
        )?,
        compiler_intrinsics: defs
            .compiler_intrinsics
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        classes: scoped_types(
            defs.classes.get(module),
            defs.class_type_params.get(module),
            cx,
        )?,
        generic_type_aliases: defs
            .generic_type_aliases
            .get(module)
            .cloned()
            .unwrap_or_default()
            .iter()
            .map(|(name, (params, ty))| {
                cx.with_owner(name, params, wire::DeclarationKind::Alias, |cx| {
                    Ok((name.encode(cx)?, (params.encode(cx)?, ty.encode(cx)?)))
                })
            })
            .collect::<Result<_>>()?,
        class_instance_methods: defs
            .class_instance_methods
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        rust_consuming_methods: defs
            .rust_consuming_methods
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        rust_opaque_classes: defs
            .rust_opaque_classes
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        rust_structural_classes: defs
            .rust_structural_classes
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        class_type_params: defs
            .class_type_params
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        structural_methods: defs
            .structural_methods_for(module)
            .into_iter()
            .flat_map(|m| m.iter())
            .map(|(name, methods)| Ok((name.encode(cx)?, methods.encode(cx)?)))
            .collect::<Result<_>>()?,
        class_field_defaults: scoped_map(
            defs.class_field_defaults.get(module),
            defs.class_type_params.get(module),
            wire::DeclarationKind::Class,
            cx,
        )?,
        declaration_metadata: defs
            .declaration_metadata
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        class_adapter_providers: defs
            .class_adapter_providers
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        class_adapter_markers: defs
            .class_adapter_markers
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        attached_api_sets: defs
            .attached_api_sets
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        attached_apis: defs
            .attached_apis
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        class_adapter_selections: defs
            .class_adapter_selections
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        descriptor_functions: defs
            .descriptor_functions
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        declaration_descriptors: defs
            .declaration_descriptors
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        applied_adapter_metadata: defs
            .applied_adapter_metadata
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        const_functions: defs
            .const_functions
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        specialization_requests: defs
            .specialization_requests
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        specialization_outputs: defs
            .specialization_outputs
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        json_integer_boundary_requests: defs
            .json_integer_boundary_requests
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        constants: defs
            .constants
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        constant_integer_values: defs
            .constant_integer_values
            .get(module)
            .cloned()
            .unwrap_or_default()
            .iter()
            .map(|(k, v)| Ok((k.encode(cx)?, v.to_string().encode(cx)?)))
            .collect::<Result<_>>()?,
        error_types: defs
            .error_types
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        type_param_bounds: defs
            .type_param_bounds
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        generic_functions: defs
            .generic_functions
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        function_varargs: defs
            .function_varargs
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        function_python_call_shapes: defs
            .function_python_call_shapes
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        rust_threadsafe_callback_targets: defs
            .rust_threadsafe_callback_targets
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        function_workloads: defs
            .function_workloads
            .get(module)
            .cloned()
            .unwrap_or_default()
            .encode(cx)?,
        function_defaults: scoped_map(
            defs.function_defaults.get(module),
            defs.generic_functions.get(module),
            wire::DeclarationKind::Function,
            cx,
        )?,
    };
    cx.records.intern(&value)
}
fn scoped_map<T: Encode<U>, U>(
    values: Option<&std::collections::HashMap<String, T>>,
    parameters: Option<&std::collections::HashMap<String, Vec<String>>>,
    kind: wire::DeclarationKind,
    cx: &mut Encoder,
) -> Result<std::collections::BTreeMap<wire::Ref<wire::Text>, U>> {
    let mut entries = values
        .into_iter()
        .flat_map(|v| v.iter())
        .collect::<Vec<_>>();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    entries
        .into_iter()
        .map(|(name, value)| {
            let params = parameters
                .and_then(|m| m.get(name))
                .map(Vec::as_slice)
                .unwrap_or(&[]);
            cx.with_owner(name, params, kind.clone(), |cx| {
                Ok((name.encode(cx)?, value.encode(cx)?))
            })
        })
        .collect()
}
impl Encode<wire::Ref<wire::StructuralMethodExport>> for sifr_lowering::StructuralMethodExport {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StructuralMethodExport>> {
        let value = wire::StructuralMethodExport {
            handler_target: self.handler_target.encode(cx)?,
            name: self.name.encode(cx)?,
            params: self.params.encode(cx)?,
            return_type: self.return_type.encode(cx)?,
            is_async: self.is_async.encode(cx)?,
            method_kind: self.method_kind.encode(cx)?,
            receiver: self.receiver.encode(cx)?,
        };
        cx.records.intern(&value)
    }
}
fn scoped_types(
    values: Option<&std::collections::HashMap<String, sifr_type_system::Type>>,
    parameters: Option<&std::collections::HashMap<String, Vec<String>>>,
    cx: &mut Encoder,
) -> Result<std::collections::BTreeMap<wire::Ref<wire::Text>, wire::Ref<wire::Type>>> {
    let mut entries = values
        .into_iter()
        .flat_map(|v| v.iter())
        .collect::<Vec<_>>();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    entries
        .into_iter()
        .map(|(name, value)| {
            let params = parameters
                .and_then(|m| m.get(name))
                .map(Vec::as_slice)
                .unwrap_or(&[]);
            let kind = match value {
                sifr_type_system::Type::Enum { .. } => wire::DeclarationKind::Enum,
                sifr_type_system::Type::Protocol { .. } => wire::DeclarationKind::Protocol,
                sifr_type_system::Type::Newtype { .. } => wire::DeclarationKind::Newtype,
                sifr_type_system::Type::Alias { .. } => wire::DeclarationKind::Alias,
                _ => wire::DeclarationKind::Class,
            };
            cx.with_owner(name, params, kind, |cx| {
                Ok((name.encode(cx)?, value.encode(cx)?))
            })
        })
        .collect()
}
