// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::DeclarationMetadataTargetKind>>
    for sifr_ir::DeclarationMetadataTargetKind
{
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::DeclarationMetadataTargetKind>> {
        let value = match self {
            sifr_ir::DeclarationMetadataTargetKind::Type => {
                wire::DeclarationMetadataTargetKind::Type
            }
            sifr_ir::DeclarationMetadataTargetKind::Field => {
                wire::DeclarationMetadataTargetKind::Field
            }
            sifr_ir::DeclarationMetadataTargetKind::EnumVariant => {
                wire::DeclarationMetadataTargetKind::EnumVariant
            }
            sifr_ir::DeclarationMetadataTargetKind::Function => {
                wire::DeclarationMetadataTargetKind::Function
            }
            sifr_ir::DeclarationMetadataTargetKind::Method => {
                wire::DeclarationMetadataTargetKind::Method
            }
            sifr_ir::DeclarationMetadataTargetKind::Parameter => {
                wire::DeclarationMetadataTargetKind::Parameter
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::TypedDeclarationMetadata>> for sifr_ir::TypedDeclarationMetadata {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::TypedDeclarationMetadata>> {
        let value = wire::TypedDeclarationMetadata {
            owner: self.owner.encode(cx)?,
            target_kind: self.target_kind.encode(cx)?,
            target_name: self.target_name.encode(cx)?,
            key: self.key.encode(cx)?,
            value_type: self.value_type.encode(cx)?,
            value: self.value.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::ConstSpecializationRequest>> for sifr_ir::ConstSpecializationRequest {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ConstSpecializationRequest>> {
        let value = wire::ConstSpecializationRequest {
            owner: self.owner.encode(cx)?,
            package_module: self.package_module.encode(cx)?,
            function: self.function.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::DeclarationDescriptorKind>> for sifr_ir::DeclarationDescriptorKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::DeclarationDescriptorKind>> {
        let value = match self {
            sifr_ir::DeclarationDescriptorKind::Field => wire::DeclarationDescriptorKind::Field,
            sifr_ir::DeclarationDescriptorKind::Class => wire::DeclarationDescriptorKind::Class,
            sifr_ir::DeclarationDescriptorKind::Method => wire::DeclarationDescriptorKind::Method,
            sifr_ir::DeclarationDescriptorKind::Type => wire::DeclarationDescriptorKind::Type,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::ClassAdapterProviderDeclaration>>
    for sifr_ir::ClassAdapterProviderDeclaration
{
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ClassAdapterProviderDeclaration>> {
        let value = wire::ClassAdapterProviderDeclaration {
            module: self.module.encode(cx)?,
            function: self.function.encode(cx)?,
            descriptor_module: self.descriptor_module.encode(cx)?,
            descriptor_symbol: self.descriptor_symbol.encode(cx)?,
            descriptor_type: self.descriptor_type.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::ClassAdapterMarkerDeclaration>>
    for sifr_ir::ClassAdapterMarkerDeclaration
{
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ClassAdapterMarkerDeclaration>> {
        let value = wire::ClassAdapterMarkerDeclaration {
            module: self.module.encode(cx)?,
            symbol: self.symbol.encode(cx)?,
            provider_module: self.provider_module.encode(cx)?,
            provider_function: self.provider_function.encode(cx)?,
            descriptor_type: self.descriptor_type.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AttachedApiSetIdentity>> for sifr_ir::AttachedApiSetIdentity {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AttachedApiSetIdentity>> {
        let value = wire::AttachedApiSetIdentity {
            module: self.module.encode(cx)?,
            symbol: self.symbol.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AttachedApiSetDeclaration>> for sifr_ir::AttachedApiSetDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AttachedApiSetDeclaration>> {
        let value = wire::AttachedApiSetDeclaration {
            identity: self.identity.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AttachedApiReceiver>> for sifr_ir::AttachedApiReceiver {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AttachedApiReceiver>> {
        let value = match self {
            sifr_ir::AttachedApiReceiver::Type => wire::AttachedApiReceiver::Type,
            sifr_ir::AttachedApiReceiver::Immutable => wire::AttachedApiReceiver::Immutable,
            sifr_ir::AttachedApiReceiver::Mutable => wire::AttachedApiReceiver::Mutable,
            sifr_ir::AttachedApiReceiver::Owned => wire::AttachedApiReceiver::Owned,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AttachedApiDeclaration>> for sifr_ir::AttachedApiDeclaration {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AttachedApiDeclaration>> {
        let value = wire::AttachedApiDeclaration {
            module: self.module.encode(cx)?,
            function: self.function.encode(cx)?,
            set: self.set.encode(cx)?,
            public_name: self.public_name.encode(cx)?,
            receiver: self.receiver.encode(cx)?,
            owner_type_param: self.owner_type_param.encode(cx)?,
            type_params: self.type_params.encode(cx)?,
            type_param_bounds: self.type_param_bounds.encode(cx)?,
            function_type: self.function_type.encode(cx)?,
            defaults: self.defaults.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::ClassAdapterSelection>> for sifr_ir::ClassAdapterSelection {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ClassAdapterSelection>> {
        let value = wire::ClassAdapterSelection {
            owner: self.owner.encode(cx)?,
            provider_module: self.provider_module.encode(cx)?,
            provider_function: self.provider_function.encode(cx)?,
            descriptor_type: self.descriptor_type.encode(cx)?,
            marker_identities: self.marker_identities.encode(cx)?,
            data_parent: self.data_parent.encode(cx)?,
            field_plans: self.field_plans.encode(cx)?,
            handler_plans: self.handler_plans.encode(cx)?,
            attached_api_set: self.attached_api_set.encode(cx)?,
            adapter_invocation_identity: self.adapter_invocation_identity.encode(cx)?,
            post_adapter_identity: self.post_adapter_identity.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AdapterHandlerPlan>> for sifr_ir::AdapterHandlerPlan {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AdapterHandlerPlan>> {
        let value = wire::AdapterHandlerPlan {
            callable: self.callable.encode(cx)?,
            descriptor_type: self.descriptor_type.encode(cx)?,
            descriptor_value: self.descriptor_value.encode(cx)?,
            descriptor_origin: self.descriptor_origin.encode(cx)?,
            descriptor_range: self.descriptor_range.encode(cx)?,
            declaration_order: self.declaration_order.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AdapterFieldPlan>> for sifr_ir::AdapterFieldPlan {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AdapterFieldPlan>> {
        let value = wire::AdapterFieldPlan {
            identity: self.identity.encode(cx)?,
            name: self.name.encode(cx)?,
            declared_type: self.declared_type.encode(cx)?,
            default: self.default.encode(cx)?,
            validation_policy: self.validation_policy.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AdapterFieldDefault>> for sifr_ir::AdapterFieldDefault {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AdapterFieldDefault>> {
        let value = match self {
            sifr_ir::AdapterFieldDefault::Required => wire::AdapterFieldDefault::Required,
            sifr_ir::AdapterFieldDefault::Const(v0) => {
                wire::AdapterFieldDefault::Const(v0.encode(cx)?)
            }
            sifr_ir::AdapterFieldDefault::Factory(v0) => {
                wire::AdapterFieldDefault::Factory(v0.encode(cx)?)
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::DeclarationDescriptorFunction>>
    for sifr_ir::DeclarationDescriptorFunction
{
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::DeclarationDescriptorFunction>> {
        let value = wire::DeclarationDescriptorFunction {
            module: self.module.encode(cx)?,
            function: self.function.encode(cx)?,
            provider_module: self.provider_module.encode(cx)?,
            provider_function: self.provider_function.encode(cx)?,
            descriptor_type: self.descriptor_type.encode(cx)?,
            return_type: self.return_type.encode(cx)?,
            kind: self.kind.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::CallableIdentity>> for sifr_ir::CallableIdentity {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::CallableIdentity>> {
        let value = wire::CallableIdentity {
            module: self.module.encode(cx)?,
            owner: self.owner.encode(cx)?,
            symbol: self.symbol.encode(cx)?,
            generic_arguments: self.generic_arguments.encode(cx)?,
            signature: self.signature.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::TypedDeclarationDescriptor>> for sifr_ir::TypedDeclarationDescriptor {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::TypedDeclarationDescriptor>> {
        let value = wire::TypedDeclarationDescriptor {
            owner: self.owner.encode(cx)?,
            target_kind: self.target_kind.encode(cx)?,
            target_identity: self.target_identity.encode(cx)?,
            target_callable: self.target_callable.encode(cx)?,
            provider_module: self.provider_module.encode(cx)?,
            provider_function: self.provider_function.encode(cx)?,
            value_type: self.value_type.encode(cx)?,
            value: self.value.encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::AppliedAdapterMetadata>> for sifr_ir::AppliedAdapterMetadata {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::AppliedAdapterMetadata>> {
        let value = wire::AppliedAdapterMetadata {
            owner: self.owner.encode(cx)?,
            target_kind: self.target_kind.encode(cx)?,
            target_name: self.target_name.encode(cx)?,
            key: self.key.encode(cx)?,
            value_type: self.value_type.encode(cx)?,
            value: self.value.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::StaticProgramValue>> for sifr_ir::StaticProgramValue {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StaticProgramValue>> {
        let value = match self {
            sifr_ir::StaticProgramValue::None => wire::StaticProgramValue::None,
            sifr_ir::StaticProgramValue::Bool(v0) => wire::StaticProgramValue::Bool(v0.encode(cx)?),
            sifr_ir::StaticProgramValue::Integer(v0) => {
                wire::StaticProgramValue::Integer(v0.encode(cx)?)
            }
            sifr_ir::StaticProgramValue::FloatBits(v0) => {
                wire::StaticProgramValue::FloatBits(v0.encode(cx)?)
            }
            sifr_ir::StaticProgramValue::String(v0) => {
                wire::StaticProgramValue::String(v0.encode(cx)?)
            }
            sifr_ir::StaticProgramValue::Bytes(v0) => {
                wire::StaticProgramValue::Bytes(v0.encode(cx)?)
            }
            sifr_ir::StaticProgramValue::Tuple(v0) => {
                wire::StaticProgramValue::Tuple(v0.encode(cx)?)
            }
            sifr_ir::StaticProgramValue::List(v0) => wire::StaticProgramValue::List(v0.encode(cx)?),
            sifr_ir::StaticProgramValue::Record(v0) => {
                wire::StaticProgramValue::Record(v0.encode(cx)?)
            }
            sifr_ir::StaticProgramValue::CallableIdentity(v0) => {
                wire::StaticProgramValue::CallableIdentity(v0.encode(cx)?)
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::StaticSpecializationOutput>> for sifr_ir::StaticSpecializationOutput {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StaticSpecializationOutput>> {
        let value = wire::StaticSpecializationOutput {
            owner: self.owner.encode(cx)?,
            package_module: self.package_module.encode(cx)?,
            function: self.function.encode(cx)?,
            canonical_value: self.canonical_value.encode(cx)?,
            value: self.value.encode(cx)?,
            program_identity: self.program_identity.encode(cx)?,
            structural_contract_version: self.structural_contract_version.encode(cx)?,
            method_slots: self.method_slots.encode(cx)?,
            method_slot_context: self.method_slot_context.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::StaticMethodSlotContext>> for sifr_ir::StaticMethodSlotContext {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StaticMethodSlotContext>> {
        let value = match self {
            sifr_ir::StaticMethodSlotContext::None => wire::StaticMethodSlotContext::None,
            sifr_ir::StaticMethodSlotContext::Shared(v0) => {
                wire::StaticMethodSlotContext::Shared(v0.encode(cx)?)
            }
            sifr_ir::StaticMethodSlotContext::Mutable(v0) => {
                wire::StaticMethodSlotContext::Mutable(v0.encode(cx)?)
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::StaticMethodSlotInputRole>> for sifr_ir::StaticMethodSlotInputRole {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StaticMethodSlotInputRole>> {
        let value = match self {
            sifr_ir::StaticMethodSlotInputRole::Value => wire::StaticMethodSlotInputRole::Value,
            sifr_ir::StaticMethodSlotInputRole::Receiver => {
                wire::StaticMethodSlotInputRole::Receiver
            }
            sifr_ir::StaticMethodSlotInputRole::ReceiverAndValue => {
                wire::StaticMethodSlotInputRole::ReceiverAndValue
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::StaticMethodSlot>> for sifr_ir::StaticMethodSlot {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StaticMethodSlot>> {
        let value = wire::StaticMethodSlot {
            owner_identity: self.owner_identity.encode(cx)?,
            owner_type: self.owner_type.encode(cx)?,
            name: self.name.encode(cx)?,
            hir_name: self.hir_name.encode(cx)?,
            method_kind: self.method_kind.encode(cx)?,
            receiver: self.receiver.encode(cx)?,
            params: self.params.encode(cx)?,
            return_type: self.return_type.encode(cx)?,
            is_async: self.is_async.encode(cx)?,
            input_role: self.input_role.encode(cx)?,
            input_type: self.input_type.encode(cx)?,
            output_type: self.output_type.encode(cx)?,
            context_type: self.context_type.encode(cx)?,
            context_mutable: self.context_mutable.encode(cx)?,
            descriptor_type: self.descriptor_type.encode(cx)?,
            descriptor_value: self.descriptor_value.encode(cx)?,
            descriptor_origin: self.descriptor_origin.encode(cx)?,
            descriptor_range: self.descriptor_range.encode(cx)?,
            declaration_order: self.declaration_order.encode(cx)?,
            is_fallible: self.is_fallible.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::StaticMethodParam>> for sifr_ir::StaticMethodParam {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::StaticMethodParam>> {
        let value = wire::StaticMethodParam {
            name: self.name.encode(cx)?,
            ty: self.ty.encode(cx)?,
            keyword_only: self.keyword_only.encode(cx)?,
            convention: self.convention.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::JsonIntegerBoundaryRequest>> for sifr_ir::JsonIntegerBoundaryRequest {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::JsonIntegerBoundaryRequest>> {
        let value = wire::JsonIntegerBoundaryRequest {
            owner: self.owner.encode(cx)?,
            field: self.field.encode(cx)?,
            profile: self.profile.encode(cx)?,
            representation: self.representation.encode(cx)?,
            static_minimum: self
                .static_minimum
                .as_ref()
                .map(ToString::to_string)
                .encode(cx)?,
            static_maximum: self
                .static_maximum
                .as_ref()
                .map(ToString::to_string)
                .encode(cx)?,
            range: self.range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
