// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::HirSqlQueryAdapter>> for sifr_ir::HirSqlQueryAdapter {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlQueryAdapter>> {
        let value = match self {
            sifr_ir::HirSqlQueryAdapter::ExpectAtMostOne => {
                wire::HirSqlQueryAdapter::ExpectAtMostOne
            }
            sifr_ir::HirSqlQueryAdapter::First => wire::HirSqlQueryAdapter::First,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlEffectKind>> for sifr_ir::HirSqlEffectKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlEffectKind>> {
        let value = match self {
            sifr_ir::HirSqlEffectKind::Read => wire::HirSqlEffectKind::Read,
            sifr_ir::HirSqlEffectKind::Write => wire::HirSqlEffectKind::Write,
            sifr_ir::HirSqlEffectKind::ReadWrite => wire::HirSqlEffectKind::ReadWrite,
            sifr_ir::HirSqlEffectKind::SchemaChange => wire::HirSqlEffectKind::SchemaChange,
            sifr_ir::HirSqlEffectKind::SessionChange => wire::HirSqlEffectKind::SessionChange,
            sifr_ir::HirSqlEffectKind::TransactionControl => {
                wire::HirSqlEffectKind::TransactionControl
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlCardinality>> for sifr_ir::HirSqlCardinality {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlCardinality>> {
        let value = wire::HirSqlCardinality {
            empty: self.empty.encode(cx)?,
            minimum: self.minimum.encode(cx)?,
            maximum: self.maximum.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlEffectContract>> for sifr_ir::HirSqlEffectContract {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlEffectContract>> {
        let value = wire::HirSqlEffectContract {
            effect: self.effect.encode(cx)?,
            referenced_objects: self.referenced_objects.encode(cx)?,
            affected_objects: self.affected_objects.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlParameterSlot>> for sifr_ir::HirSqlParameterSlot {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlParameterSlot>> {
        let value = wire::HirSqlParameterSlot {
            slot: self.slot.encode(cx)?,
            ty: self.ty.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlQueryTemplate>> for sifr_ir::HirSqlQueryTemplate {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlQueryTemplate>> {
        let value = wire::HirSqlQueryTemplate {
            identity: self.identity.encode(cx)?,
            module: self.module.encode(cx)?,
            symbol: self.symbol.encode(cx)?,
            profile_identity: self.profile_identity.encode(cx)?,
            profile_fingerprint: self.profile_fingerprint.encode(cx)?,
            schema_fingerprint: self.schema_fingerprint.encode(cx)?,
            normalized_statement: self.normalized_statement.encode(cx)?,
            parameters: self.parameters.encode(cx)?,
            row_type: self.row_type.encode(cx)?,
            cardinality: self.cardinality.encode(cx)?,
            effects: self.effects.encode(cx)?,
            deterministic_order: self.deterministic_order.encode(cx)?,
            fragment_identities: self.fragment_identities.encode(cx)?,
            adapters: self.adapters.encode(cx)?,
            ty: self.ty.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlBoundQuery>> for sifr_ir::HirSqlBoundQuery {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlBoundQuery>> {
        let value = wire::HirSqlBoundQuery {
            template_identity: self.template_identity.encode(cx)?,
            profile_identity: self.profile_identity.encode(cx)?,
            profile_fingerprint: self.profile_fingerprint.encode(cx)?,
            schema_fingerprint: self.schema_fingerprint.encode(cx)?,
            captures: self.captures.encode(cx)?,
            cardinality: self.cardinality.encode(cx)?,
            effects: self.effects.encode(cx)?,
            ty: self.ty.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlExecutionMethod>> for sifr_ir::HirSqlExecutionMethod {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlExecutionMethod>> {
        let value = match self {
            sifr_ir::HirSqlExecutionMethod::Execute => wire::HirSqlExecutionMethod::Execute,
            sifr_ir::HirSqlExecutionMethod::FetchOne => wire::HirSqlExecutionMethod::FetchOne,
            sifr_ir::HirSqlExecutionMethod::FetchOptional => {
                wire::HirSqlExecutionMethod::FetchOptional
            }
            sifr_ir::HirSqlExecutionMethod::FetchAll { maximum_rows } => {
                wire::HirSqlExecutionMethod::FetchAll {
                    maximum_rows: maximum_rows.encode(cx)?,
                }
            }
            sifr_ir::HirSqlExecutionMethod::Stream => wire::HirSqlExecutionMethod::Stream,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlExecution>> for sifr_ir::HirSqlExecution {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlExecution>> {
        let value = wire::HirSqlExecution {
            query: self.query.encode(cx)?,
            method: self.method.encode(cx)?,
            runtime_cardinality: self.runtime_cardinality.encode(cx)?,
            runtime_effects: self.runtime_effects.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
