// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::HirSqlMigrationStepKind>> for sifr_ir::HirSqlMigrationStepKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlMigrationStepKind>> {
        let value = match self {
            sifr_ir::HirSqlMigrationStepKind::Ddl => wire::HirSqlMigrationStepKind::Ddl,
            sifr_ir::HirSqlMigrationStepKind::SqlData => wire::HirSqlMigrationStepKind::SqlData,
            sifr_ir::HirSqlMigrationStepKind::SifrData => wire::HirSqlMigrationStepKind::SifrData,
            sifr_ir::HirSqlMigrationStepKind::Assertion => wire::HirSqlMigrationStepKind::Assertion,
            sifr_ir::HirSqlMigrationStepKind::Backfill => wire::HirSqlMigrationStepKind::Backfill,
            sifr_ir::HirSqlMigrationStepKind::Transaction => {
                wire::HirSqlMigrationStepKind::Transaction
            }
            sifr_ir::HirSqlMigrationStepKind::RecoveryPoint => {
                wire::HirSqlMigrationStepKind::RecoveryPoint
            }
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlMigrationStep>> for sifr_ir::HirSqlMigrationStep {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlMigrationStep>> {
        let value = wire::HirSqlMigrationStep {
            migration_identity: self.migration_identity.encode(cx)?,
            parent_identity: self.parent_identity.encode(cx)?,
            step_identity: self.step_identity.encode(cx)?,
            input_state_identity: self.input_state_identity.encode(cx)?,
            output_state_identity: self.output_state_identity.encode(cx)?,
            input_plan_type: self.input_plan_type.encode(cx)?,
            output_plan_type: self.output_plan_type.encode(cx)?,
            callback_db_type: self.callback_db_type.encode(cx)?,
            referenced_objects: self.referenced_objects.encode(cx)?,
            affected_objects: self.affected_objects.encode(cx)?,
            kind: self.kind.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirSqlMigrationGraph>> for sifr_ir::HirSqlMigrationGraph {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirSqlMigrationGraph>> {
        let value = wire::HirSqlMigrationGraph {
            provider_family: self.provider_family.encode(cx)?,
            head: self.head.encode(cx)?,
            target_fingerprint: self.target_fingerprint.encode(cx)?,
            steps: self.steps.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
