// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::HirTemplateSegment>> for sifr_ir::HirTemplateSegment {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTemplateSegment>> {
        let value = wire::HirTemplateSegment {
            value: self.value.encode(cx)?,
            mappings: self.mappings.encode(cx)?,
            virtual_range: self.virtual_range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTemplateStaticMapping>> for sifr_ir::HirTemplateStaticMapping {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTemplateStaticMapping>> {
        let value = wire::HirTemplateStaticMapping {
            source_range: self.source_range.encode(cx)?,
            virtual_range: self.virtual_range.encode(cx)?,
            offsets: self.offsets.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTemplateOffsetMapping>> for sifr_ir::HirTemplateOffsetMapping {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTemplateOffsetMapping>> {
        let value = wire::HirTemplateOffsetMapping {
            source_range: self.source_range.encode(cx)?,
            virtual_range: self.virtual_range.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTemplateFormatSpec>> for sifr_ir::HirTemplateFormatSpec {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTemplateFormatSpec>> {
        let value = wire::HirTemplateFormatSpec {
            range: self.range.encode(cx)?,
            parts: self.parts.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTemplateFormatSpecPart>> for sifr_ir::HirTemplateFormatSpecPart {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTemplateFormatSpecPart>> {
        let value = match self {
            sifr_ir::HirTemplateFormatSpecPart::Literal(v0) => {
                wire::HirTemplateFormatSpecPart::Literal(v0.encode(cx)?)
            }
            sifr_ir::HirTemplateFormatSpecPart::Interpolation {
                value,
                clone_from_borrow,
                source_range,
                conversion,
                format_spec,
            } => wire::HirTemplateFormatSpecPart::Interpolation {
                value: value.encode(cx)?,
                clone_from_borrow: clone_from_borrow.encode(cx)?,
                source_range: source_range.encode(cx)?,
                conversion: conversion.encode(cx)?,
                format_spec: format_spec.encode(cx)?,
            },
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTemplateInterpolation>> for sifr_ir::HirTemplateInterpolation {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTemplateInterpolation>> {
        let value = wire::HirTemplateInterpolation {
            value: self.value.encode(cx)?,
            clone_from_borrow: self.clone_from_borrow.encode(cx)?,
            value_type: self.value_type.encode(cx)?,
            source_range: self.source_range.encode(cx)?,
            expression_range: self.expression_range.encode(cx)?,
            expression_source: self.expression_source.encode(cx)?,
            virtual_range: self.virtual_range.encode(cx)?,
            conversion: self.conversion.encode(cx)?,
            format_spec: self.format_spec.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
impl Encode<wire::Ref<wire::HirTemplateString>> for sifr_ir::HirTemplateString {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::HirTemplateString>> {
        let value = wire::HirTemplateString {
            source_range: self.source_range.encode(cx)?,
            virtual_source: self.virtual_source.encode(cx)?,
            segments: self.segments.encode(cx)?,
            interpolations: self.interpolations.encode(cx)?,
            ty: self.ty.encode(cx)?,
        };
        cx.records.intern(&value).map_err(Into::into)
    }
}
