// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.
use super::{Encode, Encoder, Result, wire};
impl Encode<wire::Ref<wire::PythonArrowKind>> for sifr_type_system::PythonArrowKind {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::PythonArrowKind>> {
        let value = match self {
            sifr_type_system::PythonArrowKind::Array => wire::PythonArrowKind::Array,
            sifr_type_system::PythonArrowKind::Schema => wire::PythonArrowKind::Schema,
            sifr_type_system::PythonArrowKind::Stream => wire::PythonArrowKind::Stream,
            sifr_type_system::PythonArrowKind::DeviceArray => wire::PythonArrowKind::DeviceArray,
            sifr_type_system::PythonArrowKind::DeviceStream => wire::PythonArrowKind::DeviceStream,
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::FixedIntType>> for sifr_type_system::FixedIntType {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::FixedIntType>> {
        let value = match self {
            sifr_type_system::FixedIntType::I8 => wire::FixedIntType::I8,
            sifr_type_system::FixedIntType::I16 => wire::FixedIntType::I16,
            sifr_type_system::FixedIntType::I32 => wire::FixedIntType::I32,
            sifr_type_system::FixedIntType::I64 => wire::FixedIntType::I64,
            sifr_type_system::FixedIntType::U8 => wire::FixedIntType::U8,
            sifr_type_system::FixedIntType::U16 => wire::FixedIntType::U16,
            sifr_type_system::FixedIntType::U32 => wire::FixedIntType::U32,
            sifr_type_system::FixedIntType::U64 => wire::FixedIntType::U64,
            sifr_type_system::FixedIntType::ISize => wire::FixedIntType::ISize,
            sifr_type_system::FixedIntType::USize => wire::FixedIntType::USize,
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::FunctionType>> for sifr_type_system::FunctionType {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::FunctionType>> {
        let value = wire::FunctionType {
            receiver: self.receiver.encode(cx)?,
            params: self.params.encode(cx)?,
            return_type: self.return_type.encode(cx)?,
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::ReceiverConvention>> for sifr_type_system::ReceiverConvention {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ReceiverConvention>> {
        let value = match self {
            sifr_type_system::ReceiverConvention::SharedBorrow => {
                wire::ReceiverConvention::SharedBorrow
            }
            sifr_type_system::ReceiverConvention::MutableBorrow => {
                wire::ReceiverConvention::MutableBorrow
            }
            sifr_type_system::ReceiverConvention::Owned => wire::ReceiverConvention::Owned,
            sifr_type_system::ReceiverConvention::OwnedMutable => {
                wire::ReceiverConvention::OwnedMutable
            }
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::ParamOwnership>> for sifr_type_system::ParamOwnership {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ParamOwnership>> {
        let value = match self {
            sifr_type_system::ParamOwnership::Borrow => wire::ParamOwnership::Borrow,
            sifr_type_system::ParamOwnership::Own => wire::ParamOwnership::Own,
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::ParamMutability>> for sifr_type_system::ParamMutability {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ParamMutability>> {
        let value = match self {
            sifr_type_system::ParamMutability::Immutable => wire::ParamMutability::Immutable,
            sifr_type_system::ParamMutability::Mutable => wire::ParamMutability::Mutable,
        };
        cx.records.intern(&value)
    }
}
impl Encode<wire::Ref<wire::ParamConvention>> for sifr_type_system::ParamConvention {
    fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::ParamConvention>> {
        let value = wire::ParamConvention {
            ownership: self.ownership().encode(cx)?,
            mutability: self.mutability().encode(cx)?,
        };
        cx.records.intern(&value)
    }
}
