[package]
name = "sifr_compiler_services"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[features]
test-support = []

[dependencies]
ruff_text_size = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sifr_codegen = { workspace = true }
sifr_diagnostics = { workspace = true }
sifr_frontend = { workspace = true }
sifr_ir = { workspace = true }
sifr_lowering = { workspace = true }
sifr_package = { workspace = true }
sifr_python_ast = { workspace = true }
sifr_stdlib_manifest = { workspace = true }
sifr_syntax = { workspace = true }
sifr_sysroot = { workspace = true }
sifr_type_system = { workspace = true }

[lints]
workspace = true
