#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path

from phase31_leetcode_lib import (
    REPO_ROOT,
    build_inventory,
    inventory_summary,
    validate_seed_manifest,
    write_json,
)


SEED_CASES = [
    # arrays
    {
        "id": "0001",
        "fixture_slug": "0001_two_sum",
        "sifr_path": "audits/leetcode/src/0001_two_sum.sifr",
        "difficulty": "easy",
        "primary_topic": "arrays",
        "topics": ["arrays", "hash_map"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0053",
        "fixture_slug": "0053_maximum_subarray",
        "sifr_path": "audits/leetcode/src/0053_maximum_subarray.sifr",
        "difficulty": "easy",
        "primary_topic": "arrays",
        "topics": ["arrays", "dp"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0238",
        "fixture_slug": "0238_product_of_array_except_self",
        "sifr_path": "audits/leetcode/src/0238_product_of_array_except_self.sifr",
        "difficulty": "medium",
        "primary_topic": "arrays",
        "topics": ["arrays", "prefix_product"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0912",
        "fixture_slug": "0912_sort_an_array",
        "sifr_path": "audits/leetcode/src/0912_sort_an_array.sifr",
        "difficulty": "medium",
        "primary_topic": "arrays",
        "topics": ["arrays", "sorting"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "1299",
        "fixture_slug": "1299_replace_elements_with_greatest_element_on_right_side",
        "sifr_path": "audits/leetcode/src/1299_replace_elements_with_greatest_element_on_right_side.sifr",
        "difficulty": "easy",
        "primary_topic": "arrays",
        "topics": ["arrays"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    # strings
    {
        "id": "0014",
        "fixture_slug": "0014_longest_common_prefix",
        "sifr_path": "audits/leetcode/src/0014_longest_common_prefix.sifr",
        "difficulty": "easy",
        "primary_topic": "strings",
        "topics": ["strings"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0043",
        "fixture_slug": "0043_multiply_strings",
        "sifr_path": "audits/leetcode/src/0043_multiply_strings.sifr",
        "difficulty": "medium",
        "primary_topic": "strings",
        "topics": ["strings", "math"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0151",
        "fixture_slug": "0151_reverse_words_in_a_string",
        "sifr_path": "audits/leetcode/src/0151_reverse_words_in_a_string.sifr",
        "difficulty": "medium",
        "primary_topic": "strings",
        "topics": ["strings", "two_pointers"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "1209",
        "fixture_slug": "1209_remove_all_adjacent_duplicates_in_string_ii",
        "sifr_path": "audits/leetcode/src/1209_remove_all_adjacent_duplicates_in_string_ii.sifr",
        "difficulty": "medium",
        "primary_topic": "strings",
        "topics": ["strings", "stack"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "1768",
        "fixture_slug": "1768_merge_strings_alternately",
        "sifr_path": "audits/leetcode/src/1768_merge_strings_alternately.sifr",
        "difficulty": "easy",
        "primary_topic": "strings",
        "topics": ["strings", "two_pointers"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    # hash map
    {
        "id": "0003",
        "fixture_slug": "0003_longest_substring_without_repeating_characters",
        "sifr_path": "audits/leetcode/src/0003_longest_substring_without_repeating_characters.sifr",
        "difficulty": "medium",
        "primary_topic": "hash_map",
        "topics": ["hash_map", "strings", "sliding_window"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0217",
        "fixture_slug": "0217_contains_duplicate",
        "sifr_path": "audits/leetcode/src/0217_contains_duplicate.sifr",
        "difficulty": "easy",
        "primary_topic": "hash_map",
        "topics": ["hash_map", "arrays"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0242",
        "fixture_slug": "0242_valid_anagram",
        "sifr_path": "audits/leetcode/src/0242_valid_anagram.sifr",
        "difficulty": "easy",
        "primary_topic": "hash_map",
        "topics": ["hash_map", "strings"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0523",
        "fixture_slug": "0523_continuous_subarray_sum",
        "sifr_path": "audits/leetcode/src/0523_continuous_subarray_sum.sifr",
        "difficulty": "medium",
        "primary_topic": "hash_map",
        "topics": ["hash_map", "prefix_sum"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0560",
        "fixture_slug": "0560_subarray_sum_equals_k",
        "sifr_path": "audits/leetcode/src/0560_subarray_sum_equals_k.sifr",
        "difficulty": "medium",
        "primary_topic": "hash_map",
        "topics": ["hash_map", "prefix_sum"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    # dynamic programming
    {
        "id": "0070",
        "fixture_slug": "0070_climbing_stairs",
        "sifr_path": "audits/leetcode/src/0070_climbing_stairs.sifr",
        "difficulty": "easy",
        "primary_topic": "dp",
        "topics": ["dp"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0198",
        "fixture_slug": "0198_house_robber",
        "sifr_path": "audits/leetcode/src/0198_house_robber.sifr",
        "difficulty": "medium",
        "primary_topic": "dp",
        "topics": ["dp"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0322",
        "fixture_slug": "0322_coin_change",
        "sifr_path": "audits/leetcode/src/0322_coin_change.sifr",
        "difficulty": "medium",
        "primary_topic": "dp",
        "topics": ["dp"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0746",
        "fixture_slug": "0746_min_cost_climbing_stairs",
        "sifr_path": "audits/leetcode/src/0746_min_cost_climbing_stairs.sifr",
        "difficulty": "easy",
        "primary_topic": "dp",
        "topics": ["dp"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "1143",
        "fixture_slug": "1143_longest_common_subsequence",
        "sifr_path": "audits/leetcode/src/1143_longest_common_subsequence.sifr",
        "difficulty": "medium",
        "primary_topic": "dp",
        "topics": ["dp", "strings"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    # graphs
    {
        "id": "0127",
        "fixture_slug": "0127_word_ladder",
        "sifr_path": "audits/leetcode/src/0127_word_ladder.sifr",
        "difficulty": "hard",
        "primary_topic": "graphs",
        "topics": ["graphs", "bfs", "strings"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0207",
        "fixture_slug": "0207_course_schedule",
        "sifr_path": "audits/leetcode/src/0207_course_schedule.sifr",
        "difficulty": "medium",
        "primary_topic": "graphs",
        "topics": ["graphs", "dfs"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0684",
        "fixture_slug": "0684_redundant_connection",
        "sifr_path": "audits/leetcode/src/0684_redundant_connection.sifr",
        "difficulty": "medium",
        "primary_topic": "graphs",
        "topics": ["graphs", "union_find"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0743",
        "fixture_slug": "0743_network_delay_time",
        "sifr_path": "audits/leetcode/src/0743_network_delay_time.sifr",
        "difficulty": "medium",
        "primary_topic": "graphs",
        "topics": ["graphs", "shortest_path", "heap"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0997",
        "fixture_slug": "0997_find_the_town_judge",
        "sifr_path": "audits/leetcode/src/0997_find_the_town_judge.sifr",
        "difficulty": "easy",
        "primary_topic": "graphs",
        "topics": ["graphs"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    # trees
    {
        "id": "0100",
        "fixture_slug": "0100_same_tree",
        "sifr_path": "audits/leetcode/src/0100_same_tree.sifr",
        "difficulty": "easy",
        "primary_topic": "trees",
        "topics": ["trees", "dfs"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0102",
        "fixture_slug": "0102_binary_tree_level_order_traversal",
        "sifr_path": "audits/leetcode/src/0102_binary_tree_level_order_traversal.sifr",
        "difficulty": "medium",
        "primary_topic": "trees",
        "topics": ["trees", "bfs"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0110",
        "fixture_slug": "0110_balanced_binary_tree",
        "sifr_path": "audits/leetcode/src/0110_balanced_binary_tree.sifr",
        "difficulty": "easy",
        "primary_topic": "trees",
        "topics": ["trees", "dfs"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0226",
        "fixture_slug": "0226_invert_binary_tree",
        "sifr_path": "audits/leetcode/src/0226_invert_binary_tree.sifr",
        "difficulty": "easy",
        "primary_topic": "trees",
        "topics": ["trees", "dfs"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0235",
        "fixture_slug": "0235_lowest_common_ancestor_of_a_binary_search_tree",
        "sifr_path": "audits/leetcode/src/0235_lowest_common_ancestor_of_a_binary_search_tree.sifr",
        "difficulty": "medium",
        "primary_topic": "trees",
        "topics": ["trees", "bst"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    # backtracking
    {
        "id": "0017",
        "fixture_slug": "0017_letter_combinations_of_a_phone_number",
        "sifr_path": "audits/leetcode/src/0017_letter_combinations_of_a_phone_number.sifr",
        "difficulty": "medium",
        "primary_topic": "backtracking",
        "topics": ["backtracking", "strings"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0039",
        "fixture_slug": "0039_combination_sum",
        "sifr_path": "audits/leetcode/src/0039_combination_sum.sifr",
        "difficulty": "medium",
        "primary_topic": "backtracking",
        "topics": ["backtracking"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0078",
        "fixture_slug": "0078_subsets",
        "sifr_path": "audits/leetcode/src/0078_subsets.sifr",
        "difficulty": "medium",
        "primary_topic": "backtracking",
        "topics": ["backtracking"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0090",
        "fixture_slug": "0090_subsets_ii",
        "sifr_path": "audits/leetcode/src/0090_subsets_ii.sifr",
        "difficulty": "medium",
        "primary_topic": "backtracking",
        "topics": ["backtracking"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0052",
        "fixture_slug": "0052_n_queens_ii",
        "sifr_path": "audits/leetcode/src/0052_n_queens_ii.sifr",
        "difficulty": "hard",
        "primary_topic": "backtracking",
        "topics": ["backtracking"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    # math
    {
        "id": "0007",
        "fixture_slug": "0007_reverse_integer",
        "sifr_path": "audits/leetcode/src/0007_reverse_integer.sifr",
        "difficulty": "medium",
        "primary_topic": "math",
        "topics": ["math"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0009",
        "fixture_slug": "0009_palindrome_number",
        "sifr_path": "audits/leetcode/src/0009_palindrome_number.sifr",
        "difficulty": "easy",
        "primary_topic": "math",
        "topics": ["math"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0050",
        "fixture_slug": "0050_powx_n",
        "sifr_path": "audits/leetcode/src/0050_powx_n.sifr",
        "difficulty": "medium",
        "primary_topic": "math",
        "topics": ["math", "recursion"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0069",
        "fixture_slug": "0069_sqrtx",
        "sifr_path": "audits/leetcode/src/0069_sqrtx.sifr",
        "difficulty": "easy",
        "primary_topic": "math",
        "topics": ["math", "binary_search"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "2235",
        "fixture_slug": "2235_add_two_integers",
        "sifr_path": "audits/leetcode/src/2235_add_two_integers.sifr",
        "difficulty": "easy",
        "primary_topic": "math",
        "topics": ["math"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    # heap / priority queue
    {
        "id": "0215",
        "fixture_slug": "0215_kth_largest_element_in_an_array",
        "sifr_path": "audits/leetcode/src/0215_kth_largest_element_in_an_array.sifr",
        "difficulty": "medium",
        "primary_topic": "heap_priority_queue",
        "topics": ["heap_priority_queue", "arrays"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0295",
        "fixture_slug": "0295_find_median_from_data_stream",
        "sifr_path": "audits/leetcode/src/0295_find_median_from_data_stream.sifr",
        "difficulty": "hard",
        "primary_topic": "heap_priority_queue",
        "topics": ["heap_priority_queue", "design"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0502",
        "fixture_slug": "0502_ipo",
        "sifr_path": "audits/leetcode/src/0502_ipo.sifr",
        "difficulty": "hard",
        "primary_topic": "heap_priority_queue",
        "topics": ["heap_priority_queue", "greedy"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "0703",
        "fixture_slug": "0703_kth_largest_element_in_a_stream",
        "sifr_path": "audits/leetcode/src/0703_kth_largest_element_in_a_stream.sifr",
        "difficulty": "easy",
        "primary_topic": "heap_priority_queue",
        "topics": ["heap_priority_queue", "design"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    {
        "id": "1046",
        "fixture_slug": "1046_last_stone_weight",
        "sifr_path": "audits/leetcode/src/1046_last_stone_weight.sifr",
        "difficulty": "easy",
        "primary_topic": "heap_priority_queue",
        "topics": ["heap_priority_queue"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "no_oracle"},
        "timeout_seconds": 20,
    },
    # two pointers / sliding window
    {
        "id": "0015",
        "fixture_slug": "0015_3sum",
        "sifr_path": "audits/leetcode/src/0015_3sum.sifr",
        "difficulty": "medium",
        "primary_topic": "two_pointers_sliding_window",
        "topics": ["two_pointers_sliding_window", "arrays"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0042",
        "fixture_slug": "0042_trapping_rain_water",
        "sifr_path": "audits/leetcode/src/0042_trapping_rain_water.sifr",
        "difficulty": "hard",
        "primary_topic": "two_pointers_sliding_window",
        "topics": ["two_pointers_sliding_window", "arrays"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0209",
        "fixture_slug": "0209_minimum_size_subarray_sum",
        "sifr_path": "audits/leetcode/src/0209_minimum_size_subarray_sum.sifr",
        "difficulty": "medium",
        "primary_topic": "two_pointers_sliding_window",
        "topics": ["two_pointers_sliding_window", "arrays"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "0424",
        "fixture_slug": "0424_longest_repeating_character_replacement",
        "sifr_path": "audits/leetcode/src/0424_longest_repeating_character_replacement.sifr",
        "difficulty": "medium",
        "primary_topic": "two_pointers_sliding_window",
        "topics": ["two_pointers_sliding_window", "strings"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
    {
        "id": "1456",
        "fixture_slug": "1456_maximum_number_of_vowels_in_a_substring_of_given_length",
        "sifr_path": "audits/leetcode/src/1456_maximum_number_of_vowels_in_a_substring_of_given_length.sifr",
        "difficulty": "medium",
        "primary_topic": "two_pointers_sliding_window",
        "topics": ["two_pointers_sliding_window", "strings"],
        "scope_classification": "in_scope",
        "oracle": {"mode": "embedded_asserts"},
        "timeout_seconds": 20,
    },
]

DEMO_CASE_IDS = ["0001", "0009", "0069", "0070", "0100"]


def main() -> None:
    verification_dir = REPO_ROOT / "verification" / "leetcode"
    seed_manifest_path = verification_dir / "phase31_seed_corpus.json"
    inventory_path = verification_dir / "phase31_corpus_inventory.json"
    summary_path = verification_dir / "phase31_seed_summary.json"
    demo_manifest_path = verification_dir / "phase31_demo_corpus.json"

    seed_summary = validate_seed_manifest(SEED_CASES)
    seed_case_ids = {entry["id"] for entry in SEED_CASES}
    inventory = build_inventory(seed_case_ids)
    write_json(
        seed_manifest_path,
        {
            "phase": 31,
            "name": "phase31_seed_corpus",
            "case_count": len(SEED_CASES),
            "cases": SEED_CASES,
        },
    )
    write_json(
        inventory_path,
        {
            "phase": 31,
            "name": "phase31_corpus_inventory",
            "summary": inventory_summary(inventory),
            "cases": inventory,
        },
    )
    write_json(summary_path, seed_summary)
    write_json(
        demo_manifest_path,
        {
            "phase": 31,
            "name": "phase31_demo_corpus",
            "case_count": len(DEMO_CASE_IDS),
            "cases": [case for case in SEED_CASES if case["id"] in DEMO_CASE_IDS],
        },
    )

    print(f"wrote {seed_manifest_path.relative_to(REPO_ROOT)}")
    print(f"wrote {inventory_path.relative_to(REPO_ROOT)}")
    print(f"wrote {summary_path.relative_to(REPO_ROOT)}")
    print(f"wrote {demo_manifest_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
