#!/usr/bin/env python3
"""Generate exhaustive typed metadata projections from the owned wire record families.

The generated matches compile against the live IR. Nominal identities, declaration
binders, source positions and producer orchestration remain explicit driver code.
"""
from pathlib import Path
import argparse
import re
import subprocess
import tempfile
root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check',action='store_true')
options=parser.parse_args()
destination=root/'crates/sifr_driver/src/metadata_producer'
temporary=tempfile.TemporaryDirectory(prefix='sifr-metadata-encoders-')
out=Path(temporary.name) if options.check else destination
def clean(s):
 s=re.sub(r'//[^\n]*','',s)
 s=re.sub(r'#\[[^\]]*\]','',s)
 return s

def split(s):
 parts=[];start=0;depth=0
 for i,c in enumerate(s):
  if c in '(<{[':depth+=1
  elif c in ')>}]':depth-=1
  elif c==',' and depth==0:
   if s[start:i].strip():parts.append(s[start:i].strip())
   start=i+1
 if s[start:].strip():parts.append(s[start:].strip())
 return parts

def records(s):
 s=clean(s); result={}
 for m in re.finditer(r'pub (struct|enum) (\w+)\s*\{',s):
  start=m.end();depth=1;i=start
  while depth:
   depth+=(s[i]=='{')-(s[i]=='}');i+=1
  result[m[2]]=(m[1],split(s[start:i-1]))
 return result

groups=['hir_nodes','specialization_metadata','rust_interop','python_interop','template_strings','sql_queries','sql_migrations','type_records']
special={'Type','BindingId','SourceOriginId','StructuralRecordField','StructuralRecordType'}
for group in groups:
 wire=records((root/f'crates/sifr_sysroot/src/metadata/{group}.rs').read_text())
 body=['// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.','use super::{Encoder, Encode, Result, wire};']
 for name,(kind,fields) in wire.items():
  if name in special:continue
  live=('sifr_type_system' if group=='type_records' else 'sifr_ir')+'::'+name
  lines=[f'impl Encode<wire::Ref<wire::{name}>> for {live} {{',f'fn encode(&self, cx: &mut Encoder) -> Result<wire::Ref<wire::{name}>> {{']
  scoped=name in ('HirFunction','HirClass')
  if scoped:
   lines+=[f'cx.with_owner(&self.name, &self.type_params, {"wire::DeclarationKind::Function" if name=="HirFunction" else "super::class_kind(self)"}, |cx| {{']
  if kind=='struct':
   lines+=[f'let value = wire::{name} {{']
   for f in fields:
    field=re.match(r'(?:pub\s+)?(\w+)\s*:',f)[1]
    expression=f'self.{field}'
    if name=='ParamConvention': expression+='()'
    if field in ('static_minimum','static_maximum'):expression+='.as_ref().map(ToString::to_string)'
    lines+=[f'{field}: {expression}.encode(cx)?,']
   lines+=['};']
  else:
   lines+=['let value = match self {']
   for f in fields:
    m=re.match(r'(\w+)(.*)',f,re.S);var,tail=m.groups();tail=tail.strip()
    if not tail:lines+=[f'{live}::{var} => wire::{name}::{var},'];continue
    if tail[0]=='(':
     members=split(tail[1:-1]);args=[f'v{i}' for i in range(len(members))]
     lines+=[f'{live}::{var}({", ".join(args)}) => wire::{name}::{var}({", ".join(x+".encode(cx)?" for x in args)}),']
    else:
     members=[re.match(r'(\w+)\s*:',p)[1] for p in split(tail[1:-1])]
     lines+=[f'{live}::{var} {{ {", ".join(members)} }} => wire::{name}::{var} {{ '+', '.join(f'{x}: '+(f'super::encode::error_type_set({x}, cx)?' if x=='body_error_types' else f'{x}.encode(cx)?') for x in members)+' },']
   lines+=['};']
  lines+=['cx.records.intern(&value).map_err(Into::into)']
  if scoped:lines+=['})']
  lines+=['}','}']
  body.extend(lines)
 (out/f'{group}.rs').write_text('\n'.join(body)+'\n')

wire=records((root/'crates/sifr_sysroot/src/metadata/type_records.rs').read_text())
body=['// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.','use super::{Encoder, Encode, Result, wire};','use sifr_type_system::Type;','impl Encode<wire::Ref<wire::Type>> for Type {','fn encode(&self,cx:&mut Encoder)->Result<wire::Ref<wire::Type>> {','let value=match self {']
for f in wire['Type'][1]:
 var,tail=re.match(r'(\w+)(.*)',f,re.S).groups();tail=tail.strip()
 if var in ('Class','Enum','Alias','Newtype','Protocol','TypeVar'):continue
 if not tail:body.append(f'Type::{var}=>wire::Type::{var},')
 elif tail[0]=='(':
  args=[f'v{i}' for i in range(len(split(tail[1:-1])))];body.append(f'Type::{var}({",".join(args)})=>wire::Type::{var}({",".join(x+".encode(cx)?" for x in args)}),')
body.extend('''Type::TypeVar(name) => {
 let (_,binder,slot)=cx.parameters.iter().rev().find(|(p,_,_)|p==name).ok_or_else(||wire::MetadataError(format!("unbound type parameter {name} in {}",cx.owner)))?;
 wire::Type::TypeVar{binder:*binder,slot:*slot}
},
Type::Alias{name,type_args,body} => {
 let declaration=cx.declaration(name,wire::DeclarationKind::Alias)?;
 wire::Type::Alias{name:name.encode(cx)?,declaration,type_args:type_args.encode(cx)?,body:if **body==Type::Unknown{None}else{Some(body.encode(cx)?)}}
},
Type::Class{identity,name,type_args,fields,methods,parent_class} => {
 let declaration=cx.declaration(identity.as_deref().unwrap_or(name),wire::DeclarationKind::Class)?;
 let value=wire::NominalView{name:name.encode(cx)?,identity:identity.encode(cx)?,fields:fields.encode(cx)?,methods:methods.encode(cx)?,parent_class:parent_class.encode(cx)?,enum_variants:Vec::new(),newtype_inner:None};
 let view=cx.records.intern(&value)?;
 wire::Type::Class{declaration,view,type_args:type_args.encode(cx)?}
},
Type::Protocol{identity,name,methods} => {
 let declaration=cx.declaration(identity.as_deref().unwrap_or(name),wire::DeclarationKind::Protocol)?;
 let value=wire::NominalView{name:name.encode(cx)?,identity:identity.encode(cx)?,fields:Vec::new(),methods:methods.encode(cx)?,parent_class:None,enum_variants:Vec::new(),newtype_inner:None};
 let view=cx.records.intern(&value)?;
 wire::Type::Protocol{declaration,view,type_args:Vec::new()}
},
Type::Newtype{identity,name,inner} => {
 let declaration=cx.declaration(identity.as_deref().unwrap_or(name),wire::DeclarationKind::Newtype)?;
 let value=wire::NominalView{name:name.encode(cx)?,identity:identity.encode(cx)?,fields:Vec::new(),methods:Vec::new(),parent_class:None,enum_variants:Vec::new(),newtype_inner:Some(inner.encode(cx)?)};
 let view=cx.records.intern(&value)?;
 wire::Type::Newtype{declaration,view,type_args:Vec::new()}
},
Type::Enum{identity,name,variants} => {
 let declaration=cx.declaration(identity.as_deref().unwrap_or(name),wire::DeclarationKind::Enum)?;
 let value=wire::NominalView{name:name.encode(cx)?,identity:identity.encode(cx)?,fields:Vec::new(),methods:Vec::new(),parent_class:None,enum_variants:variants.encode(cx)?,newtype_inner:None};
 let view=cx.records.intern(&value)?;
 wire::Type::Enum{declaration,view,type_args:Vec::new()}
},
}; cx.records.intern(&value)
}}
impl Encode<wire::Ref<wire::StructuralRecordField>> for sifr_type_system::StructuralRecordField {
 fn encode(&self,cx:&mut Encoder)->Result<wire::Ref<wire::StructuralRecordField>>{
  let value=wire::StructuralRecordField{name:self.name().encode(cx)?,ty:self.ty().encode(cx)?};cx.records.intern(&value)
 }
}
impl Encode<wire::Ref<wire::StructuralRecordType>> for sifr_type_system::StructuralRecordType {
 fn encode(&self,cx:&mut Encoder)->Result<wire::Ref<wire::StructuralRecordType>>{
  let value=wire::StructuralRecordType{canonical_fields:self.fields().encode(cx)?,source_order:self.source_fields().iter().map(|v|v.name().encode(cx)).collect::<Result<_>>()?};cx.records.intern(&value)
 }
}'''.splitlines())
(out/'types.rs').write_text('\n'.join(body)+'\n')
wire=records((root/'crates/sifr_sysroot/src/metadata/semantic_records.rs').read_text())
body=['// @generated by scripts/generate_metadata_encoders.py; DO NOT EDIT.','use super::{Encoder, Encode, Result, wire};','pub(super) fn project(defs:&sifr_lowering::ExternalDefs,module:&str,cx:&mut Encoder)->Result<wire::Ref<wire::SemanticExports>> {','let value=wire::SemanticExports {']
for field in wire['SemanticExports'][1]:
 name=re.match(r'pub (\w+)',field)[1]
 if name=='structural_methods':
  body.append('structural_methods: defs.structural_methods_for(module).into_iter().flat_map(|m|m.iter()).map(|(name,methods)|Ok((name.encode(cx)?,methods.encode(cx)?))).collect::<Result<_>>()?,')
 elif name=='classes':
  body.append('classes:scoped_types(defs.classes.get(module),defs.class_type_params.get(module),cx)?,')
 elif name in ('functions','function_defaults','class_field_defaults'):
  params='generic_functions' if name in ('functions','function_defaults') else 'class_type_params'
  kind='Function' if params=='generic_functions' else 'Class'
  body.append(f'{name}: scoped_map(defs.{name}.get(module), defs.{params}.get(module), wire::DeclarationKind::{kind},cx)?,')
 elif name=='generic_type_aliases':
  body.append('generic_type_aliases: defs.generic_type_aliases.get(module).cloned().unwrap_or_default().iter().map(|(name,(params,ty))|cx.with_owner(name,params,wire::DeclarationKind::Alias,|cx|Ok((name.encode(cx)?,(params.encode(cx)?,ty.encode(cx)?))))).collect::<Result<_>>()?,')
 elif name=='constant_integer_values':
  body.append('constant_integer_values:defs.constant_integer_values.get(module).cloned().unwrap_or_default().iter().map(|(k,v)|Ok((k.encode(cx)?,v.to_string().encode(cx)?))).collect::<Result<_>>()?,')
 else:
  body.append(f'{name}:defs.{name}.get(module).cloned().unwrap_or_default().encode(cx)?,')
body.extend(['};cx.records.intern(&value)','}', '''fn scoped_map<T: Encode<U>,U>(values:Option<&std::collections::HashMap<String,T>>,parameters:Option<&std::collections::HashMap<String,Vec<String>>>,kind:wire::DeclarationKind,cx:&mut Encoder)->Result<std::collections::BTreeMap<wire::Ref<wire::Text>,U>> {
 let mut entries=values.into_iter().flat_map(|v|v.iter()).collect::<Vec<_>>();entries.sort_by(|a,b|a.0.cmp(b.0));
 entries.into_iter().map(|(name,value)|{let params=parameters.and_then(|m|m.get(name)).map(Vec::as_slice).unwrap_or(&[]);cx.with_owner(name,params,kind.clone(),|cx|Ok((name.encode(cx)?,value.encode(cx)?)))}).collect()
}'''])
name='StructuralMethodExport'
body.extend([f'impl Encode<wire::Ref<wire::{name}>> for sifr_lowering::{name} {{',f'fn encode(&self,cx:&mut Encoder)->Result<wire::Ref<wire::{name}>> {{',f'let value=wire::{name}{{'])
for f in wire[name][1]:
 field=re.match(r'pub (\w+)',f)[1];body.append(f'{field}:self.{field}.encode(cx)?,')
body.extend(['};cx.records.intern(&value)','}','}'])
body.append('''fn scoped_types(values:Option<&std::collections::HashMap<String,sifr_type_system::Type>>,parameters:Option<&std::collections::HashMap<String,Vec<String>>>,cx:&mut Encoder)->Result<std::collections::BTreeMap<wire::Ref<wire::Text>,wire::Ref<wire::Type>>> {
 let mut entries=values.into_iter().flat_map(|v|v.iter()).collect::<Vec<_>>();entries.sort_by(|a,b|a.0.cmp(b.0));
 entries.into_iter().map(|(name,value)|{let params=parameters.and_then(|m|m.get(name)).map(Vec::as_slice).unwrap_or(&[]);let kind=match value {sifr_type_system::Type::Enum{..}=>wire::DeclarationKind::Enum,sifr_type_system::Type::Protocol{..}=>wire::DeclarationKind::Protocol,sifr_type_system::Type::Newtype{..}=>wire::DeclarationKind::Newtype,sifr_type_system::Type::Alias{..}=>wire::DeclarationKind::Alias,_=>wire::DeclarationKind::Class};cx.with_owner(name,params,kind,|cx|Ok((name.encode(cx)?,value.encode(cx)?)))}).collect()
}''')
(out/'semantic.rs').write_text('\n'.join(body)+'\n')

paths=[out/f'{group}.rs' for group in groups]+[out/'types.rs',out/'semantic.rs']
subprocess.run(['rustfmt','--edition','2024',*(str(path) for path in paths)],check=True,cwd=root)
if options.check:
    changed=[path.name for path in paths if path.read_bytes()!=(destination/path.name).read_bytes()]
    if changed:raise SystemExit('metadata encoder generation differs: '+', '.join(changed))
print('metadata encoder generation: PASS')
