#!/usr/bin/env python3
"""Generate exhaustive demanded wire-to-live projections; ownership remains explicit."""
from pathlib import Path
import argparse
import re
import subprocess
import tempfile
root=Path(__file__).resolve().parents[1]
source=(root/'scripts/generate_metadata_encoders.py').read_text()
exec(source[source.index('def clean('):source.index("groups=['")])
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
options = parser.parse_args()
destination = root / 'crates/sifr_compiler_services/src/metadata/reader'
temporary = tempfile.TemporaryDirectory(prefix="sifr-metadata-decoders-")
out = Path(temporary.name)
groups=['hir_nodes','specialization_metadata','rust_interop','python_interop','template_strings','sql_queries','sql_migrations','type_records']
special={'Type','BindingId','SourceOriginId','StructuralRecordField','StructuralRecordType','ParamConvention'}
for group in groups:
 schema=records((root/f'crates/sifr_sysroot/src/metadata/{group}.rs').read_text())
 body=['// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.','use super::{Decode, Decoder, Result, wire};']
 for name,(kind,fields) in schema.items():
  if name in special:continue
  live=('sifr_type_system' if group=='type_records' else 'sifr_ir')+'::'+name
  body += [f'impl Decode<wire::Ref<wire::{name}>> for {live} {{', f'fn decode(reference: &wire::Ref<wire::{name}>, cx: &mut Decoder)->Result<Self> {{', 'cx.record(*reference, |value,cx| { let _ = &cx;']
  if kind=='struct':
   body += ['Ok(Self {']
   for f in fields:
    field=re.match(r'(?:pub\s+)?(\w+)\s*:',f)[1]
    body += [f'{field}: Decode::decode(&value.{field},cx)?,']
   body += ['})']
  else:
   body += ['Ok(match value {']
   for f in fields:
    var,tail=re.match(r'(\w+)(.*)',f,re.S).groups();tail=tail.strip()
    if not tail:body += [f'wire::{name}::{var} => Self::{var},'];continue
    if tail[0]=='(':
     args=[f'v{i}' for i in range(len(split(tail[1:-1])))]
     body += [f'wire::{name}::{var}({", ".join(args)}) => Self::{var}({", ".join("Decode::decode("+x+",cx)?" for x in args)}),']
    else:
     members=[re.match(r'(\w+)\s*:',p)[1] for p in split(tail[1:-1])]
     body += [f'wire::{name}::{var} {{ {", ".join(members)} }} => Self::{var} {{ '+', '.join(f'{x}: Decode::decode({x},cx)?' for x in members)+' },']
   body += ['})']
  body += ['})','}','}']
 (out/f'{group}.rs').write_text('\n'.join(body)+'\n')

schema=records((root/'crates/sifr_sysroot/src/metadata/semantic_records.rs').read_text())
body=['// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.','use super::{Decode,Decoder,Result,wire};',
'pub(super) fn project(module: &str, record: wire::Ref<wire::SemanticExports>,cx:&mut Decoder)->Result<sifr_lowering::ExternalDefs> {',
'let value=cx.store.get(record)?; let mut defs=sifr_lowering::ExternalDefs::default();']
for f in schema['SemanticExports'][1]:
 field=re.match(r'(?:pub\s+)?(\w+)\s*:',f)[1]
 if field=='structural_methods':
  body += ['defs.replace_structural_methods(module,Decode::decode(&value.structural_methods,cx)?);']
 else:
  body += [f'defs.{field}.insert(module.to_owned(),Decode::decode(&value.{field},cx)?);']
body += ['defs.freeze_baseline(); Ok(defs)','}',
'impl Decode<wire::Ref<wire::StructuralMethodExport>> for sifr_lowering::StructuralMethodExport {',
'fn decode(reference:&wire::Ref<wire::StructuralMethodExport>,cx:&mut Decoder)->Result<Self>{',
'cx.record(*reference,|value,cx| Ok(Self {']
for f in schema['StructuralMethodExport'][1]:
 field=re.match(r'(?:pub\s+)?(\w+)\s*:',f)[1]
 body += [f'{field}:Decode::decode(&value.{field},cx)?,']
body += ['}))}}']
(out/'semantic.rs').write_text('\n'.join(body)+'\n')
subprocess.run(['rustfmt','--edition','2024',*(str(out/f'{g}.rs') for g in groups+['semantic'])],check=True)

for generated in sorted(out.glob("*.rs")):
    target = destination / generated.name
    if options.check:
        if not target.exists() or target.read_bytes() != generated.read_bytes():
            raise SystemExit(f"metadata decoder is stale: {target.relative_to(root)}")
    else:
        target.write_bytes(generated.read_bytes())
temporary.cleanup()
