"""Reviewed source-method nodes. Edits require the exact call-chain audit.

Node labels state the actual responsibility, while context/reference hashes in
method_dispatch_sites.json bind all lexical callers (including aliases/macros).
Shape predicates do not independently admit source methods.
"""
CODEGEN = 'crates/sifr_codegen/src/'
CONSTITUENTS = {
    ('stmt_support_emitter/stmt_expr_method_and_question_mark.rs', 'macro_rules!::stmt_expr_method_call'): 'source_method_path -> is_builtin; builtin specializations end in registry or builtin_method_decline; nonbuiltins branch separately',
    ('intrinsic_method_emitters/recursive_exprs.rs', 'try_lower_registry_expr_recursive'): 'source_method_path -> nonbuiltin early return; builtin specializations end in methods registry or decline',
    ('lower_expr/iterators_and_callables.rs', 'try_lower_simple_method_call_expr'): 'source_method_path -> is_builtin before task/iterator specialization',
    ('intrinsic_method_emitters/collection_methods.rs', 'try_lower_registry_method_call_expr'): 'admitted stmt_expr_method_call -> operands and checked/defaultdict or unchecked registry',
    ('intrinsic_method_emitters/collection_methods.rs', 'try_lower_registry_discarded_method_call_expr'): 'admitted stmt_expr_method_call -> setdefault discard policy or ordinary registry',
    ('intrinsic_method_emitters/collection_methods.rs', 'lower_registry_method_operands'): 'admitted ordinary/discarded registry -> checked receiver and arguments',
    ('intrinsic_method_emitters/collection_methods.rs', 'try_lower_registry_method_call_expr_unchecked'): 'admitted ordinary/discarded registry -> storage specializations or methods::lower_method_with_context',
    ('intrinsic_method_emitters/collection_methods.rs', 'try_lower_registry_set_method_call_expr'): 'admitted unchecked registry -> set iterable specialization',
    ('intrinsic_method_emitters/collection_defaultdict_methods.rs', 'try_lower_defaultdict_index_method_call_expr'): 'admitted ordinary registry -> checked defaultdict bucket -> methods registry or set helper',
    ('intrinsic_method_emitters/defaultdict_iterable_mutations.rs', 'try_lower_defaultdict_set_update_expr'): 'admitted defaultdict bucket -> set iterable mutation',
    ('intrinsic_method_emitters/recursive_method_calls.rs', 'try_lower_recursive_indexed_list_append'): 'admitted recursive builtin branch -> checked indexed append',
    ('string_char_cache.rs', 'try_lower_dict_indexed_list_append_expr'): 'admitted stmt/recursive builtin branch -> checked indexed append',
    ('string_char_cache.rs', 'try_lower_dict_indexed_list_pop_expr'): 'admitted stmt/recursive builtin branch -> checked indexed pop',
    ('string_char_cache.rs', 'try_lower_dict_indexed_list_len_expr'): 'admitted stmt/recursive builtin branch -> checked indexed len',
    ('python_raw_api_codegen.rs', 'try_lower_python_raw_object_method'): 'admitted stmt builtin branch -> canonical Python Object runtime substrate',
    ('python_buffer_codegen.rs', 'lower_python_buffer_method'): 'admitted recursive builtin branch -> canonical Buffer ABI runtime substrate',
    ('python_arrow_codegen.rs', 'lower_python_arrow_method'): 'admitted recursive builtin branch -> canonical Arrow ABI runtime substrate',
    ('python_dlpack_codegen.rs', 'lower_python_dlpack_method'): 'admitted recursive builtin branch -> canonical DLPack ABI runtime substrate',
    ('methods/bytes.rs', 'int'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'usize_literal'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'bytes_slice_ref_type'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'list_bound_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'byte_range_guard_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'bind_receiver_once'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'bound_receiver'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_count'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_contains'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_find'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_prefix_method'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_startswith'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_endswith'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_hex'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/bytes.rs', 'lower_to_ints'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'exact_int_from_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'exact_int_to_bound_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'exact_int_literal'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'lower_tuple_len'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'tuple_bound_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'lower_tuple_count'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'lower_tuple_index'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'lower_string_char_len'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'lower_option_len'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/common.rs', 'lower_len'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'bigdecimal_default_context_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'round_bigdecimal_with_default_context'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'decimal_non_negative_scale_u32'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_decimal_quantize'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_decimal_sqrt'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_decimal_round'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_decimal_abs'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_decimal_is_zero'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_decimal_is_finite'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_bigdecimal_quantize'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_bigdecimal_sqrt'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_bigdecimal_round'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_bigdecimal_abs'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_bigdecimal_is_zero'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/decimal.rs', 'lower_bigdecimal_is_finite'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/deque.rs', 'lower_append'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/deque.rs', 'lower_appendleft'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/deque.rs', 'lower_pop'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/deque.rs', 'lower_popleft'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/deque.rs', 'lower_reverse'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'is_already_borrowed_rendered_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'render_key_arg_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'materialize_setdefault_storage_arg'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_keys'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_values'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_items'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_update'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_clear'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_copy'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_contains'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_get'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_pop'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'lower_setdefault'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dict.rs', 'setdefault_affine_types_are_an_internal_invariant_violation'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dispatch.rs', 'is_in_place_collection_method'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dispatch.rs', 'lower_method'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dispatch.rs', 'lower_method_with_context'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dispatch.rs', 'lower_method_with_discard_context'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/dispatch.rs', 'supports_builtin_len'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_checked_add'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_checked_sub'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_checked_mul'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_checked_method'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_wrapping_add'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_wrapping_sub'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_wrapping_mul'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_saturating_add'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_saturating_sub'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_saturating_mul'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_overflowing_add'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_overflowing_sub'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_overflowing_mul'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/fixed_width.rs', 'lower_primitive_method'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'is_already_borrowed_rendered_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'render_borrowed_arg_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'list_bound_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_append'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_extend'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_insert'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_clear'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_copy'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_reverse'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_sort'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'sort_list_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_count'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_contains'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_string_contains'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_pop'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_remove'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/list.rs', 'lower_index'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'lower_method'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'lower_method_with_context'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'lowers_string_methods_via_registry'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'lower_method_accepts_ir_inputs'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'lower_method_supports_list_sort_with_reverse_flag'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'safe_collection_methods_flatten_optional_payload_absence'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'lowers_decimal_and_bigdecimal_methods_via_registry'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/mod.rs', 'lowers_bytes_methods_with_u8_backend_boundaries'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'is_already_borrowed_rendered_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'render_borrowed_arg_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_set_op_collect'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_add'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_remove'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_discard'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_contains'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_clear'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_copy'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_issubset'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_issuperset'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_isdisjoint'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_pop'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_union'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_intersection'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_difference'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/set.rs', 'lower_symmetric_difference'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string/search.rs', 'lower_find_like'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'replacement_or_split_limit'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'bind_nontrivial_string_receiver_once'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_zero_arg_method'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_trim_to_string'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'is_already_borrowed_rendered_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'render_borrowed_arg_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'literal_single_char'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'string_pattern_arg'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'is_none_expr'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_non_empty_char_all'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'char_predicate'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'char_predicate_closure'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_has_alpha_and_filtered_all'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_upper'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_lower'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_strip'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_startswith'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_endswith'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_split'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'to_string_method_path'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_replace'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_find'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_rfind'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_lstrip'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_rstrip'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_count'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_join'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_title'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_capitalize'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_swapcase'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_isdigit'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_isalpha'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_isalnum'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_isspace'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_isupper'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_islower'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_center'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_ljust'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_rjust'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_zfill'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('methods/string.rs', 'lower_checked_padding'): 'methods canonical registry implementation; lexical callers bind registry wrappers, helper delegation and synthesized Rust operations',
    ('lower_stmt/condition_lowering.rs', 'try_lower_numeric_truthiness_condition_expr'): 'source_method_path(operand).is_builtin before len registry lowering',
    ('lower_stmt/condition_lowering.rs', 'try_lower_condition_operand_expr'): 'source_method_path(expr).is_builtin before len checked bucket or registry lowering; nonbuiltins decline',
    ('checked_place/exit_guards.rs', 'admits_exit_guard_lengths'): 'walk every matching source len carrier; source_method_path and builtin-only aggregate result before replacement',
    ('checked_place/exit_guards.rs', 'try_lower_checked_sequence_exit_guards_for_ir'): 'admits_exit_guard_lengths precedes replacement prefix/sequence witness proof',
    ('checked_place.rs', 'checked_dict_read_guard_for_ir'): 'source_method_path(collection).is_builtin before removing a source keys carrier into checked key witness',
    ('intrinsic_method_emitters/borrowing_call_args.rs', 'materialize_explicit_borrowed_clone'): 'admitted unchecked collection registry -> explicit builtin clone/copy/cloned ownership materialization',
}
CONSTITUENTS = {(CODEGEN + p, s): r for (p, s), r in CONSTITUENTS.items()}

ADAPTATIONS = {
    ('intrinsic_method_emitters/narrowing_helpers.rs', 'adapt_owned_mapping_default'): 'owned mapping default coercion/materialization; recursive builtin branch after source_method_path or admitted collection registry caller; preserves selected method dispatch',
    ('intrinsic_method_emitters/narrowing_helpers.rs', 'supports_nonempty_pop_narrowing_type_for_codegen'): 'receiver shape predicate for checked_place nonempty Let-tail; caller preserves authority in optional_call and lowers through lower_stmt_expr_for_ir before emitting IfLet',
    ('intrinsic_method_emitters/narrowing_helpers.rs', 'is_deque_class_name_for_codegen'): 'receiver basename predicate used by supports_nonempty_pop_narrowing_type_for_codegen; no admission or emission; optional-call lowering owns admission',
    ('intrinsic_method_emitters/narrowing_helpers.rs', 'is_narrowable_pop_call_for_codegen'): 'unused production shape predicate: pop() or pop(0) or popleft(); no callers, no admission and no emitted builtin semantics',
    ('checked_place.rs', 'try_lower_nonempty_pop_tail_for_ir'): 'preserve original authority, receiver convention/place, argument places and source in synthesized optional_call; lower_stmt_expr_for_ir admits/lowers that call before narrowed IfLet tail; nonbuiltin optional calls decline at source macro',
    ('stmt_support_emitter/expr_call_metadata.rs', 'supports_nonempty_pop_narrowing_type_for_ir'): 'receiver representation predicate consumed by unwrap helper on already lowered builtin registry output; type shape alone supplies no admission',
    ('stmt_support_emitter/expr_call_metadata.rs', 'is_deque_class_name_for_ir'): 'basename representation predicate used by supports/unwrap and compiler_verified_pop; caller admission is required independently of basename',
    ('stmt_support_emitter/expr_call_metadata.rs', 'is_narrowable_pop_call_for_ir'): 'argument-shape predicate for already admitted unwrap/comparison consumers; pop()/pop(0)/popleft() recognition alone supplies no admission',
    ('stmt_support_emitter/expr_call_metadata.rs', 'compiler_verified_pop_lowers_as_option_for_ir'): 'comparison/condition representation predicate: scalar HIR retains Option only when matching canonical class method signature returns optional; statement macro lowers both operands through lower_stmt_expr_for_ir first; structured condition first validates both through try_lower_condition_operand_expr',
    ('stmt_support_emitter/expr_call_metadata.rs', 'unwrap_compiler_verified_nonempty_pop_result_for_ir'): 'admitted builtin registry output plus compiler nonempty fact; rewrite list/deque-data pop representation to remove/drain; ordinary deque declaration call stays unchanged; collection wrapper delegates already lowered input',
    ('intrinsic_method_emitters/collection_methods.rs', 'unwrap_compiler_verified_nonempty_pop_result'): 'delegates already lowered builtin registry output to expr_call_metadata result adaptation; invoked after lower_method_with_context in admitted unchecked collection registry',
    ('lower_stmt/condition_lowering.rs', 'condition_operand_lowers_as_option'): 'representation observation after both operands validate via try_lower_condition_operand_expr; narrowed deque predicate reads selected class method optional-return metadata; checked indexed len retains optional read carrier',
    ('stmt_support_emitter/stmt_expr_wrappers_and_compare.rs', 'macro_rules!::stmt_expr_contains_unary_compare_bool'): 'lower both comparison operands through lower_stmt_expr_for_ir before metadata representation predicates; adapt Option comparisons and bool/unary/contains Rust representation',
    ('lower_stmt/condition_lowering.rs', 'try_lower_structured_compare_condition_expr'): 'try_lower_condition_operand_expr validates both method operands before constant/Option comparison adaptation and metadata representation predicates',
}
ADAPTATIONS = {(CODEGEN + p, s): r for (p, s), r in ADAPTATIONS.items()}

# These scopes inspect HIR shapes or signatures; they produce analysis facts or
# binding policy, never replace a source call. Their caller graph is still bound.
ANALYSES = {
    ('body_analysis.rs', 'collect_expr_mutation'): 'walk HIR receiver/arguments and call conventions to record mutation effects; no call emission',
    ('checked_place/control_flow.rs', 'checked_place_refresh_precondition_holds'): 'inspect source statement mutation/place shape to invalidate or refresh witnesses; no source method replacement here',
    ('function_emitter/python_callback_bounds.rs', 'collect_python_callback_bound_names_expr'): 'walk HIR call/method operands to collect Python callback generic bounds; no source call emission',
    ('function_emitter/sifr_int_analysis.rs', 'hir_expr_returns_sifr_int_result'): 'inspect HIR and result method/signature sets to classify exact integer return representation; actual call lowering owns admission',
    ('helpers/helpers_impl.rs', 'is_self_field_mutating_method_call'): 'detect self-field method mutation shape for analysis; no call emission',
    ('hir_analysis/queries/queries_impl.rs', 'collect_mutated_vars'): 'walk HIR statements and signatures to collect mutated locals; no call emission',
    ('hir_analysis/queries/queries_impl.rs', 'collect_typevar_operator_requirements'): 'walk HIR to collect typevar operator bounds; no source-method semantics emission',
    ('body_analysis/length_aliases.rs', 'collect_stable_length_aliases'): 'stable length aliases for body analysis; checked sequence replacements separately require admitted len carriers',
    ('checked_place/control_flow.rs', 'checked_sequence_for_guards_for_ir'): 'loop-length recognition followed by checked sequence guard preparation; source length carriers are admitted by checked_sequence_read_guard_for_ir',
    ('checked_place/exit_guard_aliases.rs', 'alias_value'): 'record arithmetic/index/len shape aliases for exit guard analysis; no source-call emission',
    ('checked_place/exit_guards.rs', 'existing_prefix_witness_excludes_read'): 'recognize len equality after try_lower_checked_sequence_exit_guards_for_ir has admitted matching length carriers',
    ('checked_place.rs', 'condition_excludes_checked_sequence_read'): 'length/comparison shape facts; checked_sequence_read_guard_for_ir separately requires source builtin admission',
    ('checked_place.rs', 'condition_supports_checked_sequence_read'): 'length/comparison shape facts; checked_sequence_read_guard_for_ir separately requires source builtin admission',
    ('lower_stmt/simple_dispatch_and_bindings.rs', 'should_omit_local_type_annotation'): 'empty get default/constructor shape selects Rust binding annotation policy; ordinary value lowering owns source method admission',
    ('stmt_support_emitter/expr_call_metadata.rs', 'should_omit_local_type_annotation'): 'empty get default/constructor shape selects Rust binding annotation policy; ordinary value lowering owns source method admission',
    ('stmt_support_emitter/performance_lowering_gate.rs', 'dict_indexed_list_method_can_borrow'): 'select whether indexed pop/len/append needs performance lowering; does not emit the source method',
    ('stmt_support_emitter/performance_lowering_gate.rs', 'expr_shape_needs_performance_lowering'): 'select performance lowering necessity by HIR shape; source emitter admits selected method',
    ('stmt_support_emitter/stmt_block_helpers.rs', 'collect_string_loop_target_use_expr'): 'string loop target-use analysis; method-name recognition selects analysis validity, not source dispatch',
    ('string_char_cache_scan.rs', 'collect_string_len_call'): 'record string length cache demand from HIR; ordinary source method emitter separately admits len calls',
    ('intrinsic_method_emitters/plain_call_args.rs', 'registry_detect_is_some_guard_name'): 'identify HIR optional guard name for recursive call-argument typing; ordinary expression lowering owns source-call admission',
    ('lower_expr/collections_and_comprehensions.rs', 'detect_is_some_guard_name'): 'identify HIR optional guard name for comprehension bindings; ordinary lowering owns source-call admission',
    ('runtime_support_demand.rs', 'record_expr'): 'walk HIR to collect runtime support demand; no source method emission',
    ('stdlib_interop_demand.rs', 'expr_node'): 'walk HIR to collect stdlib interop demand; no source method emission',
    ('lib_runtime_needs.rs', 'expr_uses_join_set_runtime'): 'walk HIR to detect join-set runtime support demand; no source method emission',
}
ANALYSES = {(CODEGEN + p, s): r for (p, s), r in ANALYSES.items()}


def nodes():
    return {**CONSTITUENTS, **ADAPTATIONS, **ANALYSES}
ROUTERS = {
    ('lower_expr/leaves_and_plain_calls.rs', 'try_lower_leaf_expr'): 'HIR expression leaf lowering; source method carriers delegate to try_lower_simple_method_call_expr typed admission; constructor/plain-function branches retain their own lowering',
    ('operator_protocol_emitters.rs', 'lower_operator_expr_ir'): 'attempt lower_stmt_expr_for_ir then leaf lowering; failures/declines fall through to generic name-preserving source MethodCall Rust construction; no builtin-name specialization or guaranteed admission is claimed',
    ('stmt_support_emitter/await_and_async_comprehension.rs', 'coerce_local_value_for_target_type_for_ir'): 'coerce already lowered local value; __sifr_join_all/__sifr_cancel_all shape boxes an Awaitable result with Box::pin; source method dispatch is supplied by the prior value-lowering caller',
    ('stmt_support_emitter/condition_lowering.rs', 'try_lower_numeric_truthiness_condition_for_ir'): 'statement numeric truthiness lowering delegates source method operand through lower_stmt_expr_for_ir before checking/converting its Rust representation',
    ('stmt_support_emitter/iterator_lowering.rs', 'lower_escaping_iter_return_expr_for_ir'): 'escaping iterator representation selection from HIR and already lowered Rust input; source method call emission stays in ordinary lowering',
    ('stmt_support_emitter/print_calls.rs', 'try_lower_stmt_expr_statement_only'): 'statement-only source methods forward to lower_source_method_expr_for_ir, then typed source_method_path and builtin/nonbuiltin branches; print/iterator plain calls have separate ownership',
    ('stmt_support_emitter/stmt_expr_await_and_registry.rs', 'macro_rules!::stmt_expr_await_and_registry'): 'ordinary expression method forwarding invokes lower_source_method_expr_for_ir before plain registry handling; source method macro owns typed admission',
    ('stmt_support_emitter/stmt_expr_method_and_question_mark.rs', 'lower_stmt_expr_for_ir'): 'expression entry forwards MethodCall carriers to lower_source_method_expr_for_ir, preserving typed admission before performance specializations',
    ('stmt_support_emitter/stmt_expr_method_and_question_mark.rs', 'lower_source_method_expr_for_ir'): 'expands stmt_expr_method_call with discard context; macro admits through source_method_path before builtin semantics or nonbuiltin declaration dispatch',
}
ROUTERS = {(CODEGEN + p, s): r for (p, s), r in ROUTERS.items()}


def nodes():
    return {**CONSTITUENTS, **ADAPTATIONS, **ANALYSES, **ROUTERS}
