[package]
name = "sifr_lsp"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
sifr_analysis = { workspace = true }
sifr_diagnostics = { workspace = true }
sifr_driver = { workspace = true }
sifr_package = { workspace = true }
sifr_source = { workspace = true }
ruff_text_size = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = "3.27.0"

[lib]
doctest = false

[lints]
workspace = true
