[workspace]
members = ["rust/serde_derive", "rust/prost_build"]
resolver = "2"

[package]
name = "proc-macro-trust-package"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_derive = { path = "rust/serde_derive" }
prost-build = { path = "rust/prost_build" }

[package.metadata.sifr]
manifest = "sifr.toml"
