[workspace]
resolver = "3"

[package]
name = "crate-backed-view-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "=1.25.2" }
bytes = { version = "=1.11.1" }
memmap2 = { version = "=0.9.11" }
sifr_runtime = { path = "../../../../../../../crates/sifr_runtime" }
zerocopy = { version = "=0.8.48", features = ["derive"] }

[package.metadata.sifr]
manifest = "sifr.toml"
