use serde::Deserialize;
use sifr_package::{
    python_binding_source_fingerprint, PythonBindingDistribution, PythonBindingSource,
    PythonBindingSourceKind,
};
use std::collections::BTreeSet;
use std::fmt::Write as _;

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeReport {
    pub module: String,
    pub soabi: String,
    pub distribution: Option<PythonBindingDistribution>,
    pub symbols: Vec<PythonBindingProbeSymbol>,
    pub errors: Vec<PythonBindingProbeError>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeSymbol {
    pub declaration: PythonBindingDeclaration,
    pub source: PythonBindingProbeSource,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeSource {
    pub kind: PythonBindingSourceKind,
    pub identity: String,
    pub digest: String,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeError {
    pub symbol: String,
    pub reason: String,
    pub source: String,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingDeclaration {
    pub name: String,
    pub kind: PythonBindingDeclarationKind,
    #[serde(rename = "async")]
    pub is_async: bool,
    pub parameters: Vec<PythonBindingParameter>,
    pub return_type: Option<String>,
}

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PythonBindingDeclarationKind {
    Function,
    Class,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingParameter {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: String,
    pub kind: PythonBindingParameterKind,
    pub optional: bool,
}

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PythonBindingParameterKind {
    PositionalOnly,
    PositionalOrKeyword,
    Vararg,
    KeywordOnly,
    Kwarg,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PythonBindingScaffold {
    pub source: String,
    pub sources: Vec<PythonBindingSource>,
    pub source_fingerprint: String,
}

pub fn render_python_binding_scaffold(
    requested_module: &str,
    requested_symbols: &[String],
    report: &PythonBindingProbeReport,
) -> Result<PythonBindingScaffold, Vec<String>> {
    let mut errors = report
        .errors
        .iter()
        .map(|error| {
            format!(
                "unresolved Python binding symbol '{}': {} ({})",
                error.symbol, error.reason, error.source
            )
        })
        .collect::<Vec<_>>();
    if report.module != requested_module {
        errors.push("Python binding probe returned a different module".to_string());
    }
    if report.soabi.trim().is_empty() {
        errors.push("Python binding probe returned an empty SOABI".to_string());
    }
    let requested = requested_symbols.iter().cloned().collect::<BTreeSet<_>>();
    let returned = report
        .symbols
        .iter()
        .map(|symbol| symbol.declaration.name.clone())
        .collect::<BTreeSet<_>>();
    if returned != requested {
        errors
            .push("Python binding probe did not resolve exactly the requested symbols".to_string());
    }
    let class_names = report
        .symbols
        .iter()
        .filter(|symbol| symbol.declaration.kind == PythonBindingDeclarationKind::Class)
        .map(|symbol| symbol.declaration.name.as_str())
        .collect::<BTreeSet<_>>();
    for symbol in &report.symbols {
        validate_declaration(&symbol.declaration, &class_names, &mut errors);
    }
    if !errors.is_empty() {
        return Err(errors);
    }

    let mut sources = report
        .symbols
        .iter()
        .map(|symbol| PythonBindingSource {
            symbol: symbol.declaration.name.clone(),
            kind: symbol.source.kind,
            identity: symbol.source.identity.clone(),
            digest: symbol.source.digest.clone(),
        })
        .collect::<Vec<_>>();
    sources.sort_by(|left, right| left.symbol.cmp(&right.symbol));
    let source_fingerprint = python_binding_source_fingerprint(
        requested_module,
        requested_symbols,
        &report.soabi,
        report.distribution.as_ref(),
        &sources,
    );
    let mut source = format!(
        "# Generated by `sifr python bind`; review and check in this file.\n# source-fingerprint: {source_fingerprint}\n\nfrom sifr.python import PythonError\n"
    );
    let mut declarations = report.symbols.iter().collect::<Vec<_>>();
    declarations.sort_by(|left, right| left.declaration.name.cmp(&right.declaration.name));
    for symbol in declarations {
        source.push('\n');
        render_declaration(&mut source, requested_module, &symbol.declaration);
    }
    Ok(PythonBindingScaffold {
        source,
        sources,
        source_fingerprint,
    })
}

fn validate_declaration(
    declaration: &PythonBindingDeclaration,
    class_names: &BTreeSet<&str>,
    errors: &mut Vec<String>,
) {
    if !is_sifr_identifier(&declaration.name) {
        errors.push(format!(
            "Python symbol '{}' is not a valid Sifr declaration name",
            declaration.name
        ));
    }
    if declaration.kind == PythonBindingDeclarationKind::Class {
        if declaration.is_async
            || !declaration.parameters.is_empty()
            || declaration.return_type.is_some()
        {
            errors.push(format!(
                "Python class '{}' returned an invalid authoring shape",
                declaration.name
            ));
        }
        return;
    }
    let mut names = BTreeSet::new();
    let mut previous_rank = 0;
    for parameter in &declaration.parameters {
        if !is_sifr_identifier(&parameter.name) || !names.insert(parameter.name.as_str()) {
            errors.push(format!(
                "Python function '{}' has an invalid or duplicate parameter '{}'",
                declaration.name, parameter.name
            ));
        }
        let rank = parameter_kind_rank(parameter.kind);
        if rank < previous_rank {
            errors.push(format!(
                "Python function '{}' has parameters in an invalid order",
                declaration.name
            ));
        }
        previous_rank = rank;
        validate_type(&declaration.name, &parameter.ty, class_names, errors);
    }
    match declaration.return_type.as_deref() {
        Some(return_type) => validate_type(&declaration.name, return_type, class_names, errors),
        None => errors.push(format!(
            "Python function '{}' has no resolved return type",
            declaration.name
        )),
    }
}

fn validate_type(
    declaration: &str,
    ty: &str,
    class_names: &BTreeSet<&str>,
    errors: &mut Vec<String>,
) {
    let allowed = [
        "None", "bool", "bytes", "dict", "float", "int", "list", "set", "str", "tuple",
    ];
    let identifiers = ty
        .split(|character: char| !character.is_alphanumeric() && character != '_')
        .filter(|part| !part.is_empty());
    for identifier in identifiers {
        if !allowed.contains(&identifier) && !class_names.contains(identifier) {
            errors.push(format!(
                "Python function '{declaration}' uses unresolved type '{identifier}'"
            ));
        }
    }
}

fn render_declaration(output: &mut String, module: &str, declaration: &PythonBindingDeclaration) {
    match declaration.kind {
        PythonBindingDeclarationKind::Class => {
            let _ = writeln!(
                output,
                "@python.opaque(type={module}.{}, cleanup=drop)\nclass {}:\n    pass",
                declaration.name, declaration.name
            );
        }
        PythonBindingDeclarationKind::Function => {
            let decorator = if declaration.is_async {
                "python.coroutine"
            } else {
                "python"
            };
            let _ = writeln!(output, "@{decorator}({module}.{})", declaration.name);
            if declaration.is_async {
                output.push_str("async ");
            }
            let parameters = render_parameters(&declaration.parameters);
            let return_type = declaration.return_type.as_deref().unwrap_or("None");
            let _ = writeln!(
                output,
                "def {}({parameters}) -> Result[{return_type}, PythonError]: ...",
                declaration.name
            );
        }
    }
}

fn render_parameters(parameters: &[PythonBindingParameter]) -> String {
    let mut rendered = Vec::new();
    let has_vararg = parameters
        .iter()
        .any(|parameter| parameter.kind == PythonBindingParameterKind::Vararg);
    let mut inserted_keyword_marker = false;
    for parameter in parameters {
        if parameter.kind == PythonBindingParameterKind::KeywordOnly
            && !has_vararg
            && !inserted_keyword_marker
        {
            rendered.push("*".to_string());
            inserted_keyword_marker = true;
        }
        let prefix = match parameter.kind {
            PythonBindingParameterKind::Vararg => "*",
            PythonBindingParameterKind::Kwarg => "**",
            _ => "",
        };
        let default = if parameter.optional {
            " = python.omit"
        } else {
            ""
        };
        rendered.push(format!(
            "{prefix}{}: {}{default}",
            parameter.name, parameter.ty
        ));
    }
    rendered.join(", ")
}

const fn parameter_kind_rank(kind: PythonBindingParameterKind) -> u8 {
    match kind {
        PythonBindingParameterKind::PositionalOnly => 0,
        PythonBindingParameterKind::PositionalOrKeyword => 1,
        PythonBindingParameterKind::Vararg => 2,
        PythonBindingParameterKind::KeywordOnly => 3,
        PythonBindingParameterKind::Kwarg => 4,
    }
}

fn is_sifr_identifier(value: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del",
        "elif", "else", "except", "False", "finally", "for", "from", "global", "if", "import",
        "in", "is", "lambda", "None", "nonlocal", "not", "or", "pass", "raise", "return", "True",
        "try", "while", "with", "yield",
    ];
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|first| first == '_' || first.is_alphabetic())
        && chars.all(|character| character == '_' || character.is_alphanumeric())
        && !KEYWORDS.contains(&value)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_typed_sync_async_class_and_parameter_shapes() {
        let report = PythonBindingProbeReport {
            module: "sample.api".to_string(),
            soabi: "cpython-test".to_string(),
            distribution: None,
            symbols: vec![
                symbol(
                    "Client",
                    PythonBindingDeclarationKind::Class,
                    false,
                    vec![],
                    None,
                ),
                symbol(
                    "fetch",
                    PythonBindingDeclarationKind::Function,
                    true,
                    vec![
                        parameter(
                            "path",
                            "str",
                            PythonBindingParameterKind::PositionalOnly,
                            false,
                        ),
                        parameter(
                            "limit",
                            "int",
                            PythonBindingParameterKind::KeywordOnly,
                            true,
                        ),
                    ],
                    Some("list[str]"),
                ),
            ],
            errors: vec![],
        };
        let scaffold = render_python_binding_scaffold(
            "sample.api",
            &["Client".to_string(), "fetch".to_string()],
            &report,
        )
        .expect("typed report should render");
        assert!(scaffold.source.contains("class Client:\n    pass"));
        assert!(scaffold.source.contains(
            "async def fetch(path: str, *, limit: int = python.omit) -> Result[list[str], PythonError]: ..."
        ));
    }

    #[test]
    fn rejects_unresolved_and_untyped_shapes() {
        let report = PythonBindingProbeReport {
            module: "sample".to_string(),
            soabi: "cpython-test".to_string(),
            distribution: None,
            symbols: vec![symbol(
                "load",
                PythonBindingDeclarationKind::Function,
                false,
                vec![parameter(
                    "value",
                    "Unknown",
                    PythonBindingParameterKind::PositionalOrKeyword,
                    false,
                )],
                Some("int"),
            )],
            errors: vec![PythonBindingProbeError {
                symbol: "other".to_string(),
                reason: "untyped boundary 'Any' is forbidden".to_string(),
                source: "override:test.pyi".to_string(),
            }],
        };
        let errors = render_python_binding_scaffold(
            "sample",
            &["load".to_string(), "other".to_string()],
            &report,
        )
        .expect_err("untyped reports must fail closed");
        assert!(errors.iter().any(|error| error.contains("Any")));
        assert!(errors.iter().any(|error| error.contains("Unknown")));
    }

    fn symbol(
        name: &str,
        kind: PythonBindingDeclarationKind,
        is_async: bool,
        parameters: Vec<PythonBindingParameter>,
        return_type: Option<&str>,
    ) -> PythonBindingProbeSymbol {
        PythonBindingProbeSymbol {
            declaration: PythonBindingDeclaration {
                name: name.to_string(),
                kind,
                is_async,
                parameters,
                return_type: return_type.map(str::to_string),
            },
            source: PythonBindingProbeSource {
                kind: PythonBindingSourceKind::Override,
                identity: format!("override:{name}.pyi"),
                digest: "a".repeat(64),
            },
        }
    }

    fn parameter(
        name: &str,
        ty: &str,
        kind: PythonBindingParameterKind,
        optional: bool,
    ) -> PythonBindingParameter {
        PythonBindingParameter {
            name: name.to_string(),
            ty: ty.to_string(),
            kind,
            optional,
        }
    }
}
