use serde::Deserialize;
use sifr_package::{
    python_binding_source_fingerprint, PythonBindingDistribution, PythonBindingSource,
    PythonBindingSourceKind,
};
use std::collections::BTreeSet;
use std::fmt::Write as _;

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeReport {
    pub module: String,
    pub soabi: String,
    pub distribution: Option<PythonBindingDistribution>,
    pub symbols: Vec<PythonBindingProbeSymbol>,
    pub errors: Vec<PythonBindingProbeError>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeSymbol {
    pub declaration: PythonBindingDeclaration,
    pub source: PythonBindingProbeSource,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeSource {
    pub kind: PythonBindingSourceKind,
    pub identity: String,
    pub digest: String,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingProbeError {
    pub symbol: String,
    pub reason: String,
    pub source: String,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingDeclaration {
    pub name: String,
    pub kind: PythonBindingDeclarationKind,
    #[serde(rename = "async")]
    pub is_async: bool,
    pub parameters: Vec<PythonBindingParameter>,
    pub return_type: Option<String>,
}

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PythonBindingDeclarationKind {
    Function,
    Class,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct PythonBindingParameter {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: String,
    pub kind: PythonBindingParameterKind,
    pub optional: bool,
}

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PythonBindingParameterKind {
    PositionalOnly,
    PositionalOrKeyword,
    Vararg,
    KeywordOnly,
    Kwarg,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PythonBindingScaffold {
    pub source: String,
    pub sources: Vec<PythonBindingSource>,
    pub source_fingerprint: String,
}

pub fn render_python_binding_scaffold(
    requested_module: &str,
    requested_symbols: &[String],
    report: &PythonBindingProbeReport,
) -> Result<PythonBindingScaffold, Vec<String>> {
    let mut errors = report
        .errors
        .iter()
        .map(|error| {
            format!(
                "unresolved Python binding symbol '{}': {} ({})",
                error.symbol, error.reason, error.source
            )
        })
        .collect::<Vec<_>>();
    if report.module != requested_module {
        errors.push("Python binding probe returned a different module".to_string());
    }
    if report.soabi.trim().is_empty() {
        errors.push("Python binding probe returned an empty SOABI".to_string());
    }
    let requested = requested_symbols.iter().cloned().collect::<BTreeSet<_>>();
    let returned = report
        .symbols
        .iter()
        .map(|symbol| symbol.declaration.name.clone())
        .collect::<BTreeSet<_>>();
    if returned != requested {
        errors
            .push("Python binding probe did not resolve exactly the requested symbols".to_string());
    }
    let class_names = report
        .symbols
        .iter()
        .filter(|symbol| symbol.declaration.kind == PythonBindingDeclarationKind::Class)
        .map(|symbol| symbol.declaration.name.as_str())
        .collect::<BTreeSet<_>>();
    for symbol in &report.symbols {
        validate_declaration(
            &symbol.declaration,
            &report.module,
            &class_names,
            &mut errors,
        );
    }
    if !errors.is_empty() {
        return Err(errors);
    }

    let mut sources = report
        .symbols
        .iter()
        .map(|symbol| PythonBindingSource {
            symbol: symbol.declaration.name.clone(),
            kind: symbol.source.kind,
            identity: symbol.source.identity.clone(),
            digest: symbol.source.digest.clone(),
        })
        .collect::<Vec<_>>();
    sources.sort_by(|left, right| left.symbol.cmp(&right.symbol));
    let source_fingerprint = python_binding_source_fingerprint(
        requested_module,
        requested_symbols,
        &report.soabi,
        report.distribution.as_ref(),
        &sources,
    );
    let mut source = format!(
        "# Generated by `sifr python bind`; review and check in this file.\n# source-fingerprint: {source_fingerprint}\n\nfrom sifr.python import PythonError\n"
    );
    let mut declarations = report.symbols.iter().collect::<Vec<_>>();
    declarations.sort_by(|left, right| left.declaration.name.cmp(&right.declaration.name));
    for symbol in declarations {
        source.push('\n');
        render_declaration(
            &mut source,
            requested_module,
            &class_names,
            &symbol.declaration,
        );
    }
    Ok(PythonBindingScaffold {
        source,
        sources,
        source_fingerprint,
    })
}

fn validate_declaration(
    declaration: &PythonBindingDeclaration,
    module: &str,
    class_names: &BTreeSet<&str>,
    errors: &mut Vec<String>,
) {
    if !is_sifr_identifier(&declaration.name) {
        errors.push(format!(
            "Python symbol '{}' is not a valid Sifr declaration name",
            declaration.name
        ));
    }
    if declaration.kind == PythonBindingDeclarationKind::Class {
        if declaration.is_async
            || !declaration.parameters.is_empty()
            || declaration.return_type.is_some()
        {
            errors.push(format!(
                "Python class '{}' returned an invalid authoring shape",
                declaration.name
            ));
        }
        return;
    }
    let mut names = BTreeSet::new();
    let mut previous_rank = 0;
    for parameter in &declaration.parameters {
        if !is_sifr_identifier(&parameter.name) || !names.insert(parameter.name.as_str()) {
            errors.push(format!(
                "Python function '{}' has an invalid or duplicate parameter '{}'",
                declaration.name, parameter.name
            ));
        }
        if parameter.kind == PythonBindingParameterKind::PositionalOnly && parameter.optional {
            errors.push(format!(
                "Python function '{}' has optional positional-only parameter '{}', which cannot be represented by the declaration call plan",
                declaration.name, parameter.name
            ));
        }
        let rank = parameter_kind_rank(parameter.kind);
        if rank < previous_rank {
            errors.push(format!(
                "Python function '{}' has parameters in an invalid order",
                declaration.name
            ));
        }
        previous_rank = rank;
        validate_type(
            &declaration.name,
            &parameter.ty,
            module,
            class_names,
            errors,
        );
    }
    match declaration.return_type.as_deref() {
        Some(return_type) => {
            validate_type(&declaration.name, return_type, module, class_names, errors);
        }
        None => errors.push(format!(
            "Python function '{}' has no resolved return type",
            declaration.name
        )),
    }
}

fn validate_type(
    declaration: &str,
    ty: &str,
    module: &str,
    class_names: &BTreeSet<&str>,
    errors: &mut Vec<String>,
) {
    if normalize_direct_type(ty, module, class_names, true).is_none() {
        errors.push(format!(
            "Python function '{declaration}' uses unresolved or unsupported direct-conversion type '{ty}'"
        ));
    }
}

fn normalize_direct_type(
    ty: &str,
    module: &str,
    class_names: &BTreeSet<&str>,
    allow_option: bool,
) -> Option<String> {
    let ty = ty.trim();
    if matches!(ty, "None" | "bool" | "bytes" | "float" | "int" | "str") {
        return Some(ty.to_string());
    }
    if class_names.contains(ty) {
        return Some(ty.to_string());
    }
    if let Some(local_name) = ty.strip_prefix(&format!("{module}.")) {
        if class_names.contains(local_name) {
            return Some(local_name.to_string());
        }
    }

    let union_parts = split_top_level(ty, '|')?;
    if union_parts.len() > 1 {
        if !allow_option
            || union_parts.len() != 2
            || union_parts.iter().filter(|part| **part == "None").count() != 1
        {
            return None;
        }
        let value = union_parts.iter().find(|part| **part != "None")?;
        let normalized = normalize_direct_type(value, module, class_names, false)?;
        return Some(format!("{normalized} | None"));
    }

    let open = ty.find('[')?;
    if !ty.ends_with(']') {
        return None;
    }
    let base = ty[..open].trim();
    let arguments = split_top_level(&ty[open + 1..ty.len() - 1], ',')?;
    match base {
        "list" if arguments.len() == 1 => {
            normalize_direct_type(arguments[0], module, class_names, true)
                .map(|argument| format!("list[{argument}]"))
        }
        "tuple" if !arguments.is_empty() => arguments
            .iter()
            .map(|argument| normalize_direct_type(argument, module, class_names, true))
            .collect::<Option<Vec<_>>>()
            .map(|arguments| format!("tuple[{}]", arguments.join(", "))),
        "dict" if arguments.len() == 2 && arguments[0] == "str" => {
            normalize_direct_type(arguments[1], module, class_names, true)
                .map(|value| format!("dict[str, {value}]"))
        }
        _ => None,
    }
}

fn split_top_level(value: &str, separator: char) -> Option<Vec<&str>> {
    let mut depth = 0_u32;
    let mut start = 0;
    let mut parts = Vec::new();
    for (index, character) in value.char_indices() {
        match character {
            '[' => depth = depth.checked_add(1)?,
            ']' => depth = depth.checked_sub(1)?,
            current if current == separator && depth == 0 => {
                let part = value[start..index].trim();
                if part.is_empty() {
                    return None;
                }
                parts.push(part);
                start = index + character.len_utf8();
            }
            _ => {}
        }
    }
    if depth != 0 {
        return None;
    }
    let part = value[start..].trim();
    if part.is_empty() {
        return None;
    }
    parts.push(part);
    Some(parts)
}

fn render_declaration(
    output: &mut String,
    module: &str,
    class_names: &BTreeSet<&str>,
    declaration: &PythonBindingDeclaration,
) {
    match declaration.kind {
        PythonBindingDeclarationKind::Class => {
            let _ = writeln!(
                output,
                "@python.opaque(type={module}.{}, cleanup=drop)\nclass {}:\n    pass",
                declaration.name, declaration.name
            );
        }
        PythonBindingDeclarationKind::Function => {
            let decorator = if declaration.is_async {
                "python.coroutine"
            } else {
                "python"
            };
            let _ = writeln!(output, "@{decorator}({module}.{})", declaration.name);
            if declaration.is_async {
                output.push_str("async ");
            }
            let parameters = render_parameters(&declaration.parameters, module, class_names);
            let raw_return_type = declaration.return_type.as_deref().unwrap_or("None");
            let return_type = normalize_direct_type(raw_return_type, module, class_names, true)
                .unwrap_or_else(|| raw_return_type.to_string());
            let _ = writeln!(
                output,
                "def {}({parameters}) -> Result[{return_type}, PythonError]: ...",
                declaration.name
            );
        }
    }
}

fn render_parameters(
    parameters: &[PythonBindingParameter],
    module: &str,
    class_names: &BTreeSet<&str>,
) -> String {
    let mut rendered = Vec::new();
    let has_vararg = parameters
        .iter()
        .any(|parameter| parameter.kind == PythonBindingParameterKind::Vararg);
    let mut inserted_keyword_marker = false;
    for parameter in parameters {
        if parameter.kind == PythonBindingParameterKind::KeywordOnly
            && !has_vararg
            && !inserted_keyword_marker
        {
            rendered.push("*".to_string());
            inserted_keyword_marker = true;
        }
        let prefix = match parameter.kind {
            PythonBindingParameterKind::Vararg => "*",
            PythonBindingParameterKind::Kwarg => "**",
            _ => "",
        };
        let default = if parameter.optional {
            " = python.omit"
        } else {
            ""
        };
        let ty = normalize_direct_type(&parameter.ty, module, class_names, true)
            .unwrap_or_else(|| parameter.ty.clone());
        rendered.push(format!("{prefix}{}: {ty}{default}", parameter.name));
    }
    rendered.join(", ")
}

const fn parameter_kind_rank(kind: PythonBindingParameterKind) -> u8 {
    match kind {
        PythonBindingParameterKind::PositionalOnly => 0,
        PythonBindingParameterKind::PositionalOrKeyword => 1,
        PythonBindingParameterKind::Vararg => 2,
        PythonBindingParameterKind::KeywordOnly => 3,
        PythonBindingParameterKind::Kwarg => 4,
    }
}

fn is_sifr_identifier(value: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del",
        "elif", "else", "except", "False", "finally", "for", "from", "global", "if", "import",
        "in", "is", "lambda", "None", "nonlocal", "not", "or", "pass", "raise", "return", "True",
        "try", "while", "with", "yield",
    ];
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|first| first == '_' || first.is_alphabetic())
        && chars.all(|character| character == '_' || character.is_alphanumeric())
        && !KEYWORDS.contains(&value)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_typed_sync_async_class_and_parameter_shapes() {
        let report = PythonBindingProbeReport {
            module: "sample.api".to_string(),
            soabi: "cpython-test".to_string(),
            distribution: None,
            symbols: vec![
                symbol(
                    "Client",
                    PythonBindingDeclarationKind::Class,
                    false,
                    vec![],
                    None,
                ),
                symbol(
                    "fetch",
                    PythonBindingDeclarationKind::Function,
                    true,
                    vec![
                        parameter(
                            "path",
                            "str",
                            PythonBindingParameterKind::PositionalOnly,
                            false,
                        ),
                        parameter(
                            "limit",
                            "int",
                            PythonBindingParameterKind::KeywordOnly,
                            true,
                        ),
                    ],
                    Some("list[str]"),
                ),
            ],
            errors: vec![],
        };
        let scaffold = render_python_binding_scaffold(
            "sample.api",
            &["Client".to_string(), "fetch".to_string()],
            &report,
        )
        .expect("typed report should render");
        assert!(scaffold.source.contains("class Client:\n    pass"));
        assert!(scaffold.source.contains(
            "async def fetch(path: str, *, limit: int = python.omit) -> Result[list[str], PythonError]: ..."
        ));
    }

    #[test]
    fn rejects_unresolved_and_untyped_shapes() {
        let report = PythonBindingProbeReport {
            module: "sample".to_string(),
            soabi: "cpython-test".to_string(),
            distribution: None,
            symbols: vec![symbol(
                "load",
                PythonBindingDeclarationKind::Function,
                false,
                vec![parameter(
                    "value",
                    "Unknown",
                    PythonBindingParameterKind::PositionalOrKeyword,
                    false,
                )],
                Some("int"),
            )],
            errors: vec![PythonBindingProbeError {
                symbol: "other".to_string(),
                reason: "untyped boundary 'Any' is forbidden".to_string(),
                source: "override:test.pyi".to_string(),
            }],
        };
        let errors = render_python_binding_scaffold(
            "sample",
            &["load".to_string(), "other".to_string()],
            &report,
        )
        .expect_err("untyped reports must fail closed");
        assert!(errors.iter().any(|error| error.contains("Any")));
        assert!(errors.iter().any(|error| error.contains("Unknown")));
    }

    #[test]
    fn rejects_optional_positional_only_parameters() {
        let report = PythonBindingProbeReport {
            module: "sample".to_string(),
            soabi: "cpython-test".to_string(),
            distribution: None,
            symbols: vec![symbol(
                "pow",
                PythonBindingDeclarationKind::Function,
                false,
                vec![parameter(
                    "exponent",
                    "float",
                    PythonBindingParameterKind::PositionalOnly,
                    true,
                )],
                Some("float"),
            )],
            errors: vec![],
        };
        let errors = render_python_binding_scaffold("sample", &["pow".to_string()], &report)
            .expect_err("optional positional-only declarations must fail closed");
        assert!(errors
            .iter()
            .any(|error| { error.contains("optional positional-only parameter 'exponent'") }));
    }

    #[test]
    fn normalizes_same_module_qualified_class_annotations_in_scaffolds() {
        let report = PythonBindingProbeReport {
            module: "sample.api".to_string(),
            soabi: "cpython-test".to_string(),
            distribution: None,
            symbols: vec![
                symbol(
                    "Client",
                    PythonBindingDeclarationKind::Class,
                    false,
                    vec![],
                    None,
                ),
                symbol(
                    "use_client",
                    PythonBindingDeclarationKind::Function,
                    false,
                    vec![parameter(
                        "client",
                        "sample.api.Client",
                        PythonBindingParameterKind::PositionalOrKeyword,
                        false,
                    )],
                    Some("list[sample.api.Client]"),
                ),
            ],
            errors: vec![],
        };

        let scaffold = render_python_binding_scaffold(
            "sample.api",
            &["Client".to_string(), "use_client".to_string()],
            &report,
        )
        .expect("same-module annotations should render");
        assert!(scaffold
            .source
            .contains("def use_client(client: Client) -> Result[list[Client], PythonError]: ..."));
    }

    #[test]
    fn rejects_bare_list_direct_conversion_type() {
        assert_unsupported_type_rejected("list");
    }

    #[test]
    fn rejects_set_direct_conversion_type() {
        assert_unsupported_type_rejected("set[int]");
    }

    #[test]
    fn rejects_non_string_dict_key_direct_conversion_type() {
        assert_unsupported_type_rejected("dict[int, str]");
    }

    #[test]
    fn accepts_the_recursive_direct_conversion_grammar() {
        let classes = BTreeSet::from(["Client"]);
        for ty in [
            "None",
            "int",
            "Client",
            "sample.Client",
            "Client | None",
            "list[tuple[int, str | None]]",
            "dict[str, list[Client]]",
        ] {
            let mut errors = Vec::new();
            validate_type("load", ty, "sample", &classes, &mut errors);
            assert!(errors.is_empty(), "{ty}: {errors:?}");
        }
        assert_eq!(
            normalize_direct_type("list[sample.Client]", "sample", &classes, true),
            Some("list[Client]".to_string())
        );
        assert!(normalize_direct_type("other.Client", "sample", &classes, true).is_none());
    }

    fn assert_unsupported_type_rejected(ty: &str) {
        let mut errors = Vec::new();
        validate_type("load", ty, "sample", &BTreeSet::new(), &mut errors);
        assert!(errors.iter().any(|error| error.contains(ty)), "{errors:?}");
    }

    fn symbol(
        name: &str,
        kind: PythonBindingDeclarationKind,
        is_async: bool,
        parameters: Vec<PythonBindingParameter>,
        return_type: Option<&str>,
    ) -> PythonBindingProbeSymbol {
        PythonBindingProbeSymbol {
            declaration: PythonBindingDeclaration {
                name: name.to_string(),
                kind,
                is_async,
                parameters,
                return_type: return_type.map(str::to_string),
            },
            source: PythonBindingProbeSource {
                kind: PythonBindingSourceKind::Override,
                identity: format!("override:{name}.pyi"),
                digest: "a".repeat(64),
            },
        }
    }

    fn parameter(
        name: &str,
        ty: &str,
        kind: PythonBindingParameterKind,
        optional: bool,
    ) -> PythonBindingParameter {
        PythonBindingParameter {
            name: name.to_string(),
            ty: ty.to_string(),
            kind,
            optional,
        }
    }
}
