[package]
name = "sifr_hir"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
sifr_python_ast = { workspace = true }
sifr_python_parser = { workspace = true }
sifr_type_system = { workspace = true }
ruff_text_size = { workspace = true }
rust_decimal = "1"
bigdecimal = "0.4"

[dev-dependencies]

[lints]
workspace = true
