// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::HirModule>> for sifr_ir::HirModule {
    fn decode(reference: &wire::Ref<wire::HirModule>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                functions: Decode::decode(&value.functions, cx)?,
                classes: Decode::decode(&value.classes, cx)?,
                imports: Decode::decode(&value.imports, cx)?,
                constants: Decode::decode(&value.constants, cx)?,
                generic_functions: Decode::decode(&value.generic_functions, cx)?,
                type_param_bounds: Decode::decode(&value.type_param_bounds, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirImport>> for sifr_ir::HirImport {
    fn decode(reference: &wire::Ref<wire::HirImport>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                module: Decode::decode(&value.module, cx)?,
                names: Decode::decode(&value.names, cx)?,
                aliases: Decode::decode(&value.aliases, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirClassKind>> for sifr_ir::HirClassKind {
    fn decode(reference: &wire::Ref<wire::HirClassKind>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirClassKind::Regular => Self::Regular,
                wire::HirClassKind::Protocol => Self::Protocol,
                wire::HirClassKind::Enum => Self::Enum,
                wire::HirClassKind::PythonOpaque(v0) => Self::PythonOpaque(Decode::decode(v0, cx)?),
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirClass>> for sifr_ir::HirClass {
    fn decode(reference: &wire::Ref<wire::HirClass>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                name: Decode::decode(&value.name, cx)?,
                identity: Decode::decode(&value.identity, cx)?,
                fields: Decode::decode(&value.fields, cx)?,
                field_defaults: Decode::decode(&value.field_defaults, cx)?,
                field_default_identities: Decode::decode(&value.field_default_identities, cx)?,
                declaration_metadata: Decode::decode(&value.declaration_metadata, cx)?,
                methods: Decode::decode(&value.methods, cx)?,
                is_hashable: Decode::decode(&value.is_hashable, cx)?,
                is_error_type: Decode::decode(&value.is_error_type, cx)?,
                kind: Decode::decode(&value.kind, cx)?,
                operator_impls: Decode::decode(&value.operator_impls, cx)?,
                newtype_inner: Decode::decode(&value.newtype_inner, cx)?,
                implements_protocols: Decode::decode(&value.implements_protocols, cx)?,
                parent_class: Decode::decode(&value.parent_class, cx)?,
                parent_type: Decode::decode(&value.parent_type, cx)?,
                type_params: Decode::decode(&value.type_params, cx)?,
                enum_variants: Decode::decode(&value.enum_variants, cx)?,
                rust_interop: Decode::decode(&value.rust_interop, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::MethodKind>> for sifr_ir::MethodKind {
    fn decode(reference: &wire::Ref<wire::MethodKind>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::MethodKind::Regular => Self::Regular,
                wire::MethodKind::ClassMethod => Self::ClassMethod,
                wire::MethodKind::StaticMethod => Self::StaticMethod,
            })
        })
    }
}
impl Decode<wire::Ref<wire::MethodCallSource>> for sifr_ir::MethodCallSource {
    fn decode(reference: &wire::Ref<wire::MethodCallSource>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                call_range: Decode::decode(&value.call_range, cx)?,
                receiver_range: Decode::decode(&value.receiver_range, cx)?,
                arg_ranges: Decode::decode(&value.arg_ranges, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::FieldIdentity>> for sifr_ir::FieldIdentity {
    fn decode(reference: &wire::Ref<wire::FieldIdentity>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                declaring_class: Decode::decode(&value.declaring_class, cx)?,
                field: Decode::decode(&value.field, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PlaceProjection>> for sifr_ir::PlaceProjection {
    fn decode(reference: &wire::Ref<wire::PlaceProjection>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PlaceProjection::Field(v0) => Self::Field(Decode::decode(v0, cx)?),
            })
        })
    }
}
impl Decode<wire::Ref<wire::Place>> for sifr_ir::Place {
    fn decode(reference: &wire::Ref<wire::Place>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                root: Decode::decode(&value.root, cx)?,
                projections: Decode::decode(&value.projections, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::MutableReceiverTarget>> for sifr_ir::MutableReceiverTarget {
    fn decode(
        reference: &wire::Ref<wire::MutableReceiverTarget>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::MutableReceiverTarget::Place(v0) => Self::Place(Decode::decode(v0, cx)?),
                wire::MutableReceiverTarget::OwnedTemporary => Self::OwnedTemporary,
                wire::MutableReceiverTarget::SpecializedIndexedStorage(v0) => {
                    Self::SpecializedIndexedStorage(Decode::decode(v0, cx)?)
                }
            })
        })
    }
}
impl Decode<wire::Ref<wire::MutableArgumentTarget>> for sifr_ir::MutableArgumentTarget {
    fn decode(
        reference: &wire::Ref<wire::MutableArgumentTarget>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::MutableArgumentTarget::Place(v0) => Self::Place(Decode::decode(v0, cx)?),
                wire::MutableArgumentTarget::OwnedTemporary => Self::OwnedTemporary,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirFunction>> for sifr_ir::HirFunction {
    fn decode(reference: &wire::Ref<wire::HirFunction>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                name: Decode::decode(&value.name, cx)?,
                params: Decode::decode(&value.params, cx)?,
                return_type: Decode::decode(&value.return_type, cx)?,
                body: Decode::decode(&value.body, cx)?,
                is_async: Decode::decode(&value.is_async, cx)?,
                method_kind: Decode::decode(&value.method_kind, cx)?,
                receiver: Decode::decode(&value.receiver, cx)?,
                decorators: Decode::decode(&value.decorators, cx)?,
                rust_interop: Decode::decode(&value.rust_interop, cx)?,
                python_interop: Decode::decode(&value.python_interop, cx)?,
                compiler_intrinsic: Decode::decode(&value.compiler_intrinsic, cx)?,
                type_params: Decode::decode(&value.type_params, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::CompilerIntrinsicId>> for sifr_ir::CompilerIntrinsicId {
    fn decode(reference: &wire::Ref<wire::CompilerIntrinsicId>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::CompilerIntrinsicId::TestAssertEqual => Self::TestAssertEqual,
                wire::CompilerIntrinsicId::TestAssertNotEqual => Self::TestAssertNotEqual,
                wire::CompilerIntrinsicId::TestAssertTrue => Self::TestAssertTrue,
                wire::CompilerIntrinsicId::TestAssertFalse => Self::TestAssertFalse,
                wire::CompilerIntrinsicId::TestAssertAlmostEqual => Self::TestAssertAlmostEqual,
                wire::CompilerIntrinsicId::TestAssertGreaterThan => Self::TestAssertGreaterThan,
                wire::CompilerIntrinsicId::TestAssertLessThan => Self::TestAssertLessThan,
                wire::CompilerIntrinsicId::OpenBinary => Self::OpenBinary,
                wire::CompilerIntrinsicId::OpenText => Self::OpenText,
                wire::CompilerIntrinsicId::BytesFromHex => Self::BytesFromHex,
                wire::CompilerIntrinsicId::BytesWithSize => Self::BytesWithSize,
                wire::CompilerIntrinsicId::BytesFromIntegers => Self::BytesFromIntegers,
                wire::CompilerIntrinsicId::StringEncode => Self::StringEncode,
                wire::CompilerIntrinsicId::StringEncodeWithEncoding => {
                    Self::StringEncodeWithEncoding
                }
                wire::CompilerIntrinsicId::BytesDecode => Self::BytesDecode,
                wire::CompilerIntrinsicId::BytesDecodeWithEncoding => Self::BytesDecodeWithEncoding,
                wire::CompilerIntrinsicId::TaskCurrentContext => Self::TaskCurrentContext,
                wire::CompilerIntrinsicId::PythonFromValue => Self::PythonFromValue,
                wire::CompilerIntrinsicId::PythonToValue => Self::PythonToValue,
                wire::CompilerIntrinsicId::PythonKwarg => Self::PythonKwarg,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirAsyncWithKind>> for sifr_ir::HirAsyncWithKind {
    fn decode(reference: &wire::Ref<wire::HirAsyncWithKind>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirAsyncWithKind::TaskScope => Self::TaskScope,
                wire::HirAsyncWithKind::TaskGroup { context } => Self::TaskGroup {
                    context: Decode::decode(context, cx)?,
                },
                wire::HirAsyncWithKind::TaskTimeout { duration } => Self::TaskTimeout {
                    duration: Decode::decode(duration, cx)?,
                },
                wire::HirAsyncWithKind::UserDefined {
                    context,
                    enter_value_ty,
                    enter_error_ty,
                    exit_error_ty,
                    active_error_ty,
                    body_may_raise,
                } => Self::UserDefined {
                    context: Decode::decode(context, cx)?,
                    enter_value_ty: Decode::decode(enter_value_ty, cx)?,
                    enter_error_ty: Decode::decode(enter_error_ty, cx)?,
                    exit_error_ty: Decode::decode(exit_error_ty, cx)?,
                    active_error_ty: Decode::decode(active_error_ty, cx)?,
                    body_may_raise: Decode::decode(body_may_raise, cx)?,
                },
                wire::HirAsyncWithKind::Python {
                    context,
                    manager_class,
                    entered_type,
                    enter_error_type,
                    exit_error_type,
                    entered_is_opaque_borrow,
                    active_error_type,
                    body_may_raise,
                } => Self::Python {
                    context: Decode::decode(context, cx)?,
                    manager_class: Decode::decode(manager_class, cx)?,
                    entered_type: Decode::decode(entered_type, cx)?,
                    enter_error_type: Decode::decode(enter_error_type, cx)?,
                    exit_error_type: Decode::decode(exit_error_type, cx)?,
                    entered_is_opaque_borrow: Decode::decode(entered_is_opaque_borrow, cx)?,
                    active_error_type: Decode::decode(active_error_type, cx)?,
                    body_may_raise: Decode::decode(body_may_raise, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirWithItemKind>> for sifr_ir::HirWithItemKind {
    fn decode(reference: &wire::Ref<wire::HirWithItemKind>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirWithItemKind::Native {
                    has_context_manager_protocol,
                } => Self::Native {
                    has_context_manager_protocol: Decode::decode(has_context_manager_protocol, cx)?,
                },
                wire::HirWithItemKind::Python {
                    entered_type,
                    enter_error_type,
                    exit_error_type,
                    entered_is_opaque_borrow,
                    body_may_raise,
                } => Self::Python {
                    entered_type: Decode::decode(entered_type, cx)?,
                    enter_error_type: Decode::decode(enter_error_type, cx)?,
                    exit_error_type: Decode::decode(exit_error_type, cx)?,
                    entered_is_opaque_borrow: Decode::decode(entered_is_opaque_borrow, cx)?,
                    body_may_raise: Decode::decode(body_may_raise, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirWithItem>> for sifr_ir::HirWithItem {
    fn decode(reference: &wire::Ref<wire::HirWithItem>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                target: Decode::decode(&value.target, cx)?,
                context: Decode::decode(&value.context, cx)?,
                kind: Decode::decode(&value.kind, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirParam>> for sifr_ir::HirParam {
    fn decode(reference: &wire::Ref<wire::HirParam>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                name: Decode::decode(&value.name, cx)?,
                ty: Decode::decode(&value.ty, cx)?,
                default: Decode::decode(&value.default, cx)?,
                keyword_only: Decode::decode(&value.keyword_only, cx)?,
                convention: Decode::decode(&value.convention, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirStmt>> for sifr_ir::HirStmt {
    fn decode(reference: &wire::Ref<wire::HirStmt>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirStmt::Let {
                    name,
                    ty,
                    value,
                    is_mutable,
                } => Self::Let {
                    name: Decode::decode(name, cx)?,
                    ty: Decode::decode(ty, cx)?,
                    value: Decode::decode(value, cx)?,
                    is_mutable: Decode::decode(is_mutable, cx)?,
                },
                wire::HirStmt::Assign { name, value } => Self::Assign {
                    name: Decode::decode(name, cx)?,
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::AugAssign { name, op, value } => Self::AugAssign {
                    name: Decode::decode(name, cx)?,
                    op: Decode::decode(op, cx)?,
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::Return { value } => Self::Return {
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::Expr { expr } => Self::Expr {
                    expr: Decode::decode(expr, cx)?,
                },
                wire::HirStmt::If {
                    condition,
                    then_body,
                    elif_clauses,
                    else_body,
                } => Self::If {
                    condition: Decode::decode(condition, cx)?,
                    then_body: Decode::decode(then_body, cx)?,
                    elif_clauses: Decode::decode(elif_clauses, cx)?,
                    else_body: Decode::decode(else_body, cx)?,
                },
                wire::HirStmt::While {
                    condition,
                    body,
                    else_body,
                } => Self::While {
                    condition: Decode::decode(condition, cx)?,
                    body: Decode::decode(body, cx)?,
                    else_body: Decode::decode(else_body, cx)?,
                },
                wire::HirStmt::For {
                    target,
                    target_ty,
                    iter,
                    body,
                    else_body,
                } => Self::For {
                    target: Decode::decode(target, cx)?,
                    target_ty: Decode::decode(target_ty, cx)?,
                    iter: Decode::decode(iter, cx)?,
                    body: Decode::decode(body, cx)?,
                    else_body: Decode::decode(else_body, cx)?,
                },
                wire::HirStmt::AsyncFor {
                    target,
                    target_ty,
                    iter,
                    iter_error_ty,
                    close_error_ty,
                    active_error_ty,
                    body_may_raise,
                    body,
                    else_body,
                } => Self::AsyncFor {
                    target: Decode::decode(target, cx)?,
                    target_ty: Decode::decode(target_ty, cx)?,
                    iter: Decode::decode(iter, cx)?,
                    iter_error_ty: Decode::decode(iter_error_ty, cx)?,
                    close_error_ty: Decode::decode(close_error_ty, cx)?,
                    active_error_ty: Decode::decode(active_error_ty, cx)?,
                    body_may_raise: Decode::decode(body_may_raise, cx)?,
                    body: Decode::decode(body, cx)?,
                    else_body: Decode::decode(else_body, cx)?,
                },
                wire::HirStmt::Break => Self::Break,
                wire::HirStmt::Continue => Self::Continue,
                wire::HirStmt::TupleUnpack { targets, value } => Self::TupleUnpack {
                    targets: Decode::decode(targets, cx)?,
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::StarUnpack {
                    before,
                    star,
                    after,
                    value,
                    failure,
                } => Self::StarUnpack {
                    before: Decode::decode(before, cx)?,
                    star: Decode::decode(star, cx)?,
                    after: Decode::decode(after, cx)?,
                    value: Decode::decode(value, cx)?,
                    failure: Decode::decode(failure, cx)?,
                },
                wire::HirStmt::Pass => Self::Pass,
                wire::HirStmt::Assert { test, msg } => Self::Assert {
                    test: Decode::decode(test, cx)?,
                    msg: Decode::decode(msg, cx)?,
                },
                wire::HirStmt::Raise { value } => Self::Raise {
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::TryExcept {
                    body,
                    handlers,
                    body_error_types,
                } => Self::TryExcept {
                    body: Decode::decode(body, cx)?,
                    handlers: Decode::decode(handlers, cx)?,
                    body_error_types: Decode::decode(body_error_types, cx)?,
                },
                wire::HirStmt::TryFinally { body, finalbody } => Self::TryFinally {
                    body: Decode::decode(body, cx)?,
                    finalbody: Decode::decode(finalbody, cx)?,
                },
                wire::HirStmt::FieldAssign {
                    object,
                    field,
                    field_ty,
                    value,
                } => Self::FieldAssign {
                    object: Decode::decode(object, cx)?,
                    field: Decode::decode(field, cx)?,
                    field_ty: Decode::decode(field_ty, cx)?,
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::NestedFieldAssign {
                    object,
                    field,
                    field_ty,
                    nested_field,
                    nested_field_ty,
                    value,
                } => Self::NestedFieldAssign {
                    object: Decode::decode(object, cx)?,
                    field: Decode::decode(field, cx)?,
                    field_ty: Decode::decode(field_ty, cx)?,
                    nested_field: Decode::decode(nested_field, cx)?,
                    nested_field_ty: Decode::decode(nested_field_ty, cx)?,
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::SubscriptAssign {
                    object,
                    index,
                    value,
                    object_ty,
                    failure,
                } => Self::SubscriptAssign {
                    object: Decode::decode(object, cx)?,
                    index: Decode::decode(index, cx)?,
                    value: Decode::decode(value, cx)?,
                    object_ty: Decode::decode(object_ty, cx)?,
                    failure: Decode::decode(failure, cx)?,
                },
                wire::HirStmt::NestedSubscriptAssign {
                    object,
                    outer_index,
                    inner_index,
                    value,
                    object_ty,
                    outer_failure,
                    inner_failure,
                    operation,
                } => Self::NestedSubscriptAssign {
                    object: Decode::decode(object, cx)?,
                    outer_index: Decode::decode(outer_index, cx)?,
                    inner_index: Decode::decode(inner_index, cx)?,
                    value: Decode::decode(value, cx)?,
                    object_ty: Decode::decode(object_ty, cx)?,
                    outer_failure: Decode::decode(outer_failure, cx)?,
                    inner_failure: Decode::decode(inner_failure, cx)?,
                    operation: Decode::decode(operation, cx)?,
                },
                wire::HirStmt::AttributeNestedSubscriptAssign {
                    object,
                    field,
                    outer_index,
                    inner_index,
                    value,
                    field_ty,
                    outer_failure,
                    inner_failure,
                    operation,
                } => Self::AttributeNestedSubscriptAssign {
                    object: Decode::decode(object, cx)?,
                    field: Decode::decode(field, cx)?,
                    outer_index: Decode::decode(outer_index, cx)?,
                    inner_index: Decode::decode(inner_index, cx)?,
                    value: Decode::decode(value, cx)?,
                    field_ty: Decode::decode(field_ty, cx)?,
                    outer_failure: Decode::decode(outer_failure, cx)?,
                    inner_failure: Decode::decode(inner_failure, cx)?,
                    operation: Decode::decode(operation, cx)?,
                },
                wire::HirStmt::SubscriptAugAssign {
                    object,
                    index,
                    op,
                    value,
                    object_ty,
                    failure,
                } => Self::SubscriptAugAssign {
                    object: Decode::decode(object, cx)?,
                    index: Decode::decode(index, cx)?,
                    op: Decode::decode(op, cx)?,
                    value: Decode::decode(value, cx)?,
                    object_ty: Decode::decode(object_ty, cx)?,
                    failure: Decode::decode(failure, cx)?,
                },
                wire::HirStmt::AttributeAugAssign {
                    object,
                    field,
                    op,
                    value,
                } => Self::AttributeAugAssign {
                    object: Decode::decode(object, cx)?,
                    field: Decode::decode(field, cx)?,
                    op: Decode::decode(op, cx)?,
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::AttributeSubscriptAssign {
                    object,
                    field,
                    index,
                    value,
                    field_ty,
                    failure,
                    operation,
                } => Self::AttributeSubscriptAssign {
                    object: Decode::decode(object, cx)?,
                    field: Decode::decode(field, cx)?,
                    index: Decode::decode(index, cx)?,
                    value: Decode::decode(value, cx)?,
                    field_ty: Decode::decode(field_ty, cx)?,
                    failure: Decode::decode(failure, cx)?,
                    operation: Decode::decode(operation, cx)?,
                },
                wire::HirStmt::Delete {
                    object,
                    index,
                    failure,
                } => Self::Delete {
                    object: Decode::decode(object, cx)?,
                    index: Decode::decode(index, cx)?,
                    failure: Decode::decode(failure, cx)?,
                },
                wire::HirStmt::Yield { value } => Self::Yield {
                    value: Decode::decode(value, cx)?,
                },
                wire::HirStmt::With { items, body } => Self::With {
                    items: Decode::decode(items, cx)?,
                    body: Decode::decode(body, cx)?,
                },
                wire::HirStmt::AsyncWith { kind, target, body } => Self::AsyncWith {
                    kind: Decode::decode(kind, cx)?,
                    target: Decode::decode(target, cx)?,
                    body: Decode::decode(body, cx)?,
                },
                wire::HirStmt::NestedFunction {
                    func,
                    move_captures,
                    capture_clones,
                } => Self::NestedFunction {
                    func: Decode::decode(func, cx)?,
                    move_captures: Decode::decode(move_captures, cx)?,
                    capture_clones: Decode::decode(capture_clones, cx)?,
                },
                wire::HirStmt::Match {
                    subject,
                    subject_ty,
                    arms,
                } => Self::Match {
                    subject: Decode::decode(subject, cx)?,
                    subject_ty: Decode::decode(subject_ty, cx)?,
                    arms: Decode::decode(arms, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirCollectionMutation>> for sifr_ir::HirCollectionMutation {
    fn decode(
        reference: &wire::Ref<wire::HirCollectionMutation>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirCollectionMutation::Assign => Self::Assign,
                wire::HirCollectionMutation::AugAssign(v0) => {
                    Self::AugAssign(Decode::decode(v0, cx)?)
                }
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirMatchArm>> for sifr_ir::HirMatchArm {
    fn decode(reference: &wire::Ref<wire::HirMatchArm>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                pattern: Decode::decode(&value.pattern, cx)?,
                guard: Decode::decode(&value.guard, cx)?,
                body: Decode::decode(&value.body, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirPattern>> for sifr_ir::HirPattern {
    fn decode(reference: &wire::Ref<wire::HirPattern>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirPattern::Wildcard => Self::Wildcard,
                wire::HirPattern::Capture { name, ty } => Self::Capture {
                    name: Decode::decode(name, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirPattern::Literal { value } => Self::Literal {
                    value: Decode::decode(value, cx)?,
                },
                wire::HirPattern::None => Self::None,
                wire::HirPattern::Or { patterns } => Self::Or {
                    patterns: Decode::decode(patterns, cx)?,
                },
                wire::HirPattern::Class {
                    class_name,
                    class_type,
                    fields,
                } => Self::Class {
                    class_name: Decode::decode(class_name, cx)?,
                    class_type: Decode::decode(class_type, cx)?,
                    fields: Decode::decode(fields, cx)?,
                },
                wire::HirPattern::Value { path } => Self::Value {
                    path: Decode::decode(path, cx)?,
                },
                wire::HirPattern::Tuple { elements } => Self::Tuple {
                    elements: Decode::decode(elements, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirExceptHandler>> for sifr_ir::HirExceptHandler {
    fn decode(reference: &wire::Ref<wire::HirExceptHandler>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                error_type: Decode::decode(&value.error_type, cx)?,
                error_resolved_type: Decode::decode(&value.error_resolved_type, cx)?,
                name: Decode::decode(&value.name, cx)?,
                body: Decode::decode(&value.body, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirFStringPart>> for sifr_ir::HirFStringPart {
    fn decode(reference: &wire::Ref<wire::HirFStringPart>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirFStringPart::Literal(v0) => Self::Literal(Decode::decode(v0, cx)?),
                wire::HirFStringPart::Expr(v0) => Self::Expr(Decode::decode(v0, cx)?),
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirIteratorOp>> for sifr_ir::HirIteratorOp {
    fn decode(reference: &wire::Ref<wire::HirIteratorOp>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirIteratorOp::Iter => Self::Iter,
                wire::HirIteratorOp::Next => Self::Next,
                wire::HirIteratorOp::Reversed => Self::Reversed,
                wire::HirIteratorOp::Map => Self::Map,
                wire::HirIteratorOp::Filter => Self::Filter,
                wire::HirIteratorOp::Zip => Self::Zip,
                wire::HirIteratorOp::Enumerate => Self::Enumerate,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirExpr>> for sifr_ir::HirExpr {
    fn decode(reference: &wire::Ref<wire::HirExpr>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirExpr::IntLiteral(v0) => Self::IntLiteral(Decode::decode(v0, cx)?),
                wire::HirExpr::LargeIntLiteral(v0) => {
                    Self::LargeIntLiteral(Decode::decode(v0, cx)?)
                }
                wire::HirExpr::FloatLiteral(v0) => Self::FloatLiteral(Decode::decode(v0, cx)?),
                wire::HirExpr::StringLiteral(v0) => Self::StringLiteral(Decode::decode(v0, cx)?),
                wire::HirExpr::BoolLiteral(v0) => Self::BoolLiteral(Decode::decode(v0, cx)?),
                wire::HirExpr::NoneLiteral => Self::NoneLiteral,
                wire::HirExpr::Name {
                    name,
                    binding_id,
                    ty,
                } => Self::Name {
                    name: Decode::decode(name, cx)?,
                    binding_id: Decode::decode(binding_id, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::BinOp {
                    left,
                    op,
                    right,
                    ty,
                } => Self::BinOp {
                    left: Decode::decode(left, cx)?,
                    op: Decode::decode(op, cx)?,
                    right: Decode::decode(right, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::UnaryOp { op, operand, ty } => Self::UnaryOp {
                    op: Decode::decode(op, cx)?,
                    operand: Decode::decode(operand, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::Compare {
                    left,
                    ops,
                    comparators,
                    ty,
                } => Self::Compare {
                    left: Decode::decode(left, cx)?,
                    ops: Decode::decode(ops, cx)?,
                    comparators: Decode::decode(comparators, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::BoolOp { op, values, ty } => Self::BoolOp {
                    op: Decode::decode(op, cx)?,
                    values: Decode::decode(values, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::Call {
                    func,
                    args,
                    mutable_arg_places,
                    ty,
                } => Self::Call {
                    func: Decode::decode(func, cx)?,
                    args: Decode::decode(args, cx)?,
                    mutable_arg_places: Decode::decode(mutable_arg_places, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::GenericCall {
                    func,
                    type_args,
                    args,
                    mutable_arg_places,
                    ty,
                } => Self::GenericCall {
                    func: Decode::decode(func, cx)?,
                    type_args: Decode::decode(type_args, cx)?,
                    args: Decode::decode(args, cx)?,
                    mutable_arg_places: Decode::decode(mutable_arg_places, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::PythonCall {
                    func,
                    args,
                    provided_arguments,
                    record_expansions,
                    ty,
                } => Self::PythonCall {
                    func: Decode::decode(func, cx)?,
                    args: Decode::decode(args, cx)?,
                    provided_arguments: Decode::decode(provided_arguments, cx)?,
                    record_expansions: Decode::decode(record_expansions, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::IntrinsicCall {
                    intrinsic,
                    args,
                    ty,
                    call_range,
                    arg_ranges,
                } => Self::IntrinsicCall {
                    intrinsic: Decode::decode(intrinsic, cx)?,
                    args: Decode::decode(args, cx)?,
                    ty: Decode::decode(ty, cx)?,
                    call_range: Decode::decode(call_range, cx)?,
                    arg_ranges: Decode::decode(arg_ranges, cx)?,
                },
                wire::HirExpr::Await { value, ty } => Self::Await {
                    value: Decode::decode(value, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::IteratorCall {
                    op,
                    args,
                    mutable_arg_places,
                    ty,
                } => Self::IteratorCall {
                    op: Decode::decode(op, cx)?,
                    args: Decode::decode(args, cx)?,
                    mutable_arg_places: Decode::decode(mutable_arg_places, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::IfExpr {
                    condition,
                    then_expr,
                    else_expr,
                    ty,
                } => Self::IfExpr {
                    condition: Decode::decode(condition, cx)?,
                    then_expr: Decode::decode(then_expr, cx)?,
                    else_expr: Decode::decode(else_expr, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::RangeLiteral {
                    start,
                    end,
                    step,
                    ty,
                } => Self::RangeLiteral {
                    start: Decode::decode(start, cx)?,
                    end: Decode::decode(end, cx)?,
                    step: Decode::decode(step, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::ListLiteral { elements, ty } => Self::ListLiteral {
                    elements: Decode::decode(elements, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::SetLiteral { elements, ty } => Self::SetLiteral {
                    elements: Decode::decode(elements, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::DictLiteral { keys, values, ty } => Self::DictLiteral {
                    keys: Decode::decode(keys, cx)?,
                    values: Decode::decode(values, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::TupleLiteral { elements, ty } => Self::TupleLiteral {
                    elements: Decode::decode(elements, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::Index { object, index, ty } => Self::Index {
                    object: Decode::decode(object, cx)?,
                    index: Decode::decode(index, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::MethodCall {
                    object,
                    method,
                    args,
                    receiver_convention,
                    receiver_target,
                    mutable_arg_places,
                    source,
                    ty,
                } => Self::MethodCall {
                    object: Decode::decode(object, cx)?,
                    method: Decode::decode(method, cx)?,
                    args: Decode::decode(args, cx)?,
                    receiver_convention: Decode::decode(receiver_convention, cx)?,
                    receiver_target: Decode::decode(receiver_target, cx)?,
                    mutable_arg_places: Decode::decode(mutable_arg_places, cx)?,
                    source: Decode::decode(source, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::ContainsOp {
                    element,
                    collection,
                    ty,
                } => Self::ContainsOp {
                    element: Decode::decode(element, cx)?,
                    collection: Decode::decode(collection, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::FString { parts, ty } => Self::FString {
                    parts: Decode::decode(parts, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::TemplateString(v0) => Self::TemplateString(Decode::decode(v0, cx)?),
                wire::HirExpr::Slice {
                    object,
                    start,
                    stop,
                    step,
                    ty,
                } => Self::Slice {
                    object: Decode::decode(object, cx)?,
                    start: Decode::decode(start, cx)?,
                    stop: Decode::decode(stop, cx)?,
                    step: Decode::decode(step, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::WalrusExpr { name, value, ty } => Self::WalrusExpr {
                    name: Decode::decode(name, cx)?,
                    value: Decode::decode(value, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::FieldAccess { object, field, ty } => Self::FieldAccess {
                    object: Decode::decode(object, cx)?,
                    field: Decode::decode(field, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::StructuralRecordProject { source, fields, ty } => {
                    Self::StructuralRecordProject {
                        source: Decode::decode(source, cx)?,
                        fields: Decode::decode(fields, cx)?,
                        ty: Decode::decode(ty, cx)?,
                    }
                }
                wire::HirExpr::ConstructorCall {
                    class_name,
                    args,
                    ty,
                } => Self::ConstructorCall {
                    class_name: Decode::decode(class_name, cx)?,
                    args: Decode::decode(args, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::QuestionMark { expr, ty } => Self::QuestionMark {
                    expr: Decode::decode(expr, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::OkWrap { value, ty } => Self::OkWrap {
                    value: Decode::decode(value, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::ErrWrap { value, ty } => Self::ErrWrap {
                    value: Decode::decode(value, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::SuperCall {
                    parent_class,
                    parent_type,
                    method,
                    args,
                    ty,
                } => Self::SuperCall {
                    parent_class: Decode::decode(parent_class, cx)?,
                    parent_type: Decode::decode(parent_type, cx)?,
                    method: Decode::decode(method, cx)?,
                    args: Decode::decode(args, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::Lambda { params, body, ty } => Self::Lambda {
                    params: Decode::decode(params, cx)?,
                    body: Decode::decode(body, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::ListComp {
                    expr,
                    generators,
                    ty,
                } => Self::ListComp {
                    expr: Decode::decode(expr, cx)?,
                    generators: Decode::decode(generators, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::DictComp {
                    key_expr,
                    val_expr,
                    generators,
                    ty,
                } => Self::DictComp {
                    key_expr: Decode::decode(key_expr, cx)?,
                    val_expr: Decode::decode(val_expr, cx)?,
                    generators: Decode::decode(generators, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::SetComp {
                    expr,
                    generators,
                    ty,
                } => Self::SetComp {
                    expr: Decode::decode(expr, cx)?,
                    generators: Decode::decode(generators, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::GeneratorExpr {
                    expr,
                    var,
                    iter,
                    filter,
                    ty,
                } => Self::GeneratorExpr {
                    expr: Decode::decode(expr, cx)?,
                    var: Decode::decode(var, cx)?,
                    iter: Decode::decode(iter, cx)?,
                    filter: Decode::decode(filter, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
                wire::HirExpr::EnumVariant {
                    enum_name,
                    variant,
                    ty,
                } => Self::EnumVariant {
                    enum_name: Decode::decode(enum_name, cx)?,
                    variant: Decode::decode(variant, cx)?,
                    ty: Decode::decode(ty, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTupleTargetBinding>> for sifr_ir::HirTupleTargetBinding {
    fn decode(
        reference: &wire::Ref<wire::HirTupleTargetBinding>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirTupleTargetBinding::Name(v0) => Self::Name(Decode::decode(v0, cx)?),
                wire::HirTupleTargetBinding::Field { object, field } => Self::Field {
                    object: Decode::decode(object, cx)?,
                    field: Decode::decode(field, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTupleTarget>> for sifr_ir::HirTupleTarget {
    fn decode(reference: &wire::Ref<wire::HirTupleTarget>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                binding: Decode::decode(&value.binding, cx)?,
                ty: Decode::decode(&value.ty, cx)?,
                rebind_existing: Decode::decode(&value.rebind_existing, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonRecordExpansion>> for sifr_ir::PythonRecordExpansion {
    fn decode(
        reference: &wire::Ref<wire::PythonRecordExpansion>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                span: Decode::decode(&value.span, cx)?,
                fields: Decode::decode(&value.fields, cx)?,
            })
        })
    }
}
