// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::PythonTargetPath>> for sifr_ir::PythonTargetPath {
    fn decode(reference: &wire::Ref<wire::PythonTargetPath>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                segments: Decode::decode(&value.segments, cx)?,
                span: Decode::decode(&value.span, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonInteropDecoratorKind>> for sifr_ir::PythonInteropDecoratorKind {
    fn decode(
        reference: &wire::Ref<wire::PythonInteropDecoratorKind>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonInteropDecoratorKind::Function => Self::Function,
                wire::PythonInteropDecoratorKind::Coroutine => Self::Coroutine,
                wire::PythonInteropDecoratorKind::Opaque => Self::Opaque,
                wire::PythonInteropDecoratorKind::Attribute => Self::Attribute,
                wire::PythonInteropDecoratorKind::Item => Self::Item,
                wire::PythonInteropDecoratorKind::ContextEnter => Self::ContextEnter,
                wire::PythonInteropDecoratorKind::ContextExit => Self::ContextExit,
                wire::PythonInteropDecoratorKind::ContextAsyncEnter => Self::ContextAsyncEnter,
                wire::PythonInteropDecoratorKind::ContextAsyncExit => Self::ContextAsyncExit,
                wire::PythonInteropDecoratorKind::Callback => Self::Callback,
                wire::PythonInteropDecoratorKind::Buffer => Self::Buffer,
                wire::PythonInteropDecoratorKind::Arrow => Self::Arrow,
                wire::PythonInteropDecoratorKind::Dlpack => Self::Dlpack,
                wire::PythonInteropDecoratorKind::DlpackStream => Self::DlpackStream,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonBufferAccess>> for sifr_ir::PythonBufferAccess {
    fn decode(reference: &wire::Ref<wire::PythonBufferAccess>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonBufferAccess::Read => Self::Read,
                wire::PythonBufferAccess::Write => Self::Write,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonBufferLayout>> for sifr_ir::PythonBufferLayout {
    fn decode(reference: &wire::Ref<wire::PythonBufferLayout>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonBufferLayout::Any => Self::Any,
                wire::PythonBufferLayout::CContiguous => Self::CContiguous,
                wire::PythonBufferLayout::FContiguous => Self::FContiguous,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonBufferDeclaration>> for sifr_ir::PythonBufferDeclaration {
    fn decode(
        reference: &wire::Ref<wire::PythonBufferDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                element_type: Decode::decode(&value.element_type, cx)?,
                access: Decode::decode(&value.access, cx)?,
                layout: Decode::decode(&value.layout, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonArrowSchemaMode>> for sifr_ir::PythonArrowSchemaMode {
    fn decode(
        reference: &wire::Ref<wire::PythonArrowSchemaMode>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonArrowSchemaMode::Omitted => Self::Omitted,
                wire::PythonArrowSchemaMode::Parameter { name, span } => Self::Parameter {
                    name: Decode::decode(name, cx)?,
                    span: Decode::decode(span, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonArrowDeclaration>> for sifr_ir::PythonArrowDeclaration {
    fn decode(
        reference: &wire::Ref<wire::PythonArrowDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                kind: Decode::decode(&value.kind, cx)?,
                schema: Decode::decode(&value.schema, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonDlpackDevice>> for sifr_ir::PythonDlpackDevice {
    fn decode(reference: &wire::Ref<wire::PythonDlpackDevice>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonDlpackDevice::Cpu => Self::Cpu,
                wire::PythonDlpackDevice::Cuda => Self::Cuda,
                wire::PythonDlpackDevice::Any => Self::Any,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonDlpackStreamMode>> for sifr_ir::PythonDlpackStreamMode {
    fn decode(
        reference: &wire::Ref<wire::PythonDlpackStreamMode>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonDlpackStreamMode::None => Self::None,
                wire::PythonDlpackStreamMode::Parameter { name, span } => Self::Parameter {
                    name: Decode::decode(name, cx)?,
                    span: Decode::decode(span, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonDlpackDeclaration>> for sifr_ir::PythonDlpackDeclaration {
    fn decode(
        reference: &wire::Ref<wire::PythonDlpackDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                device: Decode::decode(&value.device, cx)?,
                stream: Decode::decode(&value.stream, cx)?,
                element_type: Decode::decode(&value.element_type, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonInteropEffect>> for sifr_ir::PythonInteropEffect {
    fn decode(reference: &wire::Ref<wire::PythonInteropEffect>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonInteropEffect::BlockingIo => Self::BlockingIo,
                wire::PythonInteropEffect::Async => Self::Async,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonCleanupPolicy>> for sifr_ir::PythonCleanupPolicy {
    fn decode(reference: &wire::Ref<wire::PythonCleanupPolicy>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonCleanupPolicy::Drop => Self::Drop,
                wire::PythonCleanupPolicy::Close => Self::Close,
                wire::PythonCleanupPolicy::AsyncClose => Self::AsyncClose,
                wire::PythonCleanupPolicy::Context => Self::Context,
                wire::PythonCleanupPolicy::AsyncContext => Self::AsyncContext,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonParameterKind>> for sifr_ir::PythonParameterKind {
    fn decode(reference: &wire::Ref<wire::PythonParameterKind>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonParameterKind::Positional => Self::Positional,
                wire::PythonParameterKind::KeywordOnly => Self::KeywordOnly,
                wire::PythonParameterKind::PositionalVariadic => Self::PositionalVariadic,
                wire::PythonParameterKind::KeywordVariadic => Self::KeywordVariadic,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonCallbackLifetime>> for sifr_ir::PythonCallbackLifetime {
    fn decode(
        reference: &wire::Ref<wire::PythonCallbackLifetime>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonCallbackLifetime::Call => Self::Call,
                wire::PythonCallbackLifetime::Result => Self::Result,
                wire::PythonCallbackLifetime::Receiver => Self::Receiver,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonCallbackDispatch>> for sifr_ir::PythonCallbackDispatch {
    fn decode(
        reference: &wire::Ref<wire::PythonCallbackDispatch>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonCallbackDispatch::Current => Self::Current,
                wire::PythonCallbackDispatch::Foreign => Self::Foreign,
                wire::PythonCallbackDispatch::Asyncio => Self::Asyncio,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonCallbackConcurrency>> for sifr_ir::PythonCallbackConcurrency {
    fn decode(
        reference: &wire::Ref<wire::PythonCallbackConcurrency>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonCallbackConcurrency::Serial => Self::Serial,
                wire::PythonCallbackConcurrency::Parallel => Self::Parallel,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonCallbackDeclaration>> for sifr_ir::PythonCallbackDeclaration {
    fn decode(
        reference: &wire::Ref<wire::PythonCallbackDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                parameter_name: Decode::decode(&value.parameter_name, cx)?,
                span: Decode::decode(&value.span, cx)?,
                lifetime: Decode::decode(&value.lifetime, cx)?,
                dispatch: Decode::decode(&value.dispatch, cx)?,
                concurrency: Decode::decode(&value.concurrency, cx)?,
                argument_types: Decode::decode(&value.argument_types, cx)?,
                argument_conventions: Decode::decode(&value.argument_conventions, cx)?,
                success_type: Decode::decode(&value.success_type, cx)?,
                handler_error_type: Decode::decode(&value.handler_error_type, cx)?,
                is_async: Decode::decode(&value.is_async, cx)?,
                owner_class: Decode::decode(&value.owner_class, cx)?,
                owner_cleanup: Decode::decode(&value.owner_cleanup, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonInteropParameter>> for sifr_ir::PythonInteropParameter {
    fn decode(
        reference: &wire::Ref<wire::PythonInteropParameter>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                name: Decode::decode(&value.name, cx)?,
                kind: Decode::decode(&value.kind, cx)?,
                has_default: Decode::decode(&value.has_default, cx)?,
                omit_when_absent: Decode::decode(&value.omit_when_absent, cx)?,
                span: Decode::decode(&value.span, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::PythonInteropDeclaration>> for sifr_ir::PythonInteropDeclaration {
    fn decode(
        reference: &wire::Ref<wire::PythonInteropDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                kind: Decode::decode(&value.kind, cx)?,
                target: Decode::decode(&value.target, cx)?,
                span: Decode::decode(&value.span, cx)?,
                effect: Decode::decode(&value.effect, cx)?,
                cleanup: Decode::decode(&value.cleanup, cx)?,
                consumes_receiver: Decode::decode(&value.consumes_receiver, cx)?,
                parameters: Decode::decode(&value.parameters, cx)?,
                required_import_root: Decode::decode(&value.required_import_root, cx)?,
                callbacks: Decode::decode(&value.callbacks, cx)?,
                buffer: Decode::decode(&value.buffer, cx)?,
                arrow: Decode::decode(&value.arrow, cx)?,
                dlpack: Decode::decode(&value.dlpack, cx)?,
            })
        })
    }
}
