// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
pub(super) fn project(
    module: &str,
    record: wire::Ref<wire::SemanticExports>,
    cx: &mut Decoder,
) -> Result<sifr_lowering::ExternalDefs> {
    let value = cx.store.get(record)?;
    let mut defs = sifr_lowering::ExternalDefs::default();
    defs.functions
        .insert(module.to_owned(), Decode::decode(&value.functions, cx)?);
    defs.compiler_intrinsics.insert(
        module.to_owned(),
        Decode::decode(&value.compiler_intrinsics, cx)?,
    );
    defs.classes
        .insert(module.to_owned(), Decode::decode(&value.classes, cx)?);
    defs.generic_type_aliases.insert(
        module.to_owned(),
        Decode::decode(&value.generic_type_aliases, cx)?,
    );
    defs.class_instance_methods.insert(
        module.to_owned(),
        Decode::decode(&value.class_instance_methods, cx)?,
    );
    defs.rust_consuming_methods.insert(
        module.to_owned(),
        Decode::decode(&value.rust_consuming_methods, cx)?,
    );
    defs.rust_opaque_classes.insert(
        module.to_owned(),
        Decode::decode(&value.rust_opaque_classes, cx)?,
    );
    defs.rust_structural_classes.insert(
        module.to_owned(),
        Decode::decode(&value.rust_structural_classes, cx)?,
    );
    defs.class_type_params.insert(
        module.to_owned(),
        Decode::decode(&value.class_type_params, cx)?,
    );
    defs.replace_structural_methods(module, Decode::decode(&value.structural_methods, cx)?);
    defs.class_field_defaults.insert(
        module.to_owned(),
        Decode::decode(&value.class_field_defaults, cx)?,
    );
    defs.declaration_metadata.insert(
        module.to_owned(),
        Decode::decode(&value.declaration_metadata, cx)?,
    );
    defs.class_adapter_providers.insert(
        module.to_owned(),
        Decode::decode(&value.class_adapter_providers, cx)?,
    );
    defs.class_adapter_markers.insert(
        module.to_owned(),
        Decode::decode(&value.class_adapter_markers, cx)?,
    );
    defs.attached_api_sets.insert(
        module.to_owned(),
        Decode::decode(&value.attached_api_sets, cx)?,
    );
    defs.attached_apis
        .insert(module.to_owned(), Decode::decode(&value.attached_apis, cx)?);
    defs.class_adapter_selections.insert(
        module.to_owned(),
        Decode::decode(&value.class_adapter_selections, cx)?,
    );
    defs.descriptor_functions.insert(
        module.to_owned(),
        Decode::decode(&value.descriptor_functions, cx)?,
    );
    defs.declaration_descriptors.insert(
        module.to_owned(),
        Decode::decode(&value.declaration_descriptors, cx)?,
    );
    defs.applied_adapter_metadata.insert(
        module.to_owned(),
        Decode::decode(&value.applied_adapter_metadata, cx)?,
    );
    defs.const_functions.insert(
        module.to_owned(),
        Decode::decode(&value.const_functions, cx)?,
    );
    defs.specialization_requests.insert(
        module.to_owned(),
        Decode::decode(&value.specialization_requests, cx)?,
    );
    defs.specialization_outputs.insert(
        module.to_owned(),
        Decode::decode(&value.specialization_outputs, cx)?,
    );
    defs.json_integer_boundary_requests.insert(
        module.to_owned(),
        Decode::decode(&value.json_integer_boundary_requests, cx)?,
    );
    defs.constants
        .insert(module.to_owned(), Decode::decode(&value.constants, cx)?);
    defs.constant_integer_values.insert(
        module.to_owned(),
        Decode::decode(&value.constant_integer_values, cx)?,
    );
    defs.error_types
        .insert(module.to_owned(), Decode::decode(&value.error_types, cx)?);
    defs.type_param_bounds.insert(
        module.to_owned(),
        Decode::decode(&value.type_param_bounds, cx)?,
    );
    defs.generic_functions.insert(
        module.to_owned(),
        Decode::decode(&value.generic_functions, cx)?,
    );
    defs.function_varargs.insert(
        module.to_owned(),
        Decode::decode(&value.function_varargs, cx)?,
    );
    defs.function_python_call_shapes.insert(
        module.to_owned(),
        Decode::decode(&value.function_python_call_shapes, cx)?,
    );
    defs.rust_threadsafe_callback_targets.insert(
        module.to_owned(),
        Decode::decode(&value.rust_threadsafe_callback_targets, cx)?,
    );
    defs.function_workloads.insert(
        module.to_owned(),
        Decode::decode(&value.function_workloads, cx)?,
    );
    defs.function_defaults.insert(
        module.to_owned(),
        Decode::decode(&value.function_defaults, cx)?,
    );
    defs.freeze_baseline();
    Ok(defs)
}
impl Decode<wire::Ref<wire::StructuralMethodExport>> for sifr_lowering::StructuralMethodExport {
    fn decode(
        reference: &wire::Ref<wire::StructuralMethodExport>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            Ok(Self {
                handler_target: Decode::decode(&value.handler_target, cx)?,
                name: Decode::decode(&value.name, cx)?,
                params: Decode::decode(&value.params, cx)?,
                return_type: Decode::decode(&value.return_type, cx)?,
                is_async: Decode::decode(&value.is_async, cx)?,
                method_kind: Decode::decode(&value.method_kind, cx)?,
                receiver: Decode::decode(&value.receiver, cx)?,
            })
        })
    }
}
