// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::DeclarationMetadataTargetKind>>
    for sifr_ir::DeclarationMetadataTargetKind
{
    fn decode(
        reference: &wire::Ref<wire::DeclarationMetadataTargetKind>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::DeclarationMetadataTargetKind::Type => Self::Type,
                wire::DeclarationMetadataTargetKind::Field => Self::Field,
                wire::DeclarationMetadataTargetKind::EnumVariant => Self::EnumVariant,
                wire::DeclarationMetadataTargetKind::Function => Self::Function,
                wire::DeclarationMetadataTargetKind::Method => Self::Method,
                wire::DeclarationMetadataTargetKind::Parameter => Self::Parameter,
            })
        })
    }
}
impl Decode<wire::Ref<wire::TypedDeclarationMetadata>> for sifr_ir::TypedDeclarationMetadata {
    fn decode(
        reference: &wire::Ref<wire::TypedDeclarationMetadata>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner: Decode::decode(&value.owner, cx)?,
                target_kind: Decode::decode(&value.target_kind, cx)?,
                target_name: Decode::decode(&value.target_name, cx)?,
                key: Decode::decode(&value.key, cx)?,
                value_type: Decode::decode(&value.value_type, cx)?,
                value: Decode::decode(&value.value, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::ConstSpecializationRequest>> for sifr_ir::ConstSpecializationRequest {
    fn decode(
        reference: &wire::Ref<wire::ConstSpecializationRequest>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner: Decode::decode(&value.owner, cx)?,
                package_module: Decode::decode(&value.package_module, cx)?,
                function: Decode::decode(&value.function, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::DeclarationDescriptorKind>> for sifr_ir::DeclarationDescriptorKind {
    fn decode(
        reference: &wire::Ref<wire::DeclarationDescriptorKind>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::DeclarationDescriptorKind::Field => Self::Field,
                wire::DeclarationDescriptorKind::Class => Self::Class,
                wire::DeclarationDescriptorKind::Method => Self::Method,
                wire::DeclarationDescriptorKind::Type => Self::Type,
            })
        })
    }
}
impl Decode<wire::Ref<wire::ClassAdapterProviderDeclaration>>
    for sifr_ir::ClassAdapterProviderDeclaration
{
    fn decode(
        reference: &wire::Ref<wire::ClassAdapterProviderDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                module: Decode::decode(&value.module, cx)?,
                function: Decode::decode(&value.function, cx)?,
                descriptor_module: Decode::decode(&value.descriptor_module, cx)?,
                descriptor_symbol: Decode::decode(&value.descriptor_symbol, cx)?,
                descriptor_type: Decode::decode(&value.descriptor_type, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::ClassAdapterMarkerDeclaration>>
    for sifr_ir::ClassAdapterMarkerDeclaration
{
    fn decode(
        reference: &wire::Ref<wire::ClassAdapterMarkerDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                module: Decode::decode(&value.module, cx)?,
                symbol: Decode::decode(&value.symbol, cx)?,
                provider_module: Decode::decode(&value.provider_module, cx)?,
                provider_function: Decode::decode(&value.provider_function, cx)?,
                descriptor_type: Decode::decode(&value.descriptor_type, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AttachedApiSetIdentity>> for sifr_ir::AttachedApiSetIdentity {
    fn decode(
        reference: &wire::Ref<wire::AttachedApiSetIdentity>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                module: Decode::decode(&value.module, cx)?,
                symbol: Decode::decode(&value.symbol, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AttachedApiSetDeclaration>> for sifr_ir::AttachedApiSetDeclaration {
    fn decode(
        reference: &wire::Ref<wire::AttachedApiSetDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                identity: Decode::decode(&value.identity, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AttachedApiReceiver>> for sifr_ir::AttachedApiReceiver {
    fn decode(reference: &wire::Ref<wire::AttachedApiReceiver>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::AttachedApiReceiver::Type => Self::Type,
                wire::AttachedApiReceiver::Immutable => Self::Immutable,
                wire::AttachedApiReceiver::Mutable => Self::Mutable,
                wire::AttachedApiReceiver::Owned => Self::Owned,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AttachedApiDeclaration>> for sifr_ir::AttachedApiDeclaration {
    fn decode(
        reference: &wire::Ref<wire::AttachedApiDeclaration>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                module: Decode::decode(&value.module, cx)?,
                function: Decode::decode(&value.function, cx)?,
                set: Decode::decode(&value.set, cx)?,
                public_name: Decode::decode(&value.public_name, cx)?,
                receiver: Decode::decode(&value.receiver, cx)?,
                owner_type_param: Decode::decode(&value.owner_type_param, cx)?,
                type_params: Decode::decode(&value.type_params, cx)?,
                type_param_bounds: Decode::decode(&value.type_param_bounds, cx)?,
                function_type: Decode::decode(&value.function_type, cx)?,
                defaults: Decode::decode(&value.defaults, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::ClassAdapterSelection>> for sifr_ir::ClassAdapterSelection {
    fn decode(
        reference: &wire::Ref<wire::ClassAdapterSelection>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner: Decode::decode(&value.owner, cx)?,
                provider_module: Decode::decode(&value.provider_module, cx)?,
                provider_function: Decode::decode(&value.provider_function, cx)?,
                descriptor_type: Decode::decode(&value.descriptor_type, cx)?,
                marker_identities: Decode::decode(&value.marker_identities, cx)?,
                data_parent: Decode::decode(&value.data_parent, cx)?,
                field_plans: Decode::decode(&value.field_plans, cx)?,
                handler_plans: Decode::decode(&value.handler_plans, cx)?,
                attached_api_set: Decode::decode(&value.attached_api_set, cx)?,
                adapter_invocation_identity: Decode::decode(
                    &value.adapter_invocation_identity,
                    cx,
                )?,
                post_adapter_identity: Decode::decode(&value.post_adapter_identity, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AdapterHandlerPlan>> for sifr_ir::AdapterHandlerPlan {
    fn decode(reference: &wire::Ref<wire::AdapterHandlerPlan>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                callable: Decode::decode(&value.callable, cx)?,
                descriptor_type: Decode::decode(&value.descriptor_type, cx)?,
                descriptor_value: Decode::decode(&value.descriptor_value, cx)?,
                descriptor_origin: Decode::decode(&value.descriptor_origin, cx)?,
                descriptor_range: Decode::decode(&value.descriptor_range, cx)?,
                declaration_order: Decode::decode(&value.declaration_order, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AdapterFieldPlan>> for sifr_ir::AdapterFieldPlan {
    fn decode(reference: &wire::Ref<wire::AdapterFieldPlan>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                identity: Decode::decode(&value.identity, cx)?,
                name: Decode::decode(&value.name, cx)?,
                declared_type: Decode::decode(&value.declared_type, cx)?,
                default: Decode::decode(&value.default, cx)?,
                validation_policy: Decode::decode(&value.validation_policy, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AdapterFieldDefault>> for sifr_ir::AdapterFieldDefault {
    fn decode(reference: &wire::Ref<wire::AdapterFieldDefault>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::AdapterFieldDefault::Required => Self::Required,
                wire::AdapterFieldDefault::Const(v0) => Self::Const(Decode::decode(v0, cx)?),
                wire::AdapterFieldDefault::Factory(v0) => Self::Factory(Decode::decode(v0, cx)?),
            })
        })
    }
}
impl Decode<wire::Ref<wire::DeclarationDescriptorFunction>>
    for sifr_ir::DeclarationDescriptorFunction
{
    fn decode(
        reference: &wire::Ref<wire::DeclarationDescriptorFunction>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                module: Decode::decode(&value.module, cx)?,
                function: Decode::decode(&value.function, cx)?,
                provider_module: Decode::decode(&value.provider_module, cx)?,
                provider_function: Decode::decode(&value.provider_function, cx)?,
                descriptor_type: Decode::decode(&value.descriptor_type, cx)?,
                return_type: Decode::decode(&value.return_type, cx)?,
                kind: Decode::decode(&value.kind, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::CallableIdentity>> for sifr_ir::CallableIdentity {
    fn decode(reference: &wire::Ref<wire::CallableIdentity>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                module: Decode::decode(&value.module, cx)?,
                owner: Decode::decode(&value.owner, cx)?,
                symbol: Decode::decode(&value.symbol, cx)?,
                generic_arguments: Decode::decode(&value.generic_arguments, cx)?,
                signature: Decode::decode(&value.signature, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::TypedDeclarationDescriptor>> for sifr_ir::TypedDeclarationDescriptor {
    fn decode(
        reference: &wire::Ref<wire::TypedDeclarationDescriptor>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner: Decode::decode(&value.owner, cx)?,
                target_kind: Decode::decode(&value.target_kind, cx)?,
                target_identity: Decode::decode(&value.target_identity, cx)?,
                target_callable: Decode::decode(&value.target_callable, cx)?,
                provider_module: Decode::decode(&value.provider_module, cx)?,
                provider_function: Decode::decode(&value.provider_function, cx)?,
                value_type: Decode::decode(&value.value_type, cx)?,
                value: Decode::decode(&value.value, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::AppliedAdapterMetadata>> for sifr_ir::AppliedAdapterMetadata {
    fn decode(
        reference: &wire::Ref<wire::AppliedAdapterMetadata>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner: Decode::decode(&value.owner, cx)?,
                target_kind: Decode::decode(&value.target_kind, cx)?,
                target_name: Decode::decode(&value.target_name, cx)?,
                key: Decode::decode(&value.key, cx)?,
                value_type: Decode::decode(&value.value_type, cx)?,
                value: Decode::decode(&value.value, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::StaticProgramValue>> for sifr_ir::StaticProgramValue {
    fn decode(reference: &wire::Ref<wire::StaticProgramValue>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::StaticProgramValue::None => Self::None,
                wire::StaticProgramValue::Bool(v0) => Self::Bool(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::Integer(v0) => Self::Integer(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::FloatBits(v0) => Self::FloatBits(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::String(v0) => Self::String(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::Bytes(v0) => Self::Bytes(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::Tuple(v0) => Self::Tuple(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::List(v0) => Self::List(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::Record(v0) => Self::Record(Decode::decode(v0, cx)?),
                wire::StaticProgramValue::CallableIdentity(v0) => {
                    Self::CallableIdentity(Decode::decode(v0, cx)?)
                }
            })
        })
    }
}
impl Decode<wire::Ref<wire::StaticSpecializationOutput>> for sifr_ir::StaticSpecializationOutput {
    fn decode(
        reference: &wire::Ref<wire::StaticSpecializationOutput>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner: Decode::decode(&value.owner, cx)?,
                package_module: Decode::decode(&value.package_module, cx)?,
                function: Decode::decode(&value.function, cx)?,
                canonical_value: Decode::decode(&value.canonical_value, cx)?,
                value: Decode::decode(&value.value, cx)?,
                program_identity: Decode::decode(&value.program_identity, cx)?,
                structural_contract_version: Decode::decode(
                    &value.structural_contract_version,
                    cx,
                )?,
                method_slots: Decode::decode(&value.method_slots, cx)?,
                method_slot_context: Decode::decode(&value.method_slot_context, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::StaticMethodSlotContext>> for sifr_ir::StaticMethodSlotContext {
    fn decode(
        reference: &wire::Ref<wire::StaticMethodSlotContext>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::StaticMethodSlotContext::None => Self::None,
                wire::StaticMethodSlotContext::Shared(v0) => Self::Shared(Decode::decode(v0, cx)?),
                wire::StaticMethodSlotContext::Mutable(v0) => {
                    Self::Mutable(Decode::decode(v0, cx)?)
                }
            })
        })
    }
}
impl Decode<wire::Ref<wire::StaticMethodSlotInputRole>> for sifr_ir::StaticMethodSlotInputRole {
    fn decode(
        reference: &wire::Ref<wire::StaticMethodSlotInputRole>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::StaticMethodSlotInputRole::Value => Self::Value,
                wire::StaticMethodSlotInputRole::Receiver => Self::Receiver,
                wire::StaticMethodSlotInputRole::ReceiverAndValue => Self::ReceiverAndValue,
            })
        })
    }
}
impl Decode<wire::Ref<wire::StaticMethodSlot>> for sifr_ir::StaticMethodSlot {
    fn decode(reference: &wire::Ref<wire::StaticMethodSlot>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner_identity: Decode::decode(&value.owner_identity, cx)?,
                owner_type: Decode::decode(&value.owner_type, cx)?,
                name: Decode::decode(&value.name, cx)?,
                hir_name: Decode::decode(&value.hir_name, cx)?,
                method_kind: Decode::decode(&value.method_kind, cx)?,
                receiver: Decode::decode(&value.receiver, cx)?,
                params: Decode::decode(&value.params, cx)?,
                return_type: Decode::decode(&value.return_type, cx)?,
                is_async: Decode::decode(&value.is_async, cx)?,
                input_role: Decode::decode(&value.input_role, cx)?,
                input_type: Decode::decode(&value.input_type, cx)?,
                output_type: Decode::decode(&value.output_type, cx)?,
                context_type: Decode::decode(&value.context_type, cx)?,
                context_mutable: Decode::decode(&value.context_mutable, cx)?,
                descriptor_type: Decode::decode(&value.descriptor_type, cx)?,
                descriptor_value: Decode::decode(&value.descriptor_value, cx)?,
                descriptor_origin: Decode::decode(&value.descriptor_origin, cx)?,
                descriptor_range: Decode::decode(&value.descriptor_range, cx)?,
                declaration_order: Decode::decode(&value.declaration_order, cx)?,
                is_fallible: Decode::decode(&value.is_fallible, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::StaticMethodParam>> for sifr_ir::StaticMethodParam {
    fn decode(reference: &wire::Ref<wire::StaticMethodParam>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                name: Decode::decode(&value.name, cx)?,
                ty: Decode::decode(&value.ty, cx)?,
                keyword_only: Decode::decode(&value.keyword_only, cx)?,
                convention: Decode::decode(&value.convention, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::JsonIntegerBoundaryRequest>> for sifr_ir::JsonIntegerBoundaryRequest {
    fn decode(
        reference: &wire::Ref<wire::JsonIntegerBoundaryRequest>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                owner: Decode::decode(&value.owner, cx)?,
                field: Decode::decode(&value.field, cx)?,
                profile: Decode::decode(&value.profile, cx)?,
                representation: Decode::decode(&value.representation, cx)?,
                static_minimum: Decode::decode(&value.static_minimum, cx)?,
                static_maximum: Decode::decode(&value.static_maximum, cx)?,
                range: Decode::decode(&value.range, cx)?,
            })
        })
    }
}
