// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::HirSqlQueryAdapter>> for sifr_ir::HirSqlQueryAdapter {
    fn decode(reference: &wire::Ref<wire::HirSqlQueryAdapter>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirSqlQueryAdapter::ExpectAtMostOne => Self::ExpectAtMostOne,
                wire::HirSqlQueryAdapter::First => Self::First,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlEffectKind>> for sifr_ir::HirSqlEffectKind {
    fn decode(reference: &wire::Ref<wire::HirSqlEffectKind>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirSqlEffectKind::Read => Self::Read,
                wire::HirSqlEffectKind::Write => Self::Write,
                wire::HirSqlEffectKind::ReadWrite => Self::ReadWrite,
                wire::HirSqlEffectKind::SchemaChange => Self::SchemaChange,
                wire::HirSqlEffectKind::SessionChange => Self::SessionChange,
                wire::HirSqlEffectKind::TransactionControl => Self::TransactionControl,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlCardinality>> for sifr_ir::HirSqlCardinality {
    fn decode(reference: &wire::Ref<wire::HirSqlCardinality>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                empty: Decode::decode(&value.empty, cx)?,
                minimum: Decode::decode(&value.minimum, cx)?,
                maximum: Decode::decode(&value.maximum, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlEffectContract>> for sifr_ir::HirSqlEffectContract {
    fn decode(reference: &wire::Ref<wire::HirSqlEffectContract>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                effect: Decode::decode(&value.effect, cx)?,
                referenced_objects: Decode::decode(&value.referenced_objects, cx)?,
                affected_objects: Decode::decode(&value.affected_objects, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlParameterSlot>> for sifr_ir::HirSqlParameterSlot {
    fn decode(reference: &wire::Ref<wire::HirSqlParameterSlot>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                slot: Decode::decode(&value.slot, cx)?,
                ty: Decode::decode(&value.ty, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlQueryTemplate>> for sifr_ir::HirSqlQueryTemplate {
    fn decode(reference: &wire::Ref<wire::HirSqlQueryTemplate>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                identity: Decode::decode(&value.identity, cx)?,
                module: Decode::decode(&value.module, cx)?,
                symbol: Decode::decode(&value.symbol, cx)?,
                profile_identity: Decode::decode(&value.profile_identity, cx)?,
                profile_fingerprint: Decode::decode(&value.profile_fingerprint, cx)?,
                schema_fingerprint: Decode::decode(&value.schema_fingerprint, cx)?,
                normalized_statement: Decode::decode(&value.normalized_statement, cx)?,
                parameters: Decode::decode(&value.parameters, cx)?,
                row_type: Decode::decode(&value.row_type, cx)?,
                cardinality: Decode::decode(&value.cardinality, cx)?,
                effects: Decode::decode(&value.effects, cx)?,
                deterministic_order: Decode::decode(&value.deterministic_order, cx)?,
                fragment_identities: Decode::decode(&value.fragment_identities, cx)?,
                adapters: Decode::decode(&value.adapters, cx)?,
                ty: Decode::decode(&value.ty, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlBoundQuery>> for sifr_ir::HirSqlBoundQuery {
    fn decode(reference: &wire::Ref<wire::HirSqlBoundQuery>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                template_identity: Decode::decode(&value.template_identity, cx)?,
                profile_identity: Decode::decode(&value.profile_identity, cx)?,
                profile_fingerprint: Decode::decode(&value.profile_fingerprint, cx)?,
                schema_fingerprint: Decode::decode(&value.schema_fingerprint, cx)?,
                captures: Decode::decode(&value.captures, cx)?,
                cardinality: Decode::decode(&value.cardinality, cx)?,
                effects: Decode::decode(&value.effects, cx)?,
                ty: Decode::decode(&value.ty, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlExecutionMethod>> for sifr_ir::HirSqlExecutionMethod {
    fn decode(
        reference: &wire::Ref<wire::HirSqlExecutionMethod>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirSqlExecutionMethod::Execute => Self::Execute,
                wire::HirSqlExecutionMethod::FetchOne => Self::FetchOne,
                wire::HirSqlExecutionMethod::FetchOptional => Self::FetchOptional,
                wire::HirSqlExecutionMethod::FetchAll { maximum_rows } => Self::FetchAll {
                    maximum_rows: Decode::decode(maximum_rows, cx)?,
                },
                wire::HirSqlExecutionMethod::Stream => Self::Stream,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirSqlExecution>> for sifr_ir::HirSqlExecution {
    fn decode(reference: &wire::Ref<wire::HirSqlExecution>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                query: Decode::decode(&value.query, cx)?,
                method: Decode::decode(&value.method, cx)?,
                runtime_cardinality: Decode::decode(&value.runtime_cardinality, cx)?,
                runtime_effects: Decode::decode(&value.runtime_effects, cx)?,
            })
        })
    }
}
