// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::HirTemplateSegment>> for sifr_ir::HirTemplateSegment {
    fn decode(reference: &wire::Ref<wire::HirTemplateSegment>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                value: Decode::decode(&value.value, cx)?,
                mappings: Decode::decode(&value.mappings, cx)?,
                virtual_range: Decode::decode(&value.virtual_range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTemplateStaticMapping>> for sifr_ir::HirTemplateStaticMapping {
    fn decode(
        reference: &wire::Ref<wire::HirTemplateStaticMapping>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                source_range: Decode::decode(&value.source_range, cx)?,
                virtual_range: Decode::decode(&value.virtual_range, cx)?,
                offsets: Decode::decode(&value.offsets, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTemplateOffsetMapping>> for sifr_ir::HirTemplateOffsetMapping {
    fn decode(
        reference: &wire::Ref<wire::HirTemplateOffsetMapping>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                source_range: Decode::decode(&value.source_range, cx)?,
                virtual_range: Decode::decode(&value.virtual_range, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTemplateFormatSpec>> for sifr_ir::HirTemplateFormatSpec {
    fn decode(
        reference: &wire::Ref<wire::HirTemplateFormatSpec>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                range: Decode::decode(&value.range, cx)?,
                parts: Decode::decode(&value.parts, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTemplateFormatSpecPart>> for sifr_ir::HirTemplateFormatSpecPart {
    fn decode(
        reference: &wire::Ref<wire::HirTemplateFormatSpecPart>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::HirTemplateFormatSpecPart::Literal(v0) => {
                    Self::Literal(Decode::decode(v0, cx)?)
                }
                wire::HirTemplateFormatSpecPart::Interpolation {
                    value,
                    clone_from_borrow,
                    source_range,
                    conversion,
                    format_spec,
                } => Self::Interpolation {
                    value: Decode::decode(value, cx)?,
                    clone_from_borrow: Decode::decode(clone_from_borrow, cx)?,
                    source_range: Decode::decode(source_range, cx)?,
                    conversion: Decode::decode(conversion, cx)?,
                    format_spec: Decode::decode(format_spec, cx)?,
                },
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTemplateInterpolation>> for sifr_ir::HirTemplateInterpolation {
    fn decode(
        reference: &wire::Ref<wire::HirTemplateInterpolation>,
        cx: &mut Decoder,
    ) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                value: Decode::decode(&value.value, cx)?,
                clone_from_borrow: Decode::decode(&value.clone_from_borrow, cx)?,
                value_type: Decode::decode(&value.value_type, cx)?,
                source_range: Decode::decode(&value.source_range, cx)?,
                expression_range: Decode::decode(&value.expression_range, cx)?,
                expression_source: Decode::decode(&value.expression_source, cx)?,
                virtual_range: Decode::decode(&value.virtual_range, cx)?,
                conversion: Decode::decode(&value.conversion, cx)?,
                format_spec: Decode::decode(&value.format_spec, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::HirTemplateString>> for sifr_ir::HirTemplateString {
    fn decode(reference: &wire::Ref<wire::HirTemplateString>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                source_range: Decode::decode(&value.source_range, cx)?,
                virtual_source: Decode::decode(&value.virtual_source, cx)?,
                segments: Decode::decode(&value.segments, cx)?,
                interpolations: Decode::decode(&value.interpolations, cx)?,
                ty: Decode::decode(&value.ty, cx)?,
            })
        })
    }
}
