// @generated by scripts/generate_metadata_decoders.py; DO NOT EDIT.
use super::{Decode, Decoder, Result, wire};
impl Decode<wire::Ref<wire::PythonArrowKind>> for sifr_type_system::PythonArrowKind {
    fn decode(reference: &wire::Ref<wire::PythonArrowKind>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::PythonArrowKind::Array => Self::Array,
                wire::PythonArrowKind::Schema => Self::Schema,
                wire::PythonArrowKind::Stream => Self::Stream,
                wire::PythonArrowKind::DeviceArray => Self::DeviceArray,
                wire::PythonArrowKind::DeviceStream => Self::DeviceStream,
            })
        })
    }
}
impl Decode<wire::Ref<wire::FixedIntType>> for sifr_type_system::FixedIntType {
    fn decode(reference: &wire::Ref<wire::FixedIntType>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::FixedIntType::I8 => Self::I8,
                wire::FixedIntType::I16 => Self::I16,
                wire::FixedIntType::I32 => Self::I32,
                wire::FixedIntType::I64 => Self::I64,
                wire::FixedIntType::U8 => Self::U8,
                wire::FixedIntType::U16 => Self::U16,
                wire::FixedIntType::U32 => Self::U32,
                wire::FixedIntType::U64 => Self::U64,
                wire::FixedIntType::ISize => Self::ISize,
                wire::FixedIntType::USize => Self::USize,
            })
        })
    }
}
impl Decode<wire::Ref<wire::FunctionType>> for sifr_type_system::FunctionType {
    fn decode(reference: &wire::Ref<wire::FunctionType>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(Self {
                receiver: Decode::decode(&value.receiver, cx)?,
                params: Decode::decode(&value.params, cx)?,
                return_type: Decode::decode(&value.return_type, cx)?,
            })
        })
    }
}
impl Decode<wire::Ref<wire::ReceiverConvention>> for sifr_type_system::ReceiverConvention {
    fn decode(reference: &wire::Ref<wire::ReceiverConvention>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::ReceiverConvention::SharedBorrow => Self::SharedBorrow,
                wire::ReceiverConvention::MutableBorrow => Self::MutableBorrow,
                wire::ReceiverConvention::Owned => Self::Owned,
                wire::ReceiverConvention::OwnedMutable => Self::OwnedMutable,
            })
        })
    }
}
impl Decode<wire::Ref<wire::ParamOwnership>> for sifr_type_system::ParamOwnership {
    fn decode(reference: &wire::Ref<wire::ParamOwnership>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::ParamOwnership::Borrow => Self::Borrow,
                wire::ParamOwnership::Own => Self::Own,
            })
        })
    }
}
impl Decode<wire::Ref<wire::ParamMutability>> for sifr_type_system::ParamMutability {
    fn decode(reference: &wire::Ref<wire::ParamMutability>, cx: &mut Decoder) -> Result<Self> {
        cx.record(*reference, |value, cx| {
            let _ = &cx;
            Ok(match value {
                wire::ParamMutability::Immutable => Self::Immutable,
                wire::ParamMutability::Mutable => Self::Mutable,
            })
        })
    }
}
